tektoncd/community

- README.md
- code-of-conduct.md
- governance.md
This PR explains that Tekton is governed by the knative build WG,
and adds a section explaining how to get a new repo created.
> Add a section on interim governance.

- CONTRIBUTING.md
- OWNERS
- README.md
- contact.md
- governance.md
- process.md
- standards.md
This takes the contributing guidelines from
https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md
and generalizes (and updates) them to apply to all projects in the
tektoncd org.
Following up to this, I will remove most of the content of
https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md
and link to this community repo instead.
Some new things:
* The guidelines on becoming an OWNERS are adapted from https://github.com/knative/docs/blob/master/contributing/ROLES.md#approver
* I changed the OWNERS file to contain the members of the governing
board
* I arbitrarily said that 50% of the governing board should review
PRs in this repo that change policy
Fixes #1 Fixes #3
p.s. Shout out to the person who came up to me yesterday and was so sad
that we had no contributing …
> Add CONTRIBUTING guidelines for all tektoncd projects ✔️

- README.md
- process.md
We have recently had some cool new projects added, like
`dashboard`, `cli` and `knative-eventing-extension`! This has happened
so fast that we got a bit ahead of documenting the process for doing
this, and we also made some on the fly decisions like creating an
`experimental` repo.
This is an attempt to catch up and document some guidelines so folks who
weren't part of these discussions can potentially propose projects too!
Not all of our repos currently meet the requirements outlined here so I
will be following up by attempting to bring them all up to speed.
Note that the "2 or more governing members" requirement was more or less
in the community project [from the start](https://github.com/tektoncd/community/commit/f78c3f7d7ef9233a16980803d70650619b92abc5#diff-898e7f1ceacb493c024554f5a7c8 …
> Add guidelines for new project creation 🎂

- code-of-conduct.md
- governance.md
We were still using the group from Knative! The Tekton project will now
have its own mailing list for reporting issues, and this change proposes
that governing committee members will be responsible for responding to
reports of violations.
> Create Tekton mailing list for code of conduct issues

- governance.md
This change assumes that all governing board members should get access
to all "plumbing" resources used in the Tekton org, so that they can
themselves hand out access as needed (ideally through service accounts
and roles vs. direct access).
> Document permissions that governing board members should get ⚖️

- contact.md
In a recent working group meeting, it was brought up that the CDF TOC
meeting overlapped with the Tekton Working group meeting (which has been
on Tuesdays at 9am PST) so I sent around a form and the most popular
option to move the meeting to is Wednesdays at 9am PST so let's try that
for a while.
This commit updates the info and posts a new link to the calendar event
which should now be on Wednesdays.
Relevant thread on the mailing list:
https://groups.google.com/forum/#!topic/tekton-dev/MlUfUJU-7N8
> Move working group to Wednesdays 📅

- contact.md
@aristosvo pointed out that our slack link doesn't work anymore!
(Thanks @aristosvo!!!) We didn't know when we made that link that we'd
use it like this so it was probably at the default expiration (30 days).
This new link should be "indefinite" so hopefully we can just keep using
it :D
Fixes #21
> Update slack link 💬

- governance.md
Unfortunately since the resources we are currently using for our
infrastructure are Google resources, we couldn't just give all governing
board members owner access too all the projects we are using. In the
long run we probably want to change this so that the infrastructure is
billed to the CDF, but in the short term we've scaled back the
permissions and are trying to pinpoint exactly the right set to make
sure ppl can do what they need to do.
I also tried to add these permissions to all the boskos projects but
there are about to be 14 of them
(https://github.com/tektoncd/plumbing/issues/29) and it turns out to be
super tedious to apply these individual permissions across 14 different
projects - and they can't share roles. So I decided to keep it simple
and not give everyone access to the …
> Update docs on changes to project access resources 👮

- README.md
- contact.md
This shared drive has been where we've been putting meeting group
recordings all this time but we haven't yet been using it for other
docs. Folks have been asking more and more recently for something like
this so now the drive should be editable by folks on the mailing list
and we can try to making design docs and meeting notes available here
when possible.
+ @afrittoli 
+ that person who asked for this in slack like 4 months ago :(
> Add link to shared doc drive 📁

- README.md
- contact.md
We've been having some ad-hoc meetings about triggers that have been
becoming more regular as we've found more in the design to discuss, and
more folks are interested in joining these meetings, so they are now
available on the public Tekton calendar!
Also added a link to the calendar itself and to a `#meetings` channel in
slack where people can announce more ad-hoc meetings that they'd like to
invite community folks to.
> Add calendar and triggers sync to docs 📅

- README.md
- contact.md
We had our first beta working group meeting today and decided to try to
hold it every 2 weeks as we go forward toward beta to keep in touch and
see how things are going.
Now that we have 3 regular meetings, I reorganized the working group
section a bit.
> Add link to beta working group meetings + agenda β

- contact.md
Docs are shared with `tekton-dev`, and the previous wording made this unclear.
cc @jchesterpivotal
> More clearly document doc visibility

- process.md
This process explains a mechanism to be added as an OWNER on repositories
that do not contain enough code or have high enough throughput for the
standard process to be appropriate.
> Add details on "simple" OWNERs process used for small repositories.

- governance.md
I had previously been lazy and not given everyone access to the boskos projects b/c it's not needed very often, but @vdemeester wanted access to help debug https://github.com/tektoncd/pipeline/issues/1500 so in https://github.com/tektoncd/plumbing/pull/105 I created a script to make it easy to give access to all of the 11 million boskos projects :D (and to expand the permissions if needed!)
Also added the service account permission which folks already had (to perform releases using a service account).
> Update boskos access docs

- org/org.yaml
This is for https://github.com/tektoncd/catalog/pull/116, and is serving to test
the peribolos configuration. My earlier test failed because github was down and never sent the event.
If this works, I'll send another PR to add the remaning buildpacks OWNERRS from that PR.
> Add ameyer-pivotal to the tektoncd org!

- org/org.yaml
This PR adds hone to the tektoncd org, so they can be an owner on the catalog/buildpacks task.
> Add remaining buildpack owners to the tekton org.

- README.md
User profiles are very useful when trying to talk about designs and who needs what - especially since folks may wear so many different hats when interacting with Tekton! But you'd need to know this was here already to discover it so adding a link from our main README.
> Add user profiles link to front page 🎩

- process.md
This adds some best-practices around holding meetings, as discussed
in the governance meeting.
This is https://github.com/tektoncd/community/pull/43 rebased - i have somehow blanked out how to push directly to the contributor's branch but this seems fine so :woman_shrugging:
> Add documentation on meeting best practices.

- working-groups.md
@vdemeester created the calendar event (so he can record it!) and we
found a time that works well for CEST, IST and CST. It's possible for
EST to attend but pretty early. Probably not reasonable for PST. Anyway
we want to start alternating our meeting time so that folks in Asia can
attend if they want to.
@vdemeester @afrittoli
> Add Asia friendly general working group meeting 🌏

- org/org.yaml
`ONWERS` files already merged. See https://github.com/tektoncd/catalog/pull/203#issuecomment-593258542
@loosebazooka
> Add Jib devs as ONWERS for Jib catalogs

- working-groups.md
Add details of dashboard working group meeting following existing
pattern, including links to Slack channel, meeting invite, recordings,
etc.
@bobcatfish @a-roberts fyi
> Add dashboard working group details

- org/org.yaml
I changed is GitHub username due to privacy reasons (it used to be my LDAP).
> Update Serge Pomorski's GitHub username.

- README.md
- org/README.md
Previously we had no requirements beyond asking to join, but recently
the new governing board (https://github.com/tektoncd/community/pull/90)
discussed and tried to identify:
* What happens if you join (you can lgtm + you get ok-to-test)
* Why you would want this (probably only if you are regularly
contributing)
The lgtm is something we want to be careful
around since this could result in arbititrary code in our released
binaries.
Even with ok-to-test we want to exercise caution because this means
running arbitrary code on our infrastructure with test priviledges.
The requirements in this commit are meant to attempt to demonstrate that
this person has been shown to be a contributor who needs and can
responsibly use these abilities.
> Add requirements for joining the Tekton org 👪

- org/org.yaml
Adding chetan-rns, pratap007, PuneetPunamiya and sm43 as they are part of
the tekton/hub OWNERS, so they need to be part of the org (and they
are in the Red Hat team working on Tekton 😉).
> Add tektoncd/hub owners to the org 🤺

- README.md
- roadmap.md
I have put together a roadmap for 2020, which attempts to represent the
most requested of the features and issues that we've seen so far. I did
this by:
* [Reviewing the 2019 roadmap](https://docs.google.com/document/d/1zClmMJZU63kEDedjxTI99MCK-mXqm-Ym7PBfjMG5tQE/edit)
* Looking at the oldest and most commented on issues in Tekton Pipelines
and Tekton Triggers
I also added a section on Tekton's mission: this is the mission that
we've been using at Google when talking about Tekton - so this is a
great chance for anyone who is viewing Tekton differently to mention
their mission and vision so we can tweak it. Having more clarity around
what everyone is hoping accomplish with Tekton will make it easier to
make decisions around features, etc.
PTAL:
* The governing board @abayer @vdemeester …
> Create 2020 roadmap 🛣️

- working-groups.md
Now that we've had the beta launch of Tekton Pipelines, we've decided to
stop having that working group meeting, but we've also decided to have
one that focuses on the API to take its place. This was originally
proposed as the "workflow" working group, to focus on things like
conditions and failure handling, but we found we wanted to discuss
things like debug mode as well and so made it a bit more broad.
The survey results for the time were a tie between the same block that
the beta meeting had occupied and an hour earlier on tuesday, decided to
go with the same time as the beta meeting b/c it was simpler and also
b/c when I asked a couple ppl they expressed a preference.
Facilitators volunteered in our first meeting - thanks
@vdemeester, @afrittoli, @skaegi, @dibyom, @chhsia0, …
> Beta working group has morphed into the API working group 🦸‍♀️

- working-groups.md
While adding the API working group to the working group list
(https://github.com/tektoncd/community/pull/93) I realized that our
faciltiator lists for some working groups were out of date.
* General WG: Thanks @dibyom @chhsia0 !
* Docs: Thanks @annqm @popcor255 !
I'm no longer facilitating triggers
Since we split the regular WG into 2, @vdemeester and @afrittoli have
been facilitating only the europe friendly timezone - but it feels weird
to remove vdmeester from the list!!!
> Update facilitator lists 📝

- org/org.yaml
(written by @bobcatfish ): @jerop has joined the Tekton team at Google and will be regularly contributing to Tekton Pipelines and later probably other Tekton project as well! 🎉
> Add jerop to the org

- README.md
- process.md
We are switching Tekton over from using the Google CLA to using the CDF
CLA. This commit adds some docs about how it works. It is a bit
aspirational since at the moment I think I might be the only governing
board member who has access to admin the CLA however I have put in a
request to get everyone access.
I also thought CONTRIBUTING.md might be a better place for this info
however the CONTRIBUTING.md in this repo is only for this repo so I then
thought process.md might be a better place for org wide info. I also
wasn't sure if plumbing was a better place but this seems in between
since external contributors might want this info also.
As of right now I've turned this on for plumbing, community and friends.
Next steps:
1. Check with @vdemeester and @afrittoli and see if they run into any …
> Add info about EasyCLA 👩‍⚖️

- process.md
Previously users listed in the OWNERS files as approvers automatically
got a `/approve` on their PRs. With https://github.com/tektoncd/plumbing/pull/72
this is no longer the case. Update the docs to reflect this.
> Update docs on review process to reflect current behaviour

- org/org.yaml
Jonas has recently become a regular contributor. He started with adding a minor [_missing_ `omitempty`](https://github.com/tektoncd/pipeline/pull/2301) and then [proposed some ideas](https://github.com/tektoncd/pipeline/issues/1986#issuecomment-605605058) around workspaces and PersistentVolumeClaim creation and continued to [elaborate around those ideas](https://github.com/tektoncd/pipeline/issues/1986#issuecomment-607436779). A sunny day a few days later, he also submitted an [implementation for volumeClaimTemplate](https://github.com/tektoncd/pipeline/pull/2326), corresponding to the discussed ideas.
A few days later submitted a [small refactoring PR](https://github.com/tektoncd/pipeline/pull/2392), and he also listened to community members that [proposed …
> Add Jonas to the org

- OWNERS
Given the new TEP process, the members of the Tekton governance
board should be owners of on the community repo, adding Jason
and Andrea who are both missing.
> Add the Jason and Andrea as OWNERS to community

- org/org.yaml
Florian would like to add a new `helm` task to the Tekton Catalog. He would like to maintain and own this task.
https://github.com/tektoncd/catalog/pull/334
Florian works in his daily job as a solution architect for IBM Germany, where he likes to rely on open source technologies. If he finds a bug in one of his used software, he does not hesitate to fix it or add new features. He has already spoken with the `helm` maintainers and is looking for active support to maintain this new Tekton Task.
Florian is excited about the cool features around Tekton and is looking forward to using them more and more in customer projects.
Signed-off-by: Florian Hopfensperger <florian.hopfensperger@de.ibm.com>
> Add Florian to the org, to own the `helm` task.

- hack/.notableofcontents
- hack/update-toc.sh
- teps/0001-tekton-enhancement-proposal-process.md
- teps/NNNN-tep-template/README.md
- teps/README.md
This is the proposal to define a well defined, more "accessible"
proposal workflow for Tekton cross-project enhancement (and new
projects).
In a gist, this is **heavily** inspired/taken from the [`KEP`](https://github.com/kubernetes/enhancements/blob/master/keps/0001-kubernetes-enhancement-proposal-process.md) from Kubernetes. You can also think of [`PEP`](https://www.python.org/dev/peps/), [Rust `RFC`s](https://github.com/rust-lang/rfcs), …
This proposal aims to make enhancement proposal easier to track and more acessible.
> - provide a common structure for proposing changes to Tekton
> - ensure that the motivation for a change is clear
> - allow for the enumeration stability milestones and stability
>   graduation criteria
> - persist project information in a Version Control System …
> Tekton Enhancement Proposals proposal 🤴

- org/org.yaml
Maneesh would like to add a new "buildid" task to the Tekton Catalog. He would like to maintain and own this task.
tektoncd/catalog#369
Maneesh works in his daily job as an Engineering Manager for Red Hat, where he likes to rely on open source technologies. If he finds a bug in one of his used software, he does not hesitate to fix it or add new features. He is looking for active support to maintain this new Tekton Task.
Maneesh is excited about the cool features around Tekton and is looking forward to using them more and more in customer projects.
Signed-off-by: Maneesh Mehra maneeshmehra@yahoo.com (and mmehra@redhat.com)
> Add maneeshmehra as an org member, to own "buildid" task

- teps/NNNN-tep-template/README.md
Add two new optional sections to the TEP template, about UX and
performance. The sections are optional as they may not be relevant
for all type of changes; however they will help who proposes the
change to think about these aspects at early stages of design.
/cc @bobcatfish 
/cc @vdemeester
> Add UX and performance as optional sections in TEPs

- org/org.yaml
Hi, Vinamra is actively contributing to `tektoncd/catalog` and has also started contributing to `tektoncd/cli` and `tektoncd/pipeline`. Vinamra is an intern at Red Hat. Vinamra is excited about the cool features around Tekton and is looking forward to contribute more in projects.
> Add vinamra28 as an org member

- org/org.yaml
Hi, Divyanshu is actively contributing to `tektoncd/catalog` and added few tasks to catalog and has also started contributing to `tektoncd/cli` and `tektoncd/pipeline`. Divyanshu is an intern at Red Hat. Divyanshu is looking forward to contribute more in projects and add more features.
Signed-off-by: Divyansh42 <diagrawa@redhat.com>
> Add divyansh42 to Tekton org

- org/org.yaml
Removing imjasonh and afritolli from the member list as they are
defined as admins. This also reorder the list alphabetically.
/cc @ImJasonH @afrittoli 
> Admins can't be members 😛

- teps/0002-custom-tasks.md
Based on the [Google Doc](https://docs.google.com/document/d/10nQSeIse7Ld4fLg4lhfgUmNKtewfaFNET3zlMdRnBuQ/edit), now with 1000% more Markdown! 😄 
[Rendered here](https://github.com/imjasonh/community/blob/custom-tasks/teps/0002-custom-tasks.md)
/assign @bobcatfish 
/assign @vdemeester 
/assign @afrittoli 
/cc @jlpettersson @mattmoor @n3wscott
> TEP 0002: Custom Tasks

- teps/0001-tekton-enhancement-proposal-process.md
Update the TEP workflow to make the PR that changes the status
of a proposed TEP the central place to track discussion on the
TEP.
This was discussed during an API WG.
> Update to the TEP workflow

- teps/0002-custom-tasks.md
As described in https://github.com/tektoncd/community/pull/142
The remaining open questions are relatively small and should not block initial implementation steps, as they can be discussed before implementing, or during review of implementation PRs.
/assign @afrittoli 
/assign @vdemeester
> Mark TEP 0002 as implementable

- org/org.yaml
This map the current teams from tektoncd so that the membership can be automated 😉. Overall the membership for this team should reflect the main `OWNERS` file approvers (and `OWNER_ALIASES` if used). I'll work on automating this in follow-ups :wink: 
Will need the following flags in [`peribolos.yaml`](https://github.com/tektoncd/plumbing/blob/master/tekton/resources/org-permissions/peribolos.yaml#L22)
```
-fix-team-members
Add/remove team members if set
-fix-team-repos
Add/remove team permissions on repos if set
-fix-teams
Create/delete/update teams if set
```
/cc @afrittoli @dlorenc @bobcatfish @ImJasonH @abayer
> org: maintain tektoncd teams using peribolos

- teps/0004-task-results-in-final-tasks.md
Proposal for enabling final tasks to get value from non-final tasks.
[Design Doc](https://docs.google.com/document/d/10iEJqVstY6k3KNvAXgffIJLcHRbPQ-GIAfQk5Dlrf3c/edit#heading=h.rghl981jtej4)
Issue [#2557](https://github.com/tektoncd/pipeline/issues/2557)
> Adding TEP for task results in final tasks

- teps/NNNN-tep-template/README.md
Adding optional references section to template which can hold links to any related docs/issues/etc. `References` goes in the end of the template i.e. it's the last section.
/cc @vdemeester @bobcatfish
> adding references section to TEP template

- teps/0005-tekton-oci-bundles.md
This proposal is to be able to bundle Tasks (and Pipelines, and Resources, and potentially other future config objects) into an [OCI Artifact](https://github.com/opencontainers/artifacts), pushed to an image registry, and referenced from that registry.
We need to agree on a name too (cc @wlynch for the *bundle* part that was discussed in a complete different context :stuck_out_tongue:)
This is a *early* version, based on
- [Tekton OCI Image Catalog](https://docs.google.com/document/d/1zUVrIbGZh2R9dawKQ9Hm1Cx3GevKIfOcRO3fFLdmBDc/edit#heading=h.tp9mko2koenr)
- [Tekton OCI Image Design](https://docs.google.com/document/d/1lXF_SvLwl6OqqGy8JbpSXRj4hWJ6CSImlxlIl4V9rnM/edit?pl=1#)
/cc @ImJasonH @pierretasci
> TEP-0005: Tekton OCI Bundle

- teps/0007-conditions-beta.md
Conditions is a CRD used to specify a criteria to determine whether or
not a Task executes. When other Tekton resources were migrated to beta,
it remained in alpha because it was missing features needed by users.
After analyzing the feature requests and discussing with users, we have
identified that the most critical gaps in Conditions are simplicity,
efficiency and skipping. We want to address these gaps so that it can
work well with the other Pipeline resources and users can count on its
stability.
> TEP-0007: Conditions Beta

- org/org.yaml
Max became recently a contributor to the Tekton project. He created some python tasks for the catalog and proposed some other ideas for improvement (tektoncd/catalog#413, tektoncd/catalog#459). He would like to maintain and own the created and derived tasks to support the project. Also the the test for several tasks are based on a repository of him.
_Introduced and improvements tasks_
tektoncd/catalog#432
tektoncd/catalog#470
_Derived tasks_
tektoncd/catalog#458
Max is working at IBM and uses various open source solutions in his daily job. This includes Tekton and he is excited how this project will develop in the future.
Signed-off-by: wumaxd <wurzer.maxi@gmx.de>
> Add Max to the org

- teps/0007-conditions-beta.md
Added [Conditions Beta TEP](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md) in https://github.com/tektoncd/community/pull/159
Let's discuss the TEP further and explore making it implementable per the TEP workflow
cc pipeline owners: @vdemeester @afrittoli @pritidesai @bobcatfish @sbwsg @ImJasonH @dibyom @dlorenc
> TEP-0007: Conditions Beta - further discussion and status update

- org/org.yaml
Related to https://github.com/tektoncd/triggers/commit/f39feca70117455dbd765cdb9a3c8fbcad134977
/cc @khrm @dibyom @afrittoli @bobcatfish @ImJasonH 
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> org: khrm maintainer of triggers

- teps/0003-tekton-catalog-organization.md
We've already started work on this in the catalog so we could even go
straight to "implemented" if we wanted to, but since we haven't
implemented all of it (e.g. testing for verifiable and official tiers
via #170) maybe "implementable" makes the most sense for now?
@vdemeester @sthaha
> Move catalog organization TEP to implementable

- teps/0009-trigger-crd.md
This proposal is to extract out Trigger definition from EventListener Spec into its own CRD 
to resolve the problem of Multitenant EventListener.
This is a TEP for the implementation of the Trigger CRD that were
discussed in the following docs: 
- [Trigger Listener CRDs](https://docs.google.com/document/d/1zWpmEhtSNe8KAPKvTJE7Pjg5Uzk8mx9MUjSN24D1jUg/edit#)
- [Multitenant EventListener](https://docs.google.com/document/d/1NX0ExhPad6ixTM8AdU0b6Vc3MVD5hQ_vIrOs9dIXq-I/edit)
> TEP-0009: Trigger CRD 

- teps/0008-support-knative-service-for-triggers-eventlistener-pod.md
This proposal helps users of triggers to deploy eventlistener pod with a more flexible way
right now the proposal focused more on supporting `Knative` Service to deploy eventlistener pod but generally it can be any CRD(ex: `foo.bar.com`) which user can specify as part of eventlistener yaml
Following is the design doc for this TEP 
[Kntiave Service For EventListener Pod](https://docs.google.com/document/d/1GtCfpzgGFPt224A7xNE5sjN8REytytmNL8E9oXAk4Uc/edit#heading=h.40e30qobhlvt) 
Signed-off-by: Savita Ashture sashture@redhat.com
> TEP-0008: Support Knative Service for Triggers EventListener Pod

- org/org.yaml
This follows up https://github.com/tektoncd/plumbing/pull/544
/cc @bobcatfish @afrittoli @savitaashture @nikhil-thomas @wlynch 
> org: update plumbing maintainers team ⛺️

- teps/0006-tekton-metrics.md
This is a barebone TEP for adding new metrics as
suggested by the TEP template. At this point it
has only the problem statement and a testing plan.
I will iterate more to add the actual (sub-)metrics
and what they measure and where should they be
measured in the code in subsequent PRs.
tektoncd/pipeline#2814
> TEP-0006: New (sub-)metrics

- teps/0014-step-timeout.md
This PR introduces the `Step` timeout TEP.
An already open Pull Request related to this feature can be found [here](https://github.com/tektoncd/pipeline/pull/3087).
/cc @vdemeester @ImJasonH @sbwsg @bobcatfish
> TEP-0014 presents the Step timeout feature

- org/org.yaml
Ziheng became recently a contributor to the Tekton Dashboard project. He would like to maintain and own the created and derived tasks to support the project. Also the the test for several tasks are based on a repository of him.
Introduced and improvements tasks
https://github.com/tektoncd/dashboard/pull/643
Ziheng is working at IBM and uses various open source solutions in his daily job. This includes Tekton and he is excited how this project will develop in the future.
> Add Ziheng to the org

- teps/0010-optional-workspaces.md
The optional workspaces TEP was pretty thoroughly edited and reviewed
during the proposal phase (https://github.com/tektoncd/community/pull/169).
There were no outstanding blockers or requests for more information that
I'm aware of that should prevent this TEP moving to implementable.
This PR moves the optional workspaces TEP into implementable state with
intention to go ahead and add this feature to Tekton Pipelines.
> Move optional workspaces TEP to implementable

- teps/0007-conditions-beta.md
Initially, we'd considered giving WhenExpressions names. After further
discussion, we decided it's unnecessary because we don't use them across
Tasks and what the WhenExpression is evaluating should be straightforward
from the input, operator and values. So removing the WhenExpression names
mistakenly left in the TEP so that it doesn't mislead users who read the TEP.
> Remove WhenExpressions names

- teps/0016-concise-trigger-bindings.md
This TEP proposes a simpler, more concise syntax for TriggerBindings embedded inside a Trigger or a EventListeners spec.triggers field in order to make it easier and less verbose to write simple Triggers.
Originally proposed in tektoncd/triggers#617
Given that this is a fairly simple change and that there wasn't any strong objections when I brought this up in the WG, I'd like to see if I can get this merged in the `implementable` state :)
/kind tep
/assign @khrm 
/assign @wlynch
> TEP-0016: Concise Embedded TriggerBindings

- teps/0005-tekton-oci-bundles.md
This moves the Tekton Bundle TEP into implementation (PR here https://github.com/tektoncd/pipeline/pull/3142).
It also updates the spec to match the current proposal.
> TEP-0005: Make Tekton Bundles implementable

- design-principles.md
The goal of these principles is to provide a basis for design choices and help in making tradeoffs. The design principles are reusability, simplicity, flexibility and conformance. 
The principles were initially proposed and discussed in [this google doc](https://docs.google.com/document/d/1_iqwslxAOx-SPYosnTFS5kOZcmxcBWpuIULZHQHP85Q/edit?usp=sharing) that's visible to members of tekton-dev@. Thank you for the contributions!
Related issue: [Add contributor and reviewer expectations](https://github.com/tektoncd/community/pull/133).
> Add Tekton Design Principles

- teps/0019-other-arch-support.md
This TEP proposes the way to add other hardware architectures support in Tekton.
It doesn't cover any specific architecture and can be used as reference for arch specific TEPs.
This TEP proposes main concept how Tekton tests and builds can be done for non-amd64 architecture
and provides samples of the Tekton tasks to run the build and e2e tests for Tekton pipeline.
It suggests to use native hardware for arch specific tasks and amd64 Tekton cluster (similar to dogfooding or itself) 
to play master role and manage all the steps.
> TEP-0019: Add other architecture support

- teps/0024-hermekton.md
This adds a TEP for hermetic builds in Tekton. It is in the 'proposed' state.
This was started as a draft in this Google document: https://docs.google.com/document/d/1TqFveX_UD1XtukeKv1I5RJHPOa155S5JGXlI9APbj4E/edit#heading=h.fzwmu8wbjk35
I wasn't quite sure what the right name for this file is. The current document seems to point at this: https://github.com/tektoncd/community/blob/master/teps/0001-tekton-enhancement-proposal-process.md#git-implementation
but other PRs aren't setup this way, and I see an outstanding PR to change the process still.
> Draft Hermekton TEP

- teps/0025-hermekton.md
There were two TEPs with the number 0024 - this one and embedded trigger
templates. Since that one already has a commit merged, I'm changing this to use
0025 instead.
/cc @dlorenc @bobcatfish
> Update hermekton TEP number to 0025

- README.md
- hacktoberfest-2020.md
This has a few Dashboard ideas I can make issues for if they don't exist, and some guidelines so if anyone does want to pitch in to Tekton and become a contributor, they have an idea of where to start.
I'll work on fleshing out the Dashboard ideas too, hopefully with @AlanGreene and @eddycharly!
Would love for more folks to pitch in with cool ideas for each project area next 😄 
This is for https://github.com/tektoncd/community/issues/188
Update: I agree with @eddycharly's proposal, decentralised this, provided guidance, and a link to the CDF's page for goodies
> Add Hacktoberfest 2020 guidance from cdf

- teps/0010-optional-workspaces.md
Optional workspaces is now available since pipelines 0.17.
This commit moves workspaces tep document to implemented status.
> Move optional workspaces to 'implemented' state

- org/org.yaml
Add members to the organization who contribute to the Tekton catalog for the incoming MacStadium Orka tasks.
> Add MacStadium contributors to Tekton org

- design-principles.md
- teps/NNNN-tep-template/README.md
Add a section in the TEP template where the authors can discuss how their proposals affects the reusability, simplicity, flexibility and conformance of Tekton, as described in the recently-added design principles
https://github.com/tektoncd/community/blob/master/design-principles.md
/cc @vdemeester @bobcatfish @afrittoli @ImJasonH
> Add design evaluation based on design principles to TEP template

- teps/0011-redirecting-step-output-streams.md
TEP for [pipeline#2925](https://github.com/tektoncd/pipeline/issues/2925) and  [pipeline#3103](https://github.com/tektoncd/pipeline/pull/3103).
Consuming outputs of a step in another step is a common pattern in writing Tasks. However, this is currently tedious to do. Task authors have to overwrite the image entrypoint with either `sh -c` or the `script` field to wrap up the command to run with an explicit output stream redirection. This is not even possible if the image does not come with a shell, e.g., images built by [`ko`](https://github.com/google/ko).
To achieve the functionality of output stream redirection between steps and even Tasks, this TEP proposes to add new fields to steps for Task authors to specify paths to store stdout/stderr to.
> TEP-0011: Redirecting Step Output Streams

- teps/0007-conditions-beta.md
Previously, we'd proposed to adding `continueAfterSkip` field which
defaults to false and can be set to true to execute ordering-dependent
tasks
We want to update that proposal because:
- using string aliases instead of booleans is preferable because,
as described in the [Kubernetes API policy](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md), "_Think twice about bool
fields. Many ideas start as boolean but eventually trend towards a
small set of mutually exclusive options. Plan for future expansions by
describing the policy options explicitly as a string type alias._"
- that naming was misleading
So, we propose using a `whenSkipped` field which defaults to `skipBranch`
and users can set to `runBranch` to execute its branch that's …
> TEP-0007: Conditions Beta Skipping

- teps/0028-task-execution-status-at-runtime.md
This TEP has a proposal on how to access task execution status at runtime within the pipeline.
Issue: https://github.com/tektoncd/pipeline/issues/1020
PoC: https://github.com/tektoncd/pipeline/pull/3390
> Adding TEP for accessing task execution status at runtime

- README.md
Adding a link to the [design principles](https://github.com/tektoncd/community/blob/master/design-principles.md) introduced in https://github.com/tektoncd/community/pull/171 to increase visibility to contributors
Fixes https://github.com/tektoncd/community/pull/171#issuecomment-721197989
/kind misc
/cc @bobcatfish
> Add design principles to the main README

- standards.md
These started out as just being for Tekton Pipelines, discussed in the productivity
working group, but @dibyom pointed out they make sense for triggers too,
so let's see if we want to adopt these for all the tektoncd projects or if we just want to
constrain it to triggers + pipelines.
The goal of these guidelines is to make sure that contributors
understand what is expected in their submissions and also so that a
reviewer (especially if someone wants to join and start reviewing who
hasn't reviewed as part of this project before) will know when they
approve + lgtm what they are expected to have checked.
Would like to hear feedback from OWNERS (approvers and reviewers) across all Tektoncd projects, both:
1. Any tweaks or additions or things you strongly disagree with
2. Whether you'd rather …
> Add contributor and reviewer expectations

- .gitignore
- org/README.md
- org/collaborator.py
- org/org.yaml
- org/requirements.txt
Create a collaborators team for every repo. Individuals in the
collaborators team have read access granted, same as the current
level of access that is provided org wide to all individuals that
belong to the org.
Every individual with read (or more) access to a repo is considered
a collaborator by GitHub; the list of collaborator is what the
/lgtm prow plugin uses to determin if an individual is allowed
to /lgtm a patch.
Ultimately, these team of collaborators aim to give more
granularity in how access to /lgtm is granted, from the whole
GitHub org to project specific, which is more in line with the
spirit of the lgtm plugin:
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/approve/approvers/README.md#lgtm-label
The teams of collaborators have been created using a script …
> Create teams of collaborators

- teps/0022-trigger-immutable-input.md
This TEP proposes a change to Trigger interceptor handling to ensure
that incoming input events are not mutated through the triggering
process.
TEP Design for https://github.com/tektoncd/triggers/issues/778
> TEP-0022: Triggers - Immutable Input Events

- org/org.yaml
lucperkins is in the OWNERS file for tektoncd/website, however
they're not part of the tektoncd org, which breaks periobolos,
so removing them from the website.maintainers group.
> Remove lucperkins from website maintainers

- teps/0003-tekton-catalog-organization.md
- This patch adds three conditions of when catalog resources version
should be bumped based on the changes in the image used
> Adds conditions on bumping the resource version based on bumped image

- teps/XXXX-step-workspaces.md
Prior to this TEP access to Workspaces has been defined through Tasks, TaskRuns, Pipelines and PipelineRuns. There are known limitations with this:
- Sensitive data is exposed to every single Step in a Task instead of only those Steps that actually make use of the data.  This is a similar problem to one we face with our credentials system. Ideally, access to sensitive data should be isolated to only the code that uses it.
- Sidecars do not have a "blessed" path to accessing a Workspace. Instead they must rely on a hack by adding the `$(workspaces.<name>.volume)` variable to the `name` field of a `volumeMount`.
The TEP in this commit proposes adding a `workspaces` field to `Steps` and `Sidecars`. The meaning of this field would be to provide access to that Workspace in either the Step or …
> TEP: Step and Sidecar Workspaces

- org/collaborator.py
- org/org.yaml
Removed duplicate roles. Team maintainers are not really needed
because we maintain the config via peribolos, however it's good
to have them setup for backup.
Using the governance team as default maintainer team, and take
care that no individual is both maintainer and member of any
collaborator team.
> Fix collaborators groups

- teps/0026-interceptor-plugins.md
This is a Triggers proposal to make interceptors more pluggable and
extensible by making the API uniform across built-in and webhook interceptors
(i.e. using HTTP), and by updating the API to support some missing use cases.
This should allow operators to select which interceptors they'd like to
support as part of their installation. In addition, this allows for better
auditability (see TEP-0022), the ability to distinguish between unexpected
errors and filtered events (i.e. processing is successful but we don't need
to continue; see [#336](https://github.com/tektoncd/triggers/issues/336)),
and leaves the room open to easily extend the interceptor interface in the
future.
Triggers issues:
* https://github.com/tektoncd/triggers/issues/271
* https://github.com/tektoncd/triggers/issues/336 …
> TEP-0026- Add TEP for interceptor plugins

- teps/0015-pending-pipeline.md
This TEP proposes a method for pausing PipelineRuns and TaskRuns that are then
ignored by the Tekton reconciler. These paused resources can be used by platform
implementers to control PipelineRun and TaskRun resources, for example, in cases
where the cluster is under heavy load and not ready to process a PipelineRun.
PipelineRuns and TaskRuns can be created paused so that they are not started at
all or, in the case of a PipelineRun, the pause setting can be used to prevent
further TaskRuns from being created. As it is not possible to "pause" a
Kubernetes pod, the pause setting would not affect TaskRuns after they are
started.
> TEP-0015 - Add a pending setting to Tekton PipelineRun and TaskRuns 

- org/org.yaml
With this change, everyone in the Tekton org will stay part of the
org, but they won't be considered collaborators on a project unless
they're part of the project collaborator team.
The effectively restricts 'lgtm' to project collaborators only,
instead of being granted to everyone in the org for all repos like
it is today.
/kind misc
/hold
> Set default project permission to "none"

- teps/0021-results-api.md
This TEP proposes a Results API to store long term Tekton results independent of
on-cluster runtime data stored in etcd.
/cc @ImJasonH @afrittoli
> TEP-0021: Results API

- teps/README.md.mustache
- teps/tools/Dockerfile
- teps/tools/README.md
- teps/tools/requirements.txt
- teps/tools/tep-template.md.template
- teps/tools/teps.py
Add a renumber command that gets a new TEP number and updates a TEP
and the tep table accordingly. This can be handly in case of the
TEP number has been taken by another TEP.
> Add a renumber command to the teps tool

- teps/0021-results-api.md
- teps/README.md
- teps/README.md.mustache
- teps/tools/Dockerfile
- teps/tools/teps.py
The update docker file runs `--help` by default and can take
the teps command as a container command and teps args as
container args.
Fix validation issues and update the TEP table.
> Fix the docker file and teps_folder for CI runs

- teps/tools/tep-template.md.template
We currently have a User Stories section that give space for implementation TEPs
to describe how a specific usage will change once the implementation is complete.
For people writing a problem statement User Stories don't fit the bill since they describe
implementation specifics. This commit introduces a Use Cases sub-section to Motivation that
gives space for a TEP author to describe broad groups of users and the kinds of enhacement
they should expect from an implementation, without getting into specifics of how an
implementation could operate.
> Add a Use Cases sub-section to Motivations in the TEP template

- teps/tools/tep-template.md.template
In 4fe594 we added a "Use Cases" paragraph to the Motivation section.
of the TEP  template.
This commit removes the "User Stories" list from the Proposal section
since it's likely to end up with very similar content to "Use Cases".
> Remove the User Stories section from the TEP template

- teps/tools/README.md
Add a file lines to the teps tool README to describe how to
install and run the teps.py tool.
> Add installation instruction to the teps tool README

- teps/README.md
https://github.com/tektoncd/community/pull/244 must have been merged
while the TEP tool was being created and the automation added?
Right now the TEP table is broken (according to the tool) b/c it's out
of sync and this is failing all PRs to community
> Fix TEP table

- teps/tools/teps.py
If we don't add a title the new command would crash :
```
% ./teps/tools/teps.py new
[...]
Traceback (most recent call last):
File "..../teps/tools/teps.py", line 305, in new
title_slug = "".join(x for x in title if x.isalnum() or x == ' ')
```
> Make title argument as required

- teps/0003-tekton-catalog-organization.md
In TEP-0003 we need to add an annotation instead of
a label while deprecating a resource. So fixing the
documentation under Deprecation & Removal Strategy.
> Label -> Annotation in Deprecation Strategy in TEP-0003

- org/org.yaml
Creates initial maintainer/collaborator team for new results project.
Primarily based on the existing OWNERS config
(https://github.com/tektoncd/results/blob/b113f90d53db800a9f6cb402fe6abc230f4ae55c/OWNERS).
For group maintainers, chose admins + wlynch.
Fixes #288
> [results] Create initial peribolos config.

- org/org.yaml
Fixing groups for results maintainers and collaborators.
The maintainers section of each group is not so relevant
as we maintain the groups via peribolos anyways.
/cc @vdemeester @wlynch
> Individuals cannot be both team maintainers and members

- org/org.yaml
Jerop was added as Pipelines Owner in https://github.com/tektoncd/pipeline/pull/3620 so needs to be added to core.maintainers in org.yaml
/cc @bobcatfish
> Sync Pipeline OWNERS with org.yaml

- teps/0035-document-tekton-position-around-policy-authentication-authorization.md
- teps/README.md
See https://github.com/tektoncd/pipeline/issues/2917 and https://github.com/tektoncd/pipeline/pull/2797
> TEP-0035: add tep for further documenting how-to's around policy, authentication, authorization, RBAC, and Tekton

- README.md
- roadmap.md
- user-profiles.md
In the context of some discussions with @vdemeester, I've been working
on a doc and I wanted to be able to refer to something that
distinguishes between "runtime" and "authoring time". @jerop started
working on a doc for that and I thought it would be useful to be able to
refer to the 2 (potentially) different sets of users (users at authoring
time and users at runtime) - we already had this profiles doc and it
pretty much expressed that but I thought I'd try to make it a bit more
clear.
I also changed around the 'operator' bit - I'm not sure those personas
mentioned as being out of scope were actually fully out of scope since
we do need to support folks who are operating Tekton.
Added some links to this doc from other docs as well.
> Spruce up user profiles 🌲

- org/org.yaml
I'd like to contribute tasks to the catalog, for example the EKS cluster create/delete tektoncd/catalog#606.
> Add theofpa to the org

- working-groups.md
I've stepped back from faciltiating the hub and catalog working group,
and @piyush-garg has been facilitating, so removing myself from the list and
adding him instead.
> Remove myself, add Piyush 📝

- teps/0036-start-measuring-tekton-pipelines-performance.md
- teps/README.md
This PR starts a TEP to begin to measure tekton pipelines performance
and address https://github.com/tektoncd/pipeline/issues/540
This first iteration just tries to describe the problem vs suggesting
the solution.
It DOES recommend measuring SLOs and SLIs as a goal, which is kind of
part of the solution, so if we think it's useful we could step back even
further, but I think this is a reasonable path forward, curious what
other folks think!
> TEP-0036: Start measuring Pipelines performance

- design-principles.md
We want to distinguish between authoring time APIs vs run time APIs to
facilitate discussions of whether a feature should be in Tasks/Pipelines
or TaskRuns/PipelineRuns -- this will also help with the reusability of
Tasks and Pipelines
At **authoring time** (i.e. when authoring Pipelines and Tasks), authors
should be able to include anything that is required for every execution
of the Task or Pipeline.
At **run time** (i.e. when invoking a Pipeline or Task via  PipelineRun or
TaskRun), users should be able to control execution as needed by their
context without having to modify Tasks and Pipelines.
Related:
- https://github.com/tektoncd/community/pull/294
- https://github.com/tektoncd/pipeline/issues/3345#issuecomment-709375661
- …
> Design Principles: Authoring Time APIs vs Run Time APIs

- teps/0029-step-workspaces.md
- teps/README.md
In [f22828](https://github.com/tektoncd/community/commit/f228287acd11abead227564170a632ee9179e693) we introduced a new TEP describing two problems: first, Sidecars
don't have access to Workspaces. Second: Workspaces are globally available to all
Steps all of the time. For sensitive data this is less than ideal - preferably a
Task should be able to declare precisely which Steps or Sidecars are allowed to
access a given Workspace.
This commit adds a technical design to TEP-0029 that shows how we can add both
Workspace support to Sidecars as well as a mechanism for isolating Workspaces
to specific Steps/Sidecars in a Task.
> TEP-0029 Technical design for Step & Sidecar Workspaces

- org/org.yaml
I have been contributing to triggers and want to be more active in the org: https://github.com/tektoncd/triggers/pulls?q=is%3Apr+author%3AMarcelMue
I would like to more easily test / work more independent for my upcoming contributions to the project.
> Add marcelmue to the org

- org/org.yaml
Jerop and Priti are both owners of the new experimental project
CELRun; for that they need to be collaborators of the overall
experimental repo.
> Add Jerop and Priti as collaborators to experimental

- org/org.yaml
We don't have an official policy for adding collaborators yet but @MarcelMue meets the criteria that was used to seed the initial list (>5 PRs).
> Add @marcelmue as a collaborator for Triggers!

- teps/README.md
- teps/README.md.mustache
- teps/tools/teps.py
TIL about the := syntax which Python 3.8 introduced! The docs we have at
the moment say we require 3.6 (and I only have 3.7 installed personally
haha) so this commit removes the 3.8 syntax so that this script will
work with 3.6 (or at least 3.7 from my own attempts so far?).
I think in the long run we can simplify this by assuming folks will run
this via the image so they don't have to install it.
@afrittoli
> Remove Python 3.8 syntax

- org/org.yaml
@bigkevmcd was added to CEL owners in experimental repo, so should be in experimental.collaborators
https://github.com/tektoncd/experimental/pull/694
> Add @bigkevmcd to experimental.collaborators

- org/org.yaml
Ziheng is on my team at IBM and will be working with me on the Dashboard.
Add him to the collaborators team so he can be assigned for reviews etc.
He has already been added to the `reviewers` list in https://github.com/tektoncd/dashboard/blob/e3ea330a781ed764120cb993960431df03e6ef68/OWNERS#L16
@ziheng fyi, see discussion on Slack: https://tektoncd.slack.com/archives/CJ4ERJWAU/p1611239123001800
> Add Ziheng to dashboard.collaborators

- teps/0045-whenexpressions-in-finally-tasks.md
- teps/README.md
Users can guard execution of `Tasks` using `WhenExpressions`,
but that is not supported in `Finally Tasks`.
This TEP describes the need for supporting `WhenExpressions` in
`Finally Tasks` not only to provide efficient guarded execution
but also to improve the reusability of `Tasks`.
Given we've recently added support for `Results` and `Status` in
`Finally Tasks`, this is an opportune time to enable `WhenExpressions`
in `Finally Tasks`.
/kind tep
/cc @pritidesai @bobcatfish @sbwsg
> TEP-0045: When Expressions in Finally Tasks

- teps/0037-remove-gcs-fetcher.md
- teps/README.md
This TEP proposes deprecating and removing support for the `build-gcs` `PipelineResource` type, which would let us remove the `gcs-fetcher` image from the Tekton Pipelines release bundle.
[Rendered](https://github.com/imjasonh/community/blob/remove-gcs-fetcher/teps/0037-remove-gcs-fetcher.md)
> Add 0037: Remove gcs-fetcher image

- org/org.yaml
- Shubbam (@concaf) is part of the OpenShift Pipelines team and is
gonna work on several tekton projects, starting with the Operator.
- Rupali (@rupalibehera) is part of the OpenShift Pipelines team and
is gonna work on several tekton projects, starting with the cli.
I, @vdemeester, endorse them 😉 
> Add concaf and rupalibehera to the org

- teps/0045-whenexpressions-in-finally-tasks.md
- teps/README.md
We proposed supporting WhenExpressions in Finally Tasks in https://github.com/tektoncd/community/pull/317, and the TEP has a proposed status now
TEP: https://github.com/tektoncd/community/blob/master/teps/0045-whenexpressions-in-finally-tasks.md
In this PR, we want to change TEP status to implementable and update the examples provided for using `Execution Status`, `Results` and `Parameters`
/cc @sbwsg @pritidesai
> TEP-0045: WhenExpressions in Finally Tasks - Change Status to Implementable

- teps/0037-remove-gcs-fetcher.md
I've [notified tekton-users@](https://groups.google.com/g/tekton-users/c/1UZDlIZM_JI) and #general and #pipeline in the Slack, and I've [sent a PR to note the feature is deprecated](https://github.com/tektoncd/pipeline/pull/3728).
> Mark TEP 0037 implementing

- governance.md
- org/README.md
- standards.md
This updates any reference of plumbing repository to target the
/hold
> Update plumbing reference from master to main 🧙

- teps/0039-add-variable-retries-and-retrycount.md
- teps/README.md
This TEP proposes adding `retries` and current retry times to Pipeline variables in order to send notifications after a PipelineTask exhausted its retries.
Related issue: https://github.com/tektoncd/pipeline/issues/2725
> TEP-0039 Add Variable `retries` and `retry-count`

- standards.md
This updates any reference of website repository to target the
/hold
> Update website reference from master to main 🧙

- teps/0033-tekton-feature-gates.md
- teps/README.md
Co-authored-by: Vincent Demeester <vdemeest@redhat.com>
/kind tep
> TEP-0033 Tekton Feature Gates

- teps/0003-tekton-catalog-organization.md
- teps/README.md
This updates the TEP to in what case the version of the resource
should be updated in the catalog. If there is a field addition with default value
in existing resource and it is not going to change the behavior of resource
and not gonna break existing pipelines then version bump is not required.
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
cc @vdemeester @bobcatfish  @vinamra28  @piyush-garg
> Update Catalog Org TEP for Version Bump condition

- teps/0040-ignore-step-errors.md
- teps/README.md
Proposing a TEP to ignore step error and provide an option to continue after capturing the non zero exit code.
Related issues:
* https://github.com/tektoncd/pipeline/issues/2800
* https://github.com/tektoncd/pipeline/issues/1559
> TEP-0040 - ignore step error

- roadmap.md
This commit updates the Tekton wide roadmap from things we wanted to do
in 2020 to things we want to do in 2021!
[In this doc](https://docs.google.com/document/d/1gCuj1HgyjlngQXrmISfHk_nPlDsFWpi1yu_5PRcVfTY/edit?resourcekey=0-89-VsI_kkAQo6CvJ4X2rkg#) you can see the draft of this update as well as a look back at how we did at the 2020 roadmap.
> Update roadmap for 2021! 🛣️

- roadmap.md
This updates any reference of dashboard repository to target the
/hold
> Update dashboard reference from master to main 🧙

- teps/README.md
- teps/README.md.mustache
In [our Jan 25 API WG](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.2wljetplkxbp)
we discussed the idea of introducing a bit more process and review SLOs
around TEPs to make sure folks get feedback fast enough.
This commit updates our process docs with these changes: note tho that
the "review by next API meeting" requirement is something that we
haven't been following super closely so far so that would be a bit of a
change (but I think it would be worth it!) I think this means that you
just want to avoid assigning yourself if you don't think you'll have
time to review; and/or we'll want to reexamine our process if we think
we have too much to review and not enough reviewers to make that happen.
Also see …
> Add TEP review SLOs 👩‍⚖️

- OWNERS
I'm an owner on the pipelines repo and would like to help out with approvals
on TEPs related to pipelines.
I've contributed a bit to the community repo already with various TEPs and
process-related changes:
- Step & Sidecar Workspaces TEP: https://github.com/tektoncd/community/pull/225
- Optional Workspaces TEP: https://github.com/tektoncd/community/pull/169
- TEP Template updates: https://github.com/tektoncd/community/pull/268, https://github.com/tektoncd/community/pull/270, https://github.com/tektoncd/community/pull/238
> Add sbwsg as owner on community repo

- design-principles.md
- governance.md
- process.md
- standards.md
- teps/0001-tekton-enhancement-proposal-process.md
- teps/0020-s390x-support.md
- teps/0024-embedded-trigger-templates.md
- teps/0040-ignore-step-errors.md
- teps/0045-whenexpressions-in-finally-tasks.md
- teps/0051-ppc64le-architecture-support.md
- teps/README.md
- teps/README.md.mustache
This updates any self reference of community repository to target the
/cc @afrittoli @bobcatfish @ImJasonH @jerop
Re-created https://github.com/tektoncd/community/pull/331 (I messed up the branch 😅 )
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> Update self-reference from master to main 🧙

- org/org.yaml
Jordan (from IBM) has been consistently contributing to Tekton in the
past few months::
- https://github.com/search?q=org%3Atektoncd+is%3Apr+author%3Azhangtbj
- https://tekton.devstats.cd.foundation/d/48/users-statistics-by-repository-group?orgId=1&var-period=m&var-metric=contributions&var-repogroup_name=All&var-users=%22zhangtbj%22
I support him being added to the tektoncd org, and look forward to his
future contributions.
> Add Jordan (Tao Zhang) to the Tekton org

- org/org.yaml
@sbose78 is helping review PRs in pipeline repo and has committed a few changes to trigger repo.
* https://github.com/search?q=org%3Atektoncd+is%3Apr+author%3Asbose78
* https://github.com/tektoncd/pipeline/pull/3787
> adding sbose78 to the org

- teps/0005-tekton-oci-bundles.md
- teps/0021-results-api.md
This updates any reference of experimental repository to target the
/hold
> Update experimental reference from master to main 🧙

- org/org.yaml
The team can be mentioned in PRs where documents are modified
to help keep on top of doc reviews.
https://github.com/tektoncd/website/issues/252
> Create a team of doc reviewers

- roadmap.md
- teps/0002-custom-tasks.md
- teps/0008-support-knative-service-for-triggers-eventlistener-pod.md
- teps/0022-trigger-immutable-input.md
- teps/0026-interceptor-plugins.md
- teps/0035-document-tekton-position-around-policy-authentication-authorization.md
This updates any reference of triggers repository to target the
/hold
> Update triggers reference from master to main 🧙

- org/org.yaml
I am working on pipeline loops in tekton experimental (https://github.com/tektoncd/experimental/pull/724). This feature is using by [kubeflow/kfp-tekton](https://github.com/kubeflow/kfp-tekton) and also the IBM Datastage project currently.
I am the owner of kubeflow/kfp-tekton, and I would like to continue contributing to Tekton community further. 
I want to join tekton as member and maitain pipelineloop in tekton experimental. Please help approve. Thanks a lot!
/cc @vincent-pli
/cc @afrittoli
> Add fenglixa as member

- teps/0047-pipeline-task-display-name.md
- teps/README.md
adding a new TEP for Pipeline task display name.
> TEP-0047: Pipeline Task Display Name

- teps/0044-composing-tasks-with-tasks.md
- teps/0044-decouple-task-composition-from-scheduling.md
- teps/README.md
This TEP describes some difficulty folks have run into, especially when
trying to use Tekton Pipelines without PipelineResources: if you want to
use the functionality of multiple Tasks, you need to put them together
in a Pipeline and share data between them with volumes. It could be a
useful abstraction, and more efficient, to make it possible to combine
Tasks together without scheduling them on different pods.
Related issues:
* [Pipeline Resources Redesign](https://github.com/tektoncd/pipeline/issues/1673)
* [#1838 Extract Pre/Post Steps from PipelineResources 2 design into Tasks](https://github.com/tektoncd/pipeline/issues/1838)
* [Abstract task and nested tasks](https://github.com/tektoncd/pipeline/issues/1796)
* Oldies but goodies:
* [Link inputs and outputs without using …
> Add TEP-0044: Decouple Task Composition from Scheduling ➰

- teps/0042-taskrun-breakpoint-on-failure.md
- teps/README.md
If a TaskRun fails in Tekton, it can be hard to understand at what step and what exactly in the step led to the failure.
To solve this problem, it can be possible for the users to set a breakpoint on failure specification in the TaskRun which
halts it at a particular step, making it easy for the user to debug it. The following proposal covers the implementation
details regarding the same.
> Add TEP-0042 TaskRun breakpoint on failure

- roadmap.md
- standards.md
- teps/0001-tekton-enhancement-proposal-process.md
- teps/0007-conditions-beta.md
- teps/0021-results-api.md
- teps/0024-embedded-trigger-templates.md
- teps/0028-task-execution-status-at-runtime.md
- teps/0029-step-workspaces.md
- teps/0030-workspace-paths.md
- teps/0035-document-tekton-position-around-policy-authentication-authorization.md
- teps/0037-remove-gcs-fetcher.md
- teps/0045-whenexpressions-in-finally-tasks.md
- user-profiles.md
This updates any reference of pipeline repository to target the
/hold
/cc @bobcatfish @afrittoli @ImJasonH 
> Update pipeline reference from master to main 🧙

- org/org.yaml
I am part of the team at IBM that works with @AlanGreene on the Dashboard.
Adding to the collaborators team so I can be assigned for reviews etc.
PR open for adding to dashboard reviewers list in 
https://github.com/tektoncd/dashboard/pull/1990
> Add briangleeson to Dashboard collaborators

- teps/0033-tekton-feature-gates.md
- teps/README.md
This commit adds a proposal for feature gates which has us using two
feature flags (alpha and beta) for gating accesss to fields as we add
them to beta and v1 CRDs, as well as using feature specific flags for
changes in behavior. It also tries to enumerate all the other ways we
could approach this in case something else stands out as more appealing.
I've tried to encorporate feedback from @vdemeester and @afrittoli
(via hackmd) as well but let me know if I missed any and/or ammend this
commit with more info.
This commit also transitions the proposal from proposed -> implementable
so that (once we agree and merge) we can stop blocking features in
Tekton Pipelines which are waiting on this.
> TEP-0033: Add proposal & alternatives for feature gates ⛩️

- teps/0031-tekton-bundles-cli.md
- teps/README.md
The principal work for TEP 0031 has now been implemented (`tkn bundle list` and `tkn bundle push`) so mark the TEP as implemented.
The original proposal did call for additional changes that amend behavior of existing `tkn` commands but those were never strongly agreed upon anyways. During implementation it has become clear that `tkn bundle push` and `tkn bundle list` is a "complete" MVP experience and that we should start with just that. We can evolve from here instead of adding additional changes we aren't sure we need.
> Mark 0031 as implemented

- teps/0033-tekton-feature-gates.md
In https://github.com/tektoncd/community/pull/380 @pritidesai pointed
out a few typos and also was using a table to represent the
functionality disabled and enabled by settings for the flag - I thought
her table was really useful so I wanted to add it to the TEP.
> Add table demonstrating flags and fix typos 🛠️

- teps/OWNERS
@jerop and @pritidesai are owners in Pipelines project -- they need to be added in teps/OWNERS to approve Pipelines TEPs
> add jerop and pritidesai to teps/OWNERS

- teps/0038-generic-workspaces.md
- teps/README.md
This TEP outlines a problem facing the Workspaces feature in Tekton Pipelines: there are many different
ways that people and companies want to manage Workspaces but Tekton provides only a very narrow set of
supported storage options.
This was originally prposed in https://github.com/tektoncd/community/pull/290
but closed shortly after. Re-opening in response to @afrittoli 's
comment here: https://github.com/tektoncd/community/pull/290#issuecomment-795203985
> TEP-0038 "Generic Workspaces"

- teps/0049-aggregate-status-of-dag-tasks.md
- teps/README.md
[TEP-0028](https://github.com/tektoncd/community/blob/main/teps/0028-task-execution-status-at-runtime.md) implemented params such as `$(tasks.<pipelineTask>.status)` to access the execution status of a dag task from the finally section. This works great for a pipeline where a `finally` task depends on the execution status of an individual `dag` task. We have discovered additional use cases where a `finally` task needs to be executed if **ANY** one of the `dag` tasks fail. 
This TEP is proposing an additional variable `$(tasks.status)` to access aggregate status of the `dag` tasks. 
Related issues and PR:
https://github.com/tektoncd/pipeline/issues/3806
https://github.com/tektoncd/pipeline/issues/1020#issuecomment-747156100
https://github.com/tektoncd/pipeline/pull/3738#discussion_r56861898 …
> TEP-0049: access aggregate status of the dag tasks from finally

- working-groups.md
We have alternate times, so update the meeting details accordingly.
Normalise a bit the markdown tables for all meetings to keep them
more managable.
> Update the productivity working group meetings

- teps/0059-skip-guarded-task-only.md
- teps/README.md
This TEP addresses skipping strategies to give users the flexibility to
skip a single guarded `Task` only and unblock execution of its dependent
`Tasks`.
We explore this separately from the [Conditions Beta TEP](https://github.com/tektoncd/community/blob/main/teps/0007-conditions-beta.md) 
so that we can focus on this specific problem in further detail. 
In this PR, we discuss the motivation, goals, non-goals and requirements
only so that we can align on the problem before exploring the many 
alternatives later and choosing the way forward.
/cc @tektoncd/core-maintainers
> TEP-0059: Skip Guarded Task Only

- governance.md
@dibyom has joined the governing board after the most recent election,
@vdemeester and @bobcatfish have updated terms, and @ImJasonH was
removed (which was because he now works at RedHat which meant RedHat +
IBM had 3 seats which isn't allowed in our guidelines).
I've tried to add @dibyom to everything he needs to be added to and
wrote down how to do it - as well as removing @ImJasonH (which mostly
just removed his defunt google email XD)
Also added a former members section to give a shout out to folks who
used to be on the governing board!
PTAL @vdemeester @afrittoli @abayer @dibyom - and let me know if you can think of anything I missed (I also added a lot of folks to stuff and clean things up along the way)
> Update governing board and add instr for updates 🆕

- teps/0061-allow-custom-task-to-be-embedded-in-pipeline.md
- teps/README.md
See issue [tektoncd/pipeline#3682](https://github.com/tektoncd/pipeline/issues/3682), for initial discussion regarding this TEP.
/cc @Tomcli, @litong01
> TEP-0061 Allow custom task to be embedded in pipeline

- teps/0046-finallytask-execution-post-timeout.md
- teps/README.md
Proposal to enable finally tasks to execute when a pipelinerun has reached timeout.
Add a new flag `tasksTimeouts` which will define a timeout for the dag tasks. The finally tasks timeout will be `timeout - tasksTimeout` with `timeout >= tasksTimeout` and ```timeout```being the current timeout flag.
When `tasksTimeout` is not defined, `timeout` is used for the tasks timeout (the behavior is unchanged).
This will enable users to manage run time behavior and make sure their finally tasks run as intended by scoping the tasks runtime period.
/kind tep
cc @jerop @pritidesai
> TEP-0046: Finally tasks execution post pipelinerun timeout

- roadmap.md
- teps/0003-tekton-catalog-organization.md
- teps/0029-step-workspaces.md
- teps/0045-whenexpressions-in-finally-tasks.md
This updates any reference of catalog repository to target the
/hold
> Update catalog reference from master to main 🧙

- working-groups.md
We've added an additional API working group at a time that works for our
contributors in Australia; we've decided that since we have so much
content every week for the current API working group, instead of
alternating the times, we'll add an additional (but shorter) meeting
and see how it goes!
We're trying 6pm EST since this translated to 8am for the contributors
in Australia; any earlier is too early!
This commit also adds the folks as facilitators who indicated in the
survey that they were open to it. Thank you!!
> Add alternate API WG 📅

- OWNERS
- org/org.yaml
In https://github.com/tektoncd/community/pull/410 I am continuing to try
to make admin/ownership updates after our last election. @dibyom has
joined our governing board so should be added as an admin and owner;
former members should be removed.
Also removed @sbwsg from the top level OWNERS list b/c it looks like he
was added to that to help out with TEP review, and the OWNERS file in
teps/OWNERS should allow him to do this.
> Update admins and OWNERS post election 🗳️

- governance.md
1. During the 2021 governing board election, we noticed a few things that could use tweaking in our election guidelines. Also including some things to help next time: example timeline, email templates.
2. In https://github.com/tektoncd/community/pull/398 I missed a couple more items to give/revoke access to when the governing board members change: community drive, github org, and ownership of this repo
@afrittoli @abayer @dibyom @vdemeester 
Let me know if the email templates are overkill and I can remove them; they do repeat some of the election guidelines so it might be a bit annoying to maintain both.
> Moar updates to governing board docs post election 🗳️

- teps/0049-aggregate-status-of-dag-tasks.md
- teps/README.md
Updating the status to implementable. Also, adding an alternative to the name `$(pipeline.status)` instead of `$(tasks.status)`
> Updating the status of the TEP-0049

- org/org.yaml
and Piyush as collaboratior. This follows updates to the `OWNERs` file
in tektoncd/operator.
/cc @afrittoli
> Add Savita as operator maintainer 🧙

- org/org.yaml
Jason and Pierre were added to the org before using peribolos to
maintain the teams and members. For some reason they didn't appear on
the org member list. As they are either in maintainers or
collaborators team, they need to appear as the org member
too. Otherwise, peribolos validation fails and the org.yaml is never
synced with the github teams.
> Adding team members to the org member 😔

- org/org.yaml
… as he is an admin now, and thus can't be in both.
/cc @afrittoli 
> Remove dibyom from org members… 😅

- org/org.yaml
The username doesn't exists anymore.
/cc @afrittoli 
> Remove sergetron from the organization 🧣

- teps/0061-allow-custom-task-to-be-embedded-in-pipeline.md
- teps/README.md
Thank you, @Tomcli, @pritidesai, @sbwsg, @imjasonh, @bobcatfish, @afrittoli and @vdemeester for taking a look !
> TEP-0061 Allow custom task to be embedded in pipeline, design.

- teps/0062-catalog-tags-and-hub-categories-management.md
- teps/README.md
- Currently tags in catalog resources are mapped to categories in Hub. So
the issue was whenever new tags were added for the resource in the catalog,
these tags had to be mapped manually to a category before every release. Hence
the issue is solved by adding categories in a catalog task as annotation as
`tekton.dev/category: "foo"`
> TEP-0062 Catalog Tags and Hub Categories Management

- teps/0060-remote-resource-resolution.md
- teps/README.md
This commit adds a new TEP with a problem statement describing a gap
in Tekton's support for referencing Tasks and Pipelines. Namely, that
those resources have to be in the cluster or in an OCI registry to be utilized
by the pipelines controller.
> TEP-0060: Remote Resource Resolution

- teps/0041-tekton-component-versioning.md
- teps/README.md
Proposal to add versioning in Tekton components so that any system authenticated users who are having access to cluster may be able to view the version of Tekton component installed.
/kind tep
> TEP-0041: Add TEP for Tekton Component Versioning

- org/org.yaml
In a [previous PR](https://github.com/tektoncd/experimental/pull/748) I added myself for /approve powers on experimental
and would also like to be able to add lgtms.
This PR adds me to the org.yaml for experimental collaborators so
I can add lgtms on projects in that repo.
> Add sbwsg for lgtm to experimental collaborators

- contact.md
Julian Modesto sent an email to the tekton-users@ mailing list
requesting that this group get read access to the shared tekton drive
which seems reasonable so I've updated the permissions. This PR is
updating the docs to reflect that.
> Update that tekton-users can now have read access to the drive

- teps/0045-whenexpressions-in-finally-tasks.md
- teps/README.md
It was implemented in https://github.com/tektoncd/pipeline/pull/3738
/kind cleanup
> TEP-0045: WhenExpressions in Finally Tasks - Mark as Implemented

- teps/0020-s390x-support.md
- teps/README.md
The Tekton releases and tests for `linux/s390x` are running already.
See the s390x nightly tests at [dogfooding cluster](https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-z/pipelineruns)
/kind tep
> TEP-0020: s390x architecture support - Mark as Implemented

- teps/0002-custom-tasks.md
- teps/0015-pending-pipeline.md
- teps/0061-allow-custom-task-to-be-embedded-in-pipeline.md
- teps/README.md
- teps/tools/tep-template.md.template
Proposing a new section i.e. `Implementation pull request(s)` to TEP template and updated the same for some of the TEPs.
This section is intended to be filled when the TEP is ready to be marked as implemented or even as a TEP make progress towards being marked implemented.
This was discussed in API WG meeting on June, 7th of 2021 10AM PT.
/cc @afrittoli, @vdemeester
> TEP template update: New section, Implementation pull request(s)

- teps/0007-conditions-beta.md
- teps/README.md
This change updates [TEP-0007: Conditions Beta](https://github.com/tektoncd/community/blob/main/teps/0007-conditions-beta.md):
- TEP status is implemented - was implemented in https://github.com/tektoncd/pipeline/pull/3135
- _skipping_ is addressed in [TEP-0059: Skipping Strategies](https://github.com/tektoncd/community/blob/main/teps/0059-skipping-strategies.md)
> TEP-0007: Conditions Beta - Mark as Implemented

- org/org.yaml
waveywaves is OWNER of the cloudevents project in experimental.
Add him to the collaborators team so he may lgtm on that project too.
> Add waveywaves as experimental collaborator

- teps/0002-custom-tasks.md
Tekton-owned controller will not forcibly update the `.status` of a Run directly. This will be the responsibility of Custom Task controller. For a PipelineRun with either a pipeline level timeout configured and/or the custom task level timeout configuration, timeout is updated to the run with same policy as it is for task runs. On timeout, the running run's status is updated with "RunCancelled". 
More details on the issue https://github.com/tektoncd/pipeline/issues/3962
> Update the TEP-2 to newly proposed timeout implementation.

- org/org.yaml
Update the dashboard.maintainers team to add briangleeson, he has
already been added as an approver in the OWNERS file in tektoncd/dashboard.
See https://github.com/tektoncd/dashboard/pull/2099
Remove other members from the maintainers team who are no longer involved
with the project, this reflects the current list in the OWNERS file.
> Add briangleeson to the dashboard.maintainers team

- org/org.yaml
Following it's addition to reviewers on the operator repository,
adding him here.
See https://github.com/tektoncd/operator/pull/348
> Add sm43 as collaborator on operator

- teps/0071-custom-task-sdk.md
- teps/README.md
A Custom Task SDK will make the work of custom task author easier and will offer standard way to implement custom task controllers. While adhering to current separation of concern between a custom task controller's role and tektoncd owned controller's role, it should make custom tasks easier to manage and reason by tektoncd.
/kind tep
Please vote: https://github.com/tektoncd/community/issues/459
> TEP-0071: Custom Task SDK.

- teps/0023-implicit-mapping.md
- teps/README.md
In this TEP, we propose introducing implicit parameter mapping to allow authors to reference params in embedded specs that are not explicitly defined. Instead, users will rely on Tekton to automatically resolve these values at admission time.
This is a modification of https://github.com/tektoncd/community/pull/222.
> TEP-0023 Implicit Params

- teps/0040-ignore-step-errors.md
- teps/README.md
Introduce a new field `onError` while defining a step to indicate to ignore the error:
```yaml
onError:  [ continue | fail ]
```
For example,
```yaml
steps:
- image: docker.io/library/golang:latest
name: ignore-unit-test-failure
onError: continue
script: |
go test .
```
The original failed exit code will be part of the run status:
```json
"steps": [
{
"container": "step-ignore-unit-test-failure",
"imageID": "...",
"name": "ignore-unit-test-failure",
"terminated": {
"containerID": "...",
"exitCode": 1,
"finishedAt": "2021-06-21T18:22:05Z",
"reason": "Completed",
"startedAt": "2021-06-21T18:22:05Z"
}
},
],
```
And will be available at `/tekton/steps/0/exitCode`.
Design iterations:
Iteration 1:
```yaml
exit:
continue:  [ afterSuccess | always ]
```
For example,
```yaml
steps:
- image: …
```
> proposal for TEP 0040 - ignore step error with a new section `exit`

- org/org.yaml
I noticed I had been added as a reviewer to a CLI PR, and it was b/c I'm
in CLI maintainers. However I don't work on the CLI so I don't think I'm
in a good position to be reviewing PRs there, and so I'm removing myself
from the list. That leaves only @vdemeester as a CLI maintainer tho so I
can stay on the list if we wanted to make sure there was more than 1
person, just let me know.
> Update CLI maintainers 👻

- working-groups.md
This doc was still linking to the 2020 notes.
> Fix link for triggers working group notes 🔗

- org/org.yaml
I missed that one in the previous commit 🤦
/cc @afrittoli @nikhil-thomas 
> org: remove duplicated names from cli.maintainers

- teps/0069-support-retries-for-custom-task-in-a-pipeline.md
- teps/README.md
I need feedback on the proposal, if it looks good then I can work on demo and other design aspects.
A pipeline task can be configured with a `retries` count, this is 
currently only supported for `TaskRun`s and not `Run`s (i.e. custom tasks).
This TEP is about, a pipeline task can be configured with a `retries` count
for Custom tasks.
Also, a `PipelineRun` already manages a retry for regular task
by updating it's status. However, for custom task, a tekton owned controller
can signal a custom task controller, to retry. A custom task controller may
optionally support it.
> TEP-0069: Support retries for custom task in a pipeline.

- teps/0048-task-results-without-results.md
- teps/README.md
Listing use cases and problem statement for task results without results based on the latest API changes.
> TEP-0048: task results without results - problem statement

- teps/0059-skipping-strategies.md
- teps/README.md
This change is a clarification and update to the migration and upgrade
plan for skipping strategies.
The implementable proposal is to change the scope of `when` expressions
to guard the `Task`. This is a backwards-incompatible change. To make the
transition smooth, we plan to:
- provide a feature flag, `scope-when-expressions-to-task`, which:
- will default to `scope-when-expressions-to-task` : "false" to guard
a `Task` and its dependent `Tasks`
- can be set to `scope-when-expressions-to-task` : "true" to guard a
`Task` only
- after 9 months, per the [Tekton API compatibility policy](https://github.com/tektoncd/pipeline/blob/main/api_compatibility_policy.md#alpha-beta-and-ga),
we'll flip the feature flag and default to `
scope-when-expressions-to-task` : "true" [February 2022]
- in the …
> TEP-0059: Skipping Strategies - Migration Plan

- teps/0040-ignore-step-errors.md
This commit proposes changing the wording of the `fail` option for
`onError` from `fail` to make it more explicitly clear that this option
(which is the default behavior when `onError` is not specified) will
both cause the Task to fail AND stop execution of any subsequent steps.
This change doesn't propose changing any of the described functionality,
just the value of the field.
PTAL @pritidesai @vdemeester  ( @afrittoli I think you're on holiday right now, given this is such a minor change I'm assuming you will be okay with it but strong apologies if not!! 🙏  )
> Use `stopAndFail` instead of `fail` with `onError` 🧐

- teps/0040-ignore-step-errors.md
- teps/README.md
We just merged the implementation PR so adding a reference here.
Also, adding a note on what happens when a step is allowed to fail while it's suppose to produce a task result. Reference: https://github.com/tektoncd/community/pull/463#issuecomment-896496699
/kind tep
> changing TEP-0040 to implemented

- working-groups.md
In the slack #chains channel Naveen Srinivasan pointed out that the
calendar link didn't work - replacing the link with one that does work
(which I got by going to the tekton calendar event and clicking "publish
event")
> Fix link to chains calendar event 📅

- teps/0073-simplify-metrics.md
- teps/README.md
Carrying "Simplify Metrics" TEP (https://github.com/tektoncd/community/pull/286) as this is something that we should tackle.
I need to rephrase some stuff, but I am carrying this proposal as it is getting a higher priority for us to fix.
/kind tep
> TEP-0073 Simplify Metrics

- teps/0056-pipelines-in-pipelines.md
- teps/README.md
In https://github.com/tektoncd/pipeline/issues/4067, @mjgkaastrupandersen shares an additional use case for pipelines in pipelines. In the issue, they describe how they need a gateway task or grouping of pipelines to simplify specifying that a set of tasks all need to wait for another set of tasks to complete execution. In this change, we add that use case to [TEP-0056: Pipelines in Pipelines](https://github.com/tektoncd/community/blob/main/teps/0056-pipelines-in-pipelines.md).
Thank you for sharing your use case @mjgkaastrupandersen! 😀 
/kind tep
> TEP-0056: Pipelines in Pipelines - Add Use Case

- teps/0060-remote-resource-resolution.md
- teps/README.md
This commit updates the proposed remote resolution feature with a suggestion to
develop a controller in our experimental repo to try out some of the
Alternatives.
In order to support such an experimental controller two changes are also
proposed for Tekton Pipelines that would make such a controller much easier to
develop and test.
> TEP-0060: Propose remote resolution experimental controller

- teps/0069-support-retries-for-custom-task-in-a-pipeline.md
- teps/README.md
Added design and mark as implementable.
/kind tep
> TEP-0069: Support retries for custom task in a pipeline - design.

- working-groups.md
Updating the google meet link for chains WG based on the calendar invite.
> fixing the meet link for chains WG

- org/org.yaml
Adding pritidesai as Chains collaborator to get `lgtm` access on PRs.
> adding pritidesai as chains collaborator

- README.md
- hacktoberfest-2021.md
This is taken from the 2020 version and slightly adapated.
Project maintainers should label issues if they are interested
in partecipating.
> Adding an hacktoberfest 2021 page

- teps/0080-support-domainscoped-parameterresult-names.md
This update add example syntax illustrating the use of enclosing single and double quotes for parameter names. I've used bracket notation to describe the syntax in place of subscript as that is in common use. Also, added an additional risk statement for `-` characters.
> TEP-0080 Example syntax with enclosing single/double quotes

- working-groups.md
The pipeline, productivity and documentation WG now use Zoom as
virtual conference platform. Update the links.
Update the link to the Pipeline WG calendar entry too.
> Update VC Links for various WGs

- teps/0073-simplify-metrics.md
- teps/README.md
TEP 0073 describes simplifying the metrics that Tekton Pipelines records for TaskRuns.
A user over in the Tekton Pipelines repo requested a similar change, so this commit records that request.
> TEP-0073: Update TEP with a link to a related github issue

- teps/0094-configuring-resources-at-runtime.md
- teps/README.md
This TEP addresses tektoncd/pipeline#4080 and tektoncd/pipeline#4326 by
proposing new configuration to TaskRuns and PipelineTaskRuns that can
override any Step resource requirements specified in a Task or PipelineTask.
> TEP-0094: Specifying resource requirements at runtime [Problem Statement] 

- teps/0090-matrix.md
- teps/README.md
https://github.com/jerop/community/blob/looping/teps/0090-matrix.md
This change adds the problem statement for Matrix. It scopes the
problem, describes the use cases, and identifies the goals, the
requirements for the solution, and related work in other continuous
delivery systems.
Today, users cannot supply varying `Parameters` to execute a
`PipelineTask`, that is, fan out a `PipelineTasks`.
To solve this problem, this TEP aims to enable executing the same
`PipelineTask` with different combinations of `Parameters` specified
in a `matrix`. `TaskRuns` or `Runs` will be created with variables
substituted with each combination of the `Parameters` in the `matrix`.
This `matrix` construct will enable users to specify concise but
powerful `Pipelines`. Moreover, it would improve the …
> TEP-0090: Matrix [Problem Statement]

- teps/tools/tep-template.md.template
I noticed that the use cases section is optional but also I think many
(most? all?) of our TEP discussions end up coming down to "what are the
use cases" so I think it's a bit misleading to claim this section is
optional when it ends up being so important in our discussions, so this
commit changes it to be a required section
> Make "use cases" section required 📝

- teps/0074-deprecate-pipelineresources.md
- teps/README.md
The Google Tekton team was discussing plans for 2022 and we were trying
to figure out how important pipeline in a pod was - based on the initial
requirements here for PipelineResource deprecation, it felt like we'd be
able to go ahead (specifically with Pipelines v1!) without pipeline in a
pod. The existing requirements said we'd need experimental support to
prove it was possible - however when thinking through what that would
mean for v1, i.e.: pipelineresources are now gone, and you need to use
this experimental custom task if you want the same "in a pod"
functionality - that didn't seem fair to users.
So this change would update our requirements so that we'd have at least
alpha support for "pipeline in a pod" functionality before we'd mark
this TEP as implementable, i.e. before …
> Require TEP-0044 before removing PipelineResources 🙋‍♀️

- teps/0083-scheduled-and-polling-runs-in-tekton.md
- teps/README.md
This TEP introduces an idea for a feature in triggers which would allows user to 
- Schedule a pipelinerun/taskrun at a certain time/ at certain interval
- Setup a poll which looks for changes on a repository and triggers pipelinerun/taskrun.
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
> TEP-0083: Scheduled and Polling runs in Tekton

- org/org.yaml
Geri is part of the docs WG and he's focussing on improving our
documentation by:
- setting up a plan for the upcoming website/docs work
- restructuring, improving and consolidating the various getting
started guides and tutorials
- bringing the version of docsy up-to-date
Thanks Geri for your great work so for and for bringing new life
to our docs working group!
I propose we add Geri as a maintainer to the website (and to the tektoncd org).
> Add Geri to website maintainers :tada:

- design-principles.md
- teps/tools/tep-template.md.template
When reviewing a TEP recently I found myself wanting to reference the
k8s design principles (specifically around the convention to prefer
named subobjects to maps https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps)
and I was surprised to see this wasn't mentioned in our design
principles or our standards, though my understanding is that we have
been trying to comply with these conventions. (Not to mention I couldn't
remember what to google to find this doc so it's useful to have the link
somewhere we can easily reference XD.)
I'm not sure about making a whole new design principle section, but it
didn't seem like it fit very well into any of the existing sections
(maybe conformance?), and …
> Add k8s API conventions to design principles ✍️

- org/org.yaml
Based on https://github.com/tektoncd/operator/pull/559
/cc @afrittoli @bobcatfish 
> Sync operator teams organization

- teps/0096-pipelines-v1-api.md
- teps/README.md
This commit defines the problem statement for a stable release
of Tekton pipelines. It also describes the current Pipelines
deprecation policy and proposes a deprecation policy for a stable
release of Pipelines.
Co-authored-by: Jerop Kipruto jerop@google.com @jerop
> [Problem Statement] TEP-0096: Pipelines V1 Release

- teps/0014-step-timeout.md
- teps/README.md
This was actually done a while back in October 2020 when https://github.com/tektoncd/pipeline/pull/3087 merged.
> TEP-0014: Step Timeout - mark as implemented

- teps/0060-remote-resource-resolution.md
- teps/README.md
Remote resolution is currently in proposed state while work's been
going on to try and validate some of the alternative approaches being
put forward.
This commit moves TEP-0060 to implementable, updates the proposed
approach and adds notes about the experimental controller built to
validate ideas from the TEP.
There is an [accompanying PR](https://github.com/tektoncd/experimental/pull/806)
in experimental with a proof-of-concept controller implementing a
couple of the alternatives presented here.
> TEP-0060: Update proposal and mark Remote Resolution implementable

- teps/0046-finallytask-execution-post-timeout.md
- teps/README.md
https://github.com/tektoncd/pipeline/pull/3843 was merged back in June.
> TEP-0046: Mark as implemented

- working-groups.md
The governing board sync meeting has so far been not publicly advertised
(although the notes are available to the community via tekton-dev and
tekton-users). Recently we discussed potentially creating a "community
working group", however it felt like that most closely resembles what we
discuss in governing board meetings so instead of adding a new meeting,
with thought it might make sense to make this existing governing board
meeting public and see if other ppl are interested in joining and if
this can meet the need.
We'd also like to encourage more people to run for the governing board
(esp with the upcoming election in feb!) and joining this meeting could
give ppl an idea of what's involved.
@afrittoli @abayer @dibyom @vdemeester
> Add governing board / community meeting 👩‍⚖️

- teps/0033-tekton-feature-gates.md
- teps/README.md
https://github.com/tektoncd/pipeline/pull/3881 is the "main" PR for this
cc @afrittoli
> TEP-0033: Mark as implemented

- teps/0069-support-retries-for-custom-task-in-a-pipeline.md
- teps/README.md
cc @ScrapCodes to verify, but I'm assuming https://github.com/tektoncd/pipeline/pull/4327 being merged means this is done.
> TEP-0069: Mark as implemented

- org/org.yaml
I over-removed myself from even having lgtm in plumbing which doesn't make sense, oops!
Re-adding myself so I can collab on plumbing PRs, deliver reviews and provide lgtms.
> Add sbwsg as collaborator in plumbing

- org/org.yaml
As a new joiner in Google's Tekton team, my membership is endorsed by existing contributors.
@ywluogg @wlynch
> Add chuangw6 to org

- org/org.yaml
As a new joiner in Google's Tekton team, my membership is endorsed by existing contributors. @wlynch @chuangw6
> Add Yongxuanzhang to org

- teps/0079-tekton-catalog-support-tiers.md
This change adds the problem statement for Support Tiers in the Tekton
Catalog - we will explore the proposal in further changes.
The aim of this TEP is to establish support tiers for resources in the
Tekton Catalog to ensure users get high quality resources that they can
rely on while making it easy for contributors to submit resources to the
Tekton Catalog.
The goals of the TEP are to address the following aspects of the Tekton
Catalog:
- Ownership and Maintenance
- Automated Testing and Dogfooding
- Image Scanning for Common Vulnerabilities and Exposures (CVEs)
- Verified Remote Resources
Related PRs:
- https://github.com/tektoncd/community/pull/494
- https://github.com/tektoncd/community/pull/170
- https://github.com/tektoncd/community/pull/495
---
Note: this is a fix to a mistake I …
> TEP-0079: Tekton Catalog Support Tiers [Problem Statement]

- org/org.yaml
I removed myself a while ago as a maintainer from tekton pipelines but
am currently the release captain for Pipelines 0.32. Unfortunately being
a maintainer is required to edit a Release or push branches, both of
which are required during a release rotation.
This commit re-adds me as a maintainer on tekton pipelines with the
intention of removing myself again once the 0.32 release window is
passed. Sorry for the churn!
> Temporary add sbwsg as pipelines owner for 0.32

- teps/0094-configuring-resources-at-runtime.md
- teps/README.md
Add design details and alternative solutions for updating the `TaskRun`
API to allow users to specify resource requirements
of `Task` `Step`s and `Sidecar`s. These changes apply to both
one-shot `TaskRun`s and those launched via `PipelineRun`s.
/kind tep
> [Design Proposal] TEP-0094: Specifying Resource Requirements at Runtime

- working-groups.md
Forgot to add this when I added the governing board/community
meeting in https://github.com/tektoncd/community/pull/578 !
> Add link to gov board meeting at top of page 🔗

- teps/0079-tekton-catalog-support-tiers.md
- teps/README.md
In [TEP-0079: Tekton Catalog Support Tiers][tep-0079], we have defined
the problem statement for establishing support tiers for resources in
the Tekton Catalog.
In this change, we address the first goal of [Ownership and Maintenance][goal].
As previously discussed in [TEP-0003][tep-0003-upstream], we propose creating
two support tiers, `Community` and `Official`, through separate Tekton Catalogs.
The Community Catalog would make it easy for contributors to share resources,
while the Official Catalog will be a corpus of high quality resources that
users can rely on. This distribution of ownership would ensure the workload
is sustainable. 
The other goals and details of testing, scanning and verification will be
explored in the subsequent changes.
[tep-0079]: …
> TEP-0079: Tekton Catalog Support Tiers [Proposal - Ownership and Maintenance]

- teps/README.md
This change fixes the date on TEP-0089 to pass the PipelineRun on open TEPs (which is failing and blocking all PRs in this repo).
The `pull-community-teps-lint` PipelineRun did not run when we merged TEP-0089 in https://github.com/tektoncd/community/pull/529. It got merged with a linting issue - wrong date - that's causing the same PipelineRun to fail in open TEPs. Why it didn't run in that PR is still a mystery but focusing on unblocking PRs for now.
Examples: 
- https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/pull-community-teps-lint-h6fwd?pipelineTask=teps-lint&step=teps-table
- https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/pull-community-teps-lint-vw6qj?pipelineTask=teps-lint&step=teps-table
> Fix TEP Linting

- teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md
- teps/README.md
This TEP proposes changes to `PipelineRun` Status to reduce the amount of
information stored about the status of its `Run`s and `TaskRun`s to improve
performance, reduce memory bloat and improve extensibility.
Related Issues:
- [PipelineRun and TaskRun Status][issue-3792]
- [PipelineRun Status bloat and excessive updates][issue-3140]
Related TEPs:
- [Pipelines in Pipelines][tep-0056]
- [Matrix][tep-0090]
/kind tep
Co-authored-by: Lee Bernick <leebernick@google.com>
[tep-0056]: https://github.com/tektoncd/community/blob/main/teps/0056-pipelines-in-pipelines.md
[tep-0090]: https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md
[issue-3140]: https://github.com/tektoncd/pipeline/issues/3140
[issue-3792]: https://github.com/tektoncd/pipeline/issues/3792
> TEP-0100: Embedded TaskRuns and Runs Status in PipelineRuns [Problem Statement]

- teps/0098-workflows.md
- teps/README.md
Adds a problem statement for the [experimental workflows API](https://github.com/tektoncd/community/issues/464). The goal is to start a discussion around the use cases we should target for Workflows. The approach I'm planning to take is to design and work on this in an experimental project once we have the use cases. 
Moving from an experimental API to a full Tekton API is out of scope for now and can be considered depending on how the experimental project goes.
/cc @sbwsg @chmouel @khrm
> [TEP-0098] Workflows - Problem Statement

- org/org.yaml
Based on PR https://github.com/tektoncd/hub/pull/365, I want to add
myself as Hub maintainer. Link to my contributions are:
https://tekton.devstats.cd.foundation/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=tektoncd%2Fhub&var-country_name=All
> Add @vinamra28 as Hub Maintainer

- teps/0044-data-locality-and-pod-overhead-in-pipelines.md
- teps/README.md
This commit renames TEP-0044 to "More Execution Options for Pipelines" and re-focuses it on giving
users more control over how their Pipelines are executed. There are two reasons for this change:
- The problems identified with how Tasks are executed (pod overhead and difficulty passing data between Tasks)
are relevant only when executing multiple Tasks together, not when a single Task is executed in a TaskRun.
- The title "Decoupling Scheduling from Execution" implies that we must choose a runtime-based configuration
for Pipeline execution. This commit clarifies that while execution options must be configurable at runtime,
we may choose to also make them configurable at authoring time.
> [TEP-0044]: Refocus on Execution Options

- org/org.yaml
The resolution repo has just been spun up to host everything related to remote resolution in tekton.
This PR initializes the org.yaml entries for the resolution project, adding two teams: maintainers and collaborators.
Fixes https://github.com/tektoncd/community/issues/611
> Add resolution repo to org.yaml

- org/org.yaml
In my previous PR for the resolution.maintainers team peribolos was
erroring out during dry-run of team creation. This meant I missed a
lint error that would have otherwise surfaced.
This commit removes Dibyo from the members list of the
resolution.maintainers team since he already appears in the
"maintainers" list for that same team.
> Remove Dibyo from members list of resolution.maintainers

- working-groups.md
In the working group today, @wlynch volunteered to join the Chains
rotation. @dlorenc is listed in the rotation, I think from when the
working group was initially set up but hasn't been in the meeting
rotation.
(@dlorenc if you do want to be in the rotation after all just let me know and I'll change the commit!)
Also updated @priyawadhwa 's company! Exciting :D
> Update Chains facilitator rotation

- teps/0044-data-locality-and-pod-overhead-in-pipelines.md
- teps/README.md
This commit describes design constraints related to running multiple Tasks in one pod in more detail.
It also updates the alternative solutions based on the clarified problem statement.
Changes:
- Add 3 options: pipeline in a pod + pipelines in pipelines, pipeline -> taskrun, and task pre and post steps
- Modify and add more detail to the "TaskGroup" proposal
- Remove "focus on workspaces" option: this adds new syntax but not new functionality
- Remove "custom pipeline" solution due to similarity with grouping CRD solution
- Remove "custom scheduler" option: This is a solution for scheduling parallel Tasks that share a PVC
on the same node, but does not address the problems of pod overhead and the need
to share data between tasks in the first place.
Co-authored-by: Christie Wilson …
> [TEP-0044] Update Alternatives

- teps/0025-hermekton.md
Today, hermetic execution is supported through annotations as an
experiment. If successful, we plan to support hermetic execution
through a field in the API. The proposed API uses a bool, however
the Kubernetes API conventions [discourage using booleans][bools]
because they limit future expansions. This change updates the field
to use a string alias instead, as recommended in the conventions.
/kind tep
https://github.com/tektoncd/community/blob/main/teps/0025-hermekton.md
[bools]: https://github.com/kubernetes/community/blob/fbc5ca53d6bfd8388b335f7d0198b67a14b99d91/contributors/devel/sig-architecture/api-conventions.md#primitive-types
> TEP-0025: API change - use string alias instead of bool

- teps/0079-tekton-catalog-support-tiers.md
In this change, we update the `tekton.dev/catalog` annotation
to use a three part domain of the Catalog instead of its name
and we add a Catalog url annotation as well.
This makes it easier for users to know which Catalog the resource 
came from, especially when they have other Catalogs beyond those
provided by Tekton.
Thank you @afrittoli for the idea in https://github.com/tektoncd/community/pull/599#discussion_r792883111 🙏🏾 
/kind tep
> TEP-0079: Tekton Catalog Support Tiers [Catalog Annotations]

- org/org.yaml
In https://github.com/tektoncd/community/pull/605 I temporarily
requested maintainer status on pipelines so I could perform the releases
of Pipelines 0.32 + patches.
Now that the 0.32 release cycle is done this PR gives back that temp
maintainer status. Cheers & sorry again for the churn!
> Give back temp maintainer status now that 0.32 is released

- teps/0090-matrix.md
- teps/README.md
In [TEP-0090: Matrix][tep-0090] we described the problem statement for fanning out `PipelineTasks`. That is, enabling execution of a `PipelineTask` with different permutations of `Parameters` specified in a `Matrix`.
In this change, we add the proposal to solve the above problem. It includes the design details, implementation plan, promotion plan, design evalutation, future work, alternatives, and others.
In summary, we propose adding a `matrix` field to the `PipelineTask` specification that will be used to declare `Parameters` of type `Array`. The `PipelineTask` will be executed in parallel `TaskRuns` or `Runs` with its `Parameters` substituted with the permutations of `Parameters` in the `Matrix`.
POC Demo: https://drive.google.com/file/d/1wDYIl2Kqj5XiZzikF9878bcVb7_lmcoZ/view?t=31m11s …
> TEP-0090: Matrix [Proposal]

- teps/0044-data-locality-and-pod-overhead-in-pipelines.md
- teps/README.md
This commit adds details on the relationship between Hermekton and running multiple Tasks on one pod.
It proposes leaving Hermekton support out of scope for this feature due to feasibility constraints.
/kind tep
> [TEP-0044]: Add details on Hermekton

- teps/0076-array-result-types.md
- teps/README.md
This TEP proposes adding more support for array params by adding
array results as well as the ability to index into arrays.
It refers to TEP-0075 which will be added in a separate commit, which
proposes adding support for dictionary types.
Related issues:
* [pipelines#1393 Consider removing type from params (or _really_ support types)](https://github.com/tektoncd/pipeline/issues/1393)
* [pipelines#3255 Arguments of type array cannot be access via index](https://github.com/tektoncd/pipeline/issues/3255)
/kind tep
> [TEP-0076] Propose array results and indexing 🐠

- teps/0044-data-locality-and-pod-overhead-in-pipelines.md
- teps/README.md
This commit addresses the question of whether Tekton should be responsible for determining
which TaskRuns are executed in one pod. It proposes leaving this functionality as an option
for a later iteration of the proposal, and modifies the "TaskGroup" proposal to specify
that for the first implementation, all TaskRuns in a TaskGroup should be run in one pod.
/kind tep
> [TEP-0044]: Controller role in scheduling TaskRuns

- teps/0075-object-param-and-result-types.md
- teps/README.md
This TEP proposes adding support for more structured params and results
by introducing objects (aka dictionaries), and introducing a (small)
subset of json schema syntax for declaring keys in the object.
This refers to TEP-0074 which will be added in a separate commit and
proposes deprecating PipelineResources.
This is based on @skaegi's proposals in https://github.com/tektoncd/pipeline/issues/1393
/type tep
> [TEP-0075] Propose object (dictionary) param and result types 🤓

- teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md
- teps/README.md
In [TEP-0100][tep-0100], we described the challenges caused by embedding
the complete `TaskRun` and `Run` status in `PipelineRuns`: performance
degradation, memory bloat, and lack of extensibility.
In this change we add the proposal to reduce the amount of information
stored about the status of `TaskRuns` and `Runs` to only the object
references in order to improve performance, reduce memory bloat
and improve extensibility. We also mark the TEP as implementable.
Co-authored-by: Lee Bernick <leebernick@google.com>
/kind tep
/cc @vdemeester @imjasonh @bobcatfish @afrittoli
(approvers of the problem statement added in https://github.com/tektoncd/community/pull/606)
[tep-0100]: https://github.com/tektoncd/community/blob/main/teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md
> TEP-0100: Embedded TaskRuns and Runs Status in PipelineRuns [Proposal]

- working-groups.md
Details for the docs working group are out of date, meaning
some folks miss the meeting or wait to join the old one on
the wrong day.
- Update time/date
- Add correct calendar link
- Update list of faciliators
- Link to correct doc for 2022
> Update details of docs working group

- working-groups.md
Last week we had the first meeting of a working group focused on cross
project supply chain security interests, this commit adds the details
about this meeting going forward to the list of working groups.
We might want to replace the agenda doc and slack links with something
else if we're not happy with those but this at least gets something in
place :D
> Add supply chain security (s3c) working group to list 👷‍♀️

- governance.md
- process.md
See https://groups.google.com/g/tekton-governance/c/4n50jeqnDnA for motivation.
This is largely based off of
https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md.
This helps define more lower-stakes roles for getting involved with Tekton, as
well as updates existing roles to provide expectations of the roles.
Additionally, this adds a formal process to revoke permissions in
instances of inactivity or abuse.
I tried my best to keep the requirements the same as before, so this
shouldn't be introducing any new requirements for the
collaborator/maintainer roles.
Would appreciate majority review from gov-board 🙏
> Add contributor ladder.

- teps/0090-matrix.md
TEP-0090 references TEP-0075 and TEP-0076 quite a bit so wanted
them to link to the merged TEPs, instead of the pull requests
adding them. When TEP-0090 was merged, they had not yet been merged.
Updated all TEP links to resolve locally as well. Also fixed typos
in the TEP.
/kind tep
(not changing anything about the proposal, just minor editorial changes)
> TEP-0900: Update related TEPs references

- teps/0096-pipelines-v1-api.md
The feature flags `disable-home-env-overwrite` and `disable-working-directory-overwrite`
were recently removed from Pipelines (tektoncd/pipeline#4587). In addition, "PipelineRunCancelledStatus" is deprecated.
> [TEP-0096]: Update to reflect deprecated features

- README.md
In https://github.com/tektoncd/community/pull/549 we updated the contributor ladder but missed this link
> Fix link to contributor ladder from main README 🔗

- org/org.yaml
This is needed so that they can be assignees for experimental/workflows
See https://github.com/tektoncd/experimental/pull/836
> Add @khrm @savitaashture as experimental collaborators

- org/org.yaml
To work on tektoncd/experimental https://github.com/tektoncd/experimental/pull/840, I need to be added to experimental
collaborators members.
> Add Yongxuanzhang to experimental collaborators members

- org/org.yaml
After the recent election of Feb 2022, update the governance team
accordingly.
> Update tekton governance team

- org/org.yaml
Cleanup the experimental.maintainers team. Remove inactive users
and add the tekton governance team
> Update the experimental maintainers

- teps/0048-task-results-without-results.md
- teps/README.md
Adding one more use case - Supporting default values for the optional `Results` would help prevent unexpected failures, and improve our `Task` interface`.
/kind tep
> TEP-0048 - Update `Results` TEP to add use case of Providing Default Values

- teps/0074-deprecate-pipelineresources.md
- teps/README.md
This commit updates TEP-0074 to clarify that merging this TEP as implementable
is not a requirement for V1. This means that a V1 API will not include
PipelineResources, and may not include PipelineResource replacement features.
> [TEP-0074]: Not a V1 blocker

- teps/0096-pipelines-v1-api.md
This commit proposes removing any new features in TEP-0074 as V1 blockers.
This does not mean we are stopping work on or deprioritizing these features,
but it does mean that we can release a V1 API before they are implemented.
> [TEP-0096]: Remove TEP-0074 Features as blockers

- teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md
- teps/README.md
With the current, full embedded status for `TaskRun`s and `Run`s, we include `ConditionChecks` and `WhenExpressions` fields as well as the `TaskRun`/`Run`'s status. The minimal embedded status approach as initially written does fine for anything that's available within the `TaskRun`/`Run` statuses, but `ConditionChecks` and `WhenExpressions` are not actually known by the `TaskRun`/`Run`. They're only known at the full `PipelineRun` level. In order to make that information available for reporting, etc in the new minimal embedded status approach, we will need to store `ConditionChecks` and `WhenExpressions` along with the kind/version/`TaskRun` or `Run` name/`PipelineTask` name.
cc @jerop @lbernick - not sure who else should review this?
> [TEP-0100] Update to handle PipelineTask condition checks and when expressions

- governance.md
Since I am soon going to be on leave, I brought this up in a recent
governing board / community meeting, and this commit adds the policy
that we discussed adding for governing board members going on leave in
general. We wanted to make sure that this option was available
regardless of the reason for the leave.
The maximum period of time for the leave is however conveniently the
exact length of time I plan to be gone XD , so if folks have different
opinions on what the threshold should be, we can definitely change it
> Add a leave policy for governing board members 🏖️

- org/org.yaml
GitHub let us define a list of team members and team maintainers.
Since we maintain teams through peribolos, we should not really
have a list of team maintainers.
Each repo has a <repo>.maintainers and a <repo>.<collaborators>
team, each with its own list of maintainers and members, which
make things notably more confusing.
Last and not least, we have a pending task of sync'ing teams to
OWNER files in repos, however today it's hard to be sure that
the list of people members of <repo>.maintainers teams are those
who need to be in OWNERS since each individual can only be a
maintainer or a member.
Start experimenting doing this for the catalog team.
This also means that the Tekton governance team members do not
need to be members of all teams and maintainers of all repos.
It might be handy …
> Experiment with removing team maintainers

- contact.md
The contact.md page includes details on how to reach out to the Tekton
community. It should include details about reporting security related
issues as well.
> Added the security policy to the contact page

- teps/0102-https-connection-to-triggers-interceptor.md
- teps/README.md
Issue: https://github.com/tektoncd/triggers/issues/871
As part of this TEP proposing to make default secure connection between ClusterInterceptor and EventListener.
> [TEP-0102] HTTPS Connection to Triggers ClusterInterceptor

- teps/0075-object-param-and-result-types.md
- teps/0076-array-result-types.md
- teps/README.md
Update the TEPs about array and object support (TEP-0075 and TEP-0076)
to be implementable.
Also addressing feedback from @afrittoli in https://github.com/tektoncd/community/pull/479
Outstanding items:
* @afrittoli re. behavior of optional fields when combined with variable replacement (https://github.com/tektoncd/community/pull/479#discussion_r802555575) - i think that attempts to do variable replacement with a value that is not provided (even if it is optional) should fail and we should lean on the ability to provide defaults (and esp [TEP-0048](https://github.com/tektoncd/community/blob/main/teps/0048-task-results-without-results.md)) instead
* @afrittoli re. supporting a mode with no schema provided at all ((https://github.com/tektoncd/community/pull/479#discussion_r802634562, …
> [TEP-0075, 0076] Make array and object support implementable 👷‍♀️

- OWNERS
- governance.md
- org/org.yaml
- working-groups.md
1. Finishing up updates from governing board election (andrew bayer
no longer on the board, priya wadhwa joining the board)
2. @jerop will be taking my place on the governing board while I am
on leave (see [leave policy](https://github.com/tektoncd/community/blob/main/governance.md#governing-board-leave-policy))
(thanks @jerop !!)
Went through the list at https://github.com/tektoncd/community/blob/main/governance.md#changes-to-governing-board
to make sure jerop and priya have all the governing board permissions
and to make the changes required with andrew leaving the board.
Also added Priti to the governing board + community meeting faciltator
rotation because she is listed in the rotation in the doc.
While running the permissions adding script I ran into a couple of
difficulties which …
> Add jerop and priya to governing board, remove andrew 🗝️

- working-groups.md
Updating the video call links for all working groups to use zoom instead
of google meet; this is b/c with google meet, recordings could only be
started by someone at the same company as the person who created the
calendar event, which usually ended up being RedHat or Google - and
meant that only a limited number of people had access to the resulting
recordings in their inboxes.
With zoom, recordings will start automatically, though we still need
someone (currently governing board members have access) to make the
recordings available after they are created (but at least they aren't
lost in individual ppl's inboxes).
Also updated some times and other details when they looked stale.
Fixes #44
> Move WG video calls to zoom 🎥

- org/org.yaml
OWNER of the ansible builder task in the catalog, see https://github.com/tektoncd/catalog/pull/967.
> Adds myself to org

- teps/0103-skipping-reason.md
- teps/README.md
Today, users only know that a `PipelineTask` was skipped, but they don't know for which exact reason. In this TEP, we propose adding the reason for skipping to `SkippedTasks` field in `PipelineRunStatus` to improve usability and debuggability.
References:
* [Tekton Pipelines Issue 4738: Skipping Reason][issue-4738]
* [Tekton Pipelines Issue 4571: Task skipped when parallel task fails][issue-4571]
* [Tekton Community Slack Thread][slack]
* [TEP-0007: Conditions Beta][tep-0007]
* [TEP-0059: Skipping Strategies][tep-0059]
[tep-0007]: https://github.com/tektoncd/community/blob/main/teps/0007-conditions-beta.md
[tep-0059]: https://github.com/tektoncd/community/blob/main/teps/0059-skipping-strategies.md
[skipped-tasks]: https://github.com/tektoncd/pipeline/blob/053833cb10f3829d5a366daa1f431b293d …
> TEP-0103: Skipping Reason

- teps/0092-scheduling-timeout.md
- teps/README.md
This TEP addresses https://github.com/tektoncd/pipeline/issues/4078 by
proposing that at runtime `TaskRuns` can be configured with a new
timeout that applies before they actually start executing - and only
after that are the existing timeouts applied.
This is meant to make it possible to control when our existing timeout
feature works in resource constrained environment and also to get parity
with [Google Cloud Build's existing queuettl feature](https://cloud.google.com/build/docs/build-config-file-schema#queuettl).
> [TEP-0092] TaskRun scheduling timeout ⏱️

- teps/0105-remove-pipeline-v1alpha1-api.md
- teps/README.md
This is an initial effort towards a TEP for removing the Pipeline `v1alpha1` API,
which has been deprecated for over two years now.
/kind tep
> [TEP-0105]: Remove the Pipeline `v1alpha1` API

- org/org.yaml
I need to be added as experimental.collaborators so that I can review @yongxuanzhang's prs who is working on trusted task project.
> Add chuangw6

- teps/0104-tasklevel-resource-requests.md
- teps/README.md
This commit adds TEP-0104, which proposes allowing users to specify Kubernetes
resource requests for an entire Task. Migrated from [design doc](https://docs.google.com/document/d/1QlanhknM2-BqsYFki0L7odWXQ3oSIKMSoFZ_5j1_Pk4).
/kind tep
> [TEP-0104]: Task-level resource requests

- teps/0074-deprecate-pipelineresources.md
- teps/README.md
This commit updates TEP-0074 to reflect that implementing array and object support, plus
a solution for data locality, are not blockers for removing PipelineResources. It proposes
that PipelineResources may be removed as soon as 9 months after their deprecation was announced,
provided that our documentation and dogfooding do not use them.
/kind tep
> [TEP-0074] Mark as implementable

- org/org.yaml
This add vinamra28 as maintainer of the cli project
He has been made owner using the PR https://github.com/tektoncd/cli/pull/1558
> Add vinamra28 as cli maintainer

- org/org.yaml
The current requirements for becoming a maintainer are:
- Participating in reviews for at least 3 months: The first PR to Pipelines I reviewed was #4368,
opened on 11/9/21.
- Reviewed at least 30 PRs to the codebase: The [Tekton contributor dashboard](https://tekton.devstats.cd.foundation/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=reviews&var-repogroup_name=tektoncd%2Fpipeline&var-country_name=All)
shows that I have submitted 105 reviews to the pipelines repo in the past year, while the [Github UI](https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+reviewed-by%3Albernick) shows
42 pipelines PRs as reviewed by me (including a few of my own PRs). Not sure why there is such a large difference?
- Primary reviewer for at least 10 …
> Add Lee Bernick to pipeline maintainers

- org/org.yaml
I'm going to be making regular contributions to `Tekton` as a software developer at Google. Can I be added as an organizational member?
> Add chitrangpatel as an organizational member

- teps/0023-implicit-mapping.md
- teps/0107-propagating-parameters.md
- teps/README.md
*Tekton Pipelines* resources are verbose mostly because of explicitly propagating `Parameters`. Implicit `Parameters` feature was added to reduce the verbosity. However, there are challenges caused by mutating specifications to support Implicit `Parameters`.
This proposal builds on this prior work by propagating `Parameters` without mutating specifications to improve usability of *Tekton Pipelines*.
/kind tep
> TEP-0107: Propagating Parameters

- teps/OWNERS
@lbernick is now a maintainer for Pipelines and so should be a TEP OWNER as well!
> Add @lbernick to TEP OWNERS

- teps/0086-changing-the-way-result-parameters-are-stored.md
- teps/README.md
Initial TEP PR for issue tektoncd/pipeline#4012
> TEP-0086: Changing the way result parameters are stored

- teps/0106-support-specifying-metadata-per-task-in-runtime.md
- teps/README.md
The Related Issue
- [Pipeline Issue #4105](https://github.com/tektoncd/pipeline/issues/4105)
Design Doc
- [Support Specifying Metadata per Task in Runtime](https://docs.google.com/document/d/1JyeE_TEKDpnqr1uygxkALJyPKXMOypAwPfnEAx7HKyY/edit)
Implementation PR: 
- [TEP-0106 Implementation](https://github.com/tektoncd/pipeline/pull/4834) 
[Original PR](https://github.com/tektoncd/community/pull/690) was closed due to merge commits affecting a squash-down
> TEP-0106: Support Specifying Metadata per Task in Runtime

- teps/0101-env-in-pod-template.md
- teps/README.md
Currently there's no way we can define a pipeline level environment variables to overwrite all the task's `stepTemplate`. This can be troublesome when the CI provider wants to inject some cloud specific environment to each Tekton task/step and create a lot of redundant variables. Hence, we want to propose adding a pipeline level environment variables into the current Tekton pod template.
Signed-off-by: Tommy Li [tommy.chaoping.li@ibm.com](tommy.chaoping.li@ibm.com)
> [TEP-0101] Env in POD template

- org/org.yaml
Remove Steve from the Dashboard maintainers as he's no longer involved with
the project.
Add Lyndsey to the maintainers team. She has been contributing for over a year
now, providing great feedback in reviews, testing, providing input on design
changes, and helping to prepare for releases.
We've updated the OWNERS file in tektoncd/dashboard accordingly: https://github.com/tektoncd/dashboard/pull/2358
> Add Lyndsey to dashboard.maintainers

- design-principles.md
- teps/tools/tep-template.md.template
This commit clarifies our design principles on conformance to specify
that proposals should in general make Tekton more platform-agnostic,
that existing Kubernetes-isms in the Tekton API shouldn't be used as examples to add more,
and that expecting the user to understand how the API is implemented is something of an
anti-pattern. This commit also updates the TEP template to include questions on conformance.
> Update design principles guidance on conformance

- teps/0106-support-specifying-metadata-per-task-in-runtime.md
- teps/README.md
/kind tep
Updated the TEP status as "implemented" as the implementation PR was merged -- https://github.com/tektoncd/pipeline/pull/4834
> TEP-0106: Update as "Implemented"

- org/org.yaml
@wlynch has been contributing to Chains and reviewing PRs for months now! 
Opened up https://github.com/tektoncd/chains/pull/456 to add him to the Chains OWNERS file as well!
> Add wlynch as chains maintainer

- teps/0104-tasklevel-resource-requirements.md
- teps/README.md
After further reflection on this proposal, I realized pod effective resource limits
are not used for scheduling, and limits are enforced on individual containers by the
container runtime. This commit updates TEP-0104 to support Task-level resource limits
as a result. It also changes the behavior of how Task-level requirements interact with
Step-level requirements and with Sidecars as a result.
> [TEP-0104]: Support Task-level resource limits

- teps/0090-matrix.md
- teps/README.md
[TEP-0090: Matrix][tep-0090] proposed executing a `PipelineTask` in
parallel `TaskRuns` and `Runs` with substitutions from combinations
of `Parameters` in a `Matrix`.
In this change, we update the non-goals of TEP-0090:
1. In non-goal 2, we indicated that controlling concurrency is out
of scope. We actually ended up addressing controlling the concurrency
of `TaskRuns` or `Runs` created in a given `Matrix`. See [details][cc]
in the TEP. In this change, we remove this non-goal.
2. In non-goals 4 and 5, we suggested that `when` expressions can be
used to guard the execution of a particular combination of `Parameters`
from a `Matrix`. This is not possible because `when` expressions guard
the execution of the whole `PipelineTask` (and its `TaskRuns`/`Runs`).
In this change, we update those …
> TEP-0090: Matrix - Update Non Goals

- teps/0090-matrix.md
[TEP-0090: Matrix][tep-0090] proposed executing a `PipelineTask` in
parallel `TaskRuns` and `Runs` with substitutions from combinations
of `Parameters` in a `Matrix`.
In this change, we describe how the status of a `PipelineRun` with
a matrixed `PipelineTask` would be in full and minimal modes.
Previously, we had included `matrixId` to the `PipelineRun` status
so that it can help with identifying `Results` from fanned out
`TaskRuns` or `Runs`. However, we ended up descoping that problem
so that it can be addressed when TEP-0075 and TEP-0076 are implemented.
See [`Results` from fanned-out `PipelineTasks`][results] for details.
In this change, we remove the `matrixId` in `PipelineRun` status so
that the problem can be addressed completely later.
/kind tep
[tep-0090]: …
> TEP-0090: Matrix - Status

- teps/0104-tasklevel-resource-requirements.md
- teps/README.md
This commit proposes renaming Task-level compute resource requirements
to "ComputeResources", rather than "Resources", to disambiguate
from other uses of the term "Resources" in Tekton.
/kind tep
> [TEP-0104]: Rename "resources" field

- teps/0104-tasklevel-resource-requirements.md
This commit updates TEP-0104 to specify that we will implement
Task-level resource requirements for TaskRuns only to start,
and we may consider adding support on Tasks in the future.
/kind tep
> [TEP-0104]: Descope to runtime only

- org/org.yaml
As a new joiner in Google's Tekton team, my membership is endorsed by existing contributors.
> Add JeromeJu as an org member

- teps/0056-pipelines-in-pipelines.md
- teps/README.md
[TEP-0056: Pipelines in Pipelines](https://github.com/tektoncd/community/blob/main/teps/0056-pipelines-in-pipelines.md)
Today, users can define and execute `Tasks` and `Custom Tasks`
in `Pipelines`. In this TEP, we propose allowing users to define
and execute `Pipelines` in `Pipelines`, alongside `Tasks` and
`Custom Tasks`.
We previously described the motivation for this TEP in:
- #374
- #498
- #698
In this change, we add an overview of the proposal which includes
the API changes to the specification and status of `Pipelines`.
> TEP-0056: Pipelines in Pipelines [Proposal]

- org/org.yaml
Following [tektoncd contributor ladders](https://github.com/tektoncd/community/blob/main/process.md#contributor-ladder) @ywluogg has reviewed at least 15 PRs, and should be qualified to be a reviewer for Pipeline repo:
1. [#4786](https://github.com/tektoncd/pipeline/pull/4786)
2. [#4818](https://github.com/tektoncd/pipeline/pull/4818)
3. [#4835](https://github.com/tektoncd/pipeline/pull/4835)
4. [#4855](https://github.com/tektoncd/pipeline/pull/4855)
5. [#4861](https://github.com/tektoncd/pipeline/pull/4861)
6. [#4867](https://github.com/tektoncd/pipeline/pull/4867)
7. [#4872](https://github.com/tektoncd/pipeline/pull/4872)
8. [#4878](https://github.com/tektoncd/pipeline/pull/4878)
9. [#4883](https://github.com/tektoncd/pipeline/pull/4883)
10. …
> Add ywluogg into Pipeline reviewer roles

- teps/0096-pipelines-v1-api.md
- teps/README.md
In this change, we make it explicit that defining and executing
Pipelines in Pipelines is out of scope for V1 (not a blocker).
We will continue to make progress on TEP-0056, and the feature
will be available in V1 behind a feature flag.
Opened in response to question: https://github.com/tektoncd/community/pull/701#pullrequestreview-1012390830.
/kind tep
> TEP-0096: Pipelines V1 - Pipelines in Pipelines

- teps/0090-matrix.md
- teps/README.md
Prior to this change, we had agreed that the minimal status would
be auto-added for PipelineTasks which have a Matrix. During the
implementation, realized that it's unclear how we should handle
the other PipelineTasks in the Pipeline that don't have a Matrix.
Also realized that the automagic is opaque to users and could be
surprising to users who're not aware of the ChildReferences.
In this change, we propose that users have to enable the minimal
status to use Matrix. This is not a restrictive requirement as is
the direction we're moving to, and will become the default soon.
More importantly, it makes the behavior clear and the improves the
user experience.
/kind tep
cc @abayer
> TEP-0090: Matrix - Minimal Status is Required

- org/org.yaml
Catalog Task owner :
OWNER of the ab-load task in the catalog, see https://github.com/tektoncd/catalog/pull/1002.
OWNER of the cerberus-check task in the catalog, see https://github.com/tektoncd/catalog/pull/1004.
OWNER of the kraken-scenario task in the catalog, see https://github.com/tektoncd/catalog/pull/1003.
> Adding startxfr and startx-lab to org

- org/org.yaml
concaf was added to operator owner, add him here too to get
all permissions
> Add concaf to operator maintainers

- teps/0084-endtoend-provenance-collection.md
- teps/README.md
To assist in reviewing these changes, I've created an [example](https://github.com/lcarva/minimal-container/blob/178df1bfeb1b089bd22695f75aa99fd2d4fa679e/tekton/examples/pipelinerun-attestation-tep-84.json) pipelinerun attestation which was generated from a pipelinerun created from [this](https://github.com/lcarva/minimal-container/blob/178df1bfeb1b089bd22695f75aa99fd2d4fa679e/tekton/simple-build-pipeline.yaml) pipeline.
> tep-84: Clarify pipelinerun attestation format

- teps/0112-replace-volumes-with-workspaces.md
- teps/README.md
This TEP proposes removing volumes from the Task spec in the v1 API, as well as removing
volumeMounts and volumeDevices for the container-like fields (Step, StepTemplate, and Sidecar).
/kind tep
> [TEP-0112] Replace volumes with Workspaces [Proposal]

- org/org.yaml
@abayer was added as a pipelines owner - this change adds him to the core.maintainers group
> add @abayer to core.maintainers

- org/org.yaml
As a new joiner in Google's Tekton team, my membership is endorsed by existing contributors.
> Add QuanZhang-William as an org member

- teps/0096-pipelines-v1-api.md
This commit proposes renaming some fields of PipelineRun.TaskRunSpecs in v1 to avoid redundancy.
/kind tep
> [TEP-0096] Rename PipelineRun.TaskRunSpecs fields

- teps/0104-tasklevel-resource-requirements.md
- teps/README.md
This TEP proposes a change in implementation details to ensure that
task-level resource requests will work correctly when LimitRange default requests
are applied to a TaskRun's pod.
/kind tep
> [TEP-0104] Clarify interaction with LimitRanges

- teps/0116-referencing-finally-task-results-in-pipeline-results.md
- teps/README.md
In this change, we propose referencing `Finally` `Task` `Results` in `Pipeline` `Results`.
/kind tep
/cc @jerop
> TEP-0116: Referencing Finally Task Results in Pipeline Results

- teps/0112-replace-volumes-with-workspaces.md
- teps/README.md
This commit adds more options for supporting "dynamic" workspaces
and Task-internal workspaces. It also removes the option for adding
support for CSI volumes as workspace bindings, as this has been implemented.
/kind tep
> [TEP-0112] Add some more alternatives

- teps/0096-pipelines-v1-api.md
- teps/README.md
This commit updates TEP-0096 to specify that ClusterTasks should be
deprecated in favor of remote resolution. We are already not planning to bring
ClusterTasks into v1, but this change will allow us to make the future of this CRD
more clear to users. Discussed in https://github.com/tektoncd/pipeline/issues/4476
/kind tep
> [TEP-0096] Propose deprecating ClusterTask

- teps/0047-pipeline-task-display-name.md
- teps/README.md
This is rather straightforward as written - we just need to add `DisplayName` fields to `PipelineSpec`, `TaskSpec`, and `PipelineTask`, and add a `Description` field to `PipelineTask`.
> TEP-0047: Update and move to implementable

- teps/0096-pipelines-v1-api.md
This commit proposes leaving API fields related to step-level
compute resources at their current stability levels until we
are confident that we have a compute resources API we want to stabilize.
/kind tep
> [TEP-0096] Leave step compute resources in beta

- teps/0096-pipelines-v1-api.md
This commit adds improved upgrade tests as a blocker for v1, as
part of our "stability" v1 focus.
/kind tep
> [TEP-0096] Upgrade tests as v1 blocker

- teps/0096-pipelines-v1-api.md
This commit removes parameterizing additional fields as a potential v1
subtask for 2 reasons:
- There's no longer a clear use case for this, and the issue is closed
- Our Go libraries compatibility policy has been updated to specify that
this type of change is not considered a breaking change to the API, so it
can be done at any time.
/kind tep
> [TEP-0096] Remove reference to parameterizing more fields

- teps/0096-pipelines-v1-api.md
This commit proposes renaming `taskRun.status.taskResults` to
`taskRun.status.results` in v1, and likewise for PipelineRun.
There will no longer be a "resourcesResults" field, since PipelineResources
are deprecated.
/kind tep
> [TEP-0096] Rename taskResults/pipelineResults

- teps/0104-tasklevel-resource-requirements.md
- teps/README.md
This commit focuses on the behavior of Task-level resource requirements
in the case where a user specifies Task-level limits but not Task-level
requests. In this case, we must set some requests, as Kubernetes' default
behavior will result in overall requests that are too large. This commit
proposes setting Task-level requests equal to Task-level limits, similar
to the behavior used by Kubernetes.
/kind tep
> [TEP-0104]: Update case with limits but no requests

- teps/0091-trusted-resources.md
- teps/README.md
This commit proposes one solution to veriy the Tekton Resources via
admission webhook. It aims at starting the discussion on this work and
drives the Trusted Resources launched to Alpha.
This is a fork of https://github.com/tektoncd/community/pull/537 and work from @wlynch, and adapt it based on the poc in https://github.com/tektoncd/experimental/tree/main/pipeline/trusted-resources
> [TEP-0091]Trusted Resources

- teps/0115-tekton-catalog-git-based-versioning.md
- teps/README.md
In this TEP, we propose git-based organization contract to replace directory-based organization contract for Tekton Catalogs. This TEP builds on prior work in [TEP-0003][tep-0003] & [TEP-0110][tep-0110] and is a blocker for [TEP-0079][tep-0079].
[tep-0003]: 0003-tekton-catalog-organization.md
[tep-0079]: 0079-tekton-catalog-support-tiers.md
[tep-0110]: 0110-decouple-catalog-organization-and-reference.md
/kind tep
> TEP-0115: Tekton Catalog Git-Based Versioning

- teps/0076-array-result-types.md
Add more details for param variable replacement as a whole in TEP076
When elements in params of type arrays, it should be use variable replacements in three ways
> Add more details for param variable replacement as a whole in TEP076

- org/org.yaml
I'm the Google PM for Tekton and my membership is endorsed by wonderful Google contributors like Dibyo.
> Add alhuizenga to tektoncd members list

- teps/0120-canceling-concurrent-pipelineruns.md
- teps/README.md
This commit adds requirements and use cases for controlling concurrency of PipelineRuns.
/kind tep
> [TEP-0120] Canceling Concurrent PipelineRuns

- teps/0075-object-param-and-result-types.md
- Collision when other parameter names contain dots .
- Problem when the object parameter name itself or its key name
contains dots .
> TEP-0075: Add design proposal to handle edge cases

- org/org.yaml
Add adambkaplan (me!) to the Tekton GitHub organization. @dibyom and
@vdemeester have nominated me to be an approver for Results.
Signed-off-by: Adam Kaplan <adam@adambkaplan.com>
> Add adambkaplan to the tektoncd org

- teps/README.md
- teps/README.md.mustache
This commit updates the TEP process description to state that
after approval requirements have been met, no additional confirmation
is required to merge the TEP, and merging does not need to occur
during any meeting.
> [TEP Process] TEPs may be merged offline

- teps/0114-custom-tasks-beta.md
In v1alpha1, `Runs` have `Pod` templates. However, `Runs` do not always create `Pods`. 
In this change, we propose that `Runs` in v1beta1 should not have `Pod` templates - specific `Custom Tasks` implementation can support that in their own specifications.
Context: https://github.com/tektoncd/pipeline/pull/5403#discussion_r960774532
Many thanks to @lbernick for catching this issue!
/kind tep
cc @vsinghai @lbernick @vdemeester
> TEP-0114: Custom Tasks Beta - Remove Pod Template

- teps/0096-pipelines-v1-api.md
This commit proposes renaming fields related to compute resources in v1
to standardize around a single term for compute resource requirements
("computeResources").
Alternatively, we could rename `taskRun.spec.computeResources` to
`taskRun.spec.resources` in v1, since there will not be `pipelineResources` in v1.
However, `computeResources` is less overloaded and clearer.
/kind tep
> TEP-0096: Rename compute resources fields

- org/org.yaml
Related to https://github.com/tektoncd/cli/pull/1719
/cc @tektoncd/cli-maintainers 
> org: update cli maintainers and reviewers

- teps/0050-ignore-task-failures.md
- teps/README.md
This PR proposes adding a new field ```OnError```to ```PipelineTask```definition to allow users define task failure strategy
> [TEP-0050] Add proposed design details

- org/org.yaml
Collaborators added:
- @alhuizenga
- @bendory
- @lbernick
This change was discussed in the Tekton Docs WG, fulfilling the requirement of being nominated by an OWNER (me).
> Add website collaborators

- teps/0096-pipelines-v1-api.md
This commit updates the proposed renaming of  `pipelineRun.spec.[]taskRunSpecs.stepOverrides` and `pipelineRun.spec.[]taskRunSpecs.sidecarOverrides` to `pipelineRun.spec.[]taskRunSpecs.stepSpecs` and `pipelineRun.spec.[]taskRunSpecs.sidecarSpecs` 
Signed-off-by: Jerome Ju <jeromeju@google.com>
> [TEP-096] Update renamed fields

- teps/0075-object-param-and-result-types.md
- teps/0076-array-result-types.md
- teps/README.md
Implementation PRs for TEP 75:
https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+0075+in%3Atitle
Implementation PRs for TEP 76:
https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+0076+in%3Atitle+
> Mark tep75&76 implemented

- standards.md
Complement existing release note standards with a note about documenting any publicly known CVE specifically addressed by a PR.
This is a requirement for the OpenSSF badge:
> The release notes MUST identify every publicly known run-time vulnerability fixed in this release that already had a CVE assignment or similar when the release was created. This criterion may be marked as not applicable (N/A) if users typically cannot practically update the software themselves (e.g., as is often true for kernel updates). This criterion applies only to the project results, not to its dependencies. If there are no release notes or there have been no publicly known vulnerabilities, choose N/A.
> Callout publicly known CVEs for release notes

- README.md
- releases.md
Add policy and guidelines for Tekton projects about releases. This defines the required support policy for Tekton releases, also referred to as long-term-policy (LTS).
This is based on the discussion during the community/governace working group of Sept 13th 2022, plus extra proposed details.
Partially addresses: https://github.com/tektoncd/community/issues/806
> Add Tekton community-wide release policy

- teps/0115-tekton-catalog-git-based-versioning.md
- teps/README.md
This commit added a section to propose a new flag `versioning` in Catlin: https://github.com/tektoncd/catlin to support git-based versioning catalog path validation.
/kind tep
> [TEP-0115] Support git-based versioning validation in Catlin

- org/org.yaml
Community didn't have a team until now as we identified the
maintainers team with the Tekton governance team. The teams
may actually diverge, the first case is adding Priti :tada:
to the community maintainers to enable her to add commits
to an existing PR.
> Create a community.maintainers team

- teps/0120-canceling-concurrent-pipelineruns.md
This commit links users to the experimental project we've created for this TEP to make it more discoverable, and adds details on a use case discussed in the most recent workflows WG.
/kind tep
> TEP-0120: Add link to experimental + extra use case

- org/org.yaml
https://github.com/tektoncd/operator/pull/1066
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
> Adds piyush-garg as operator maintainer

- org/org.yaml
This commit adds Rafael Leal to the Tekton org and experimental collaborators, for collaboration on the experimental workflows project.
cc @RafaeLeal
> Add RafaeLeal to org + experimental collaborators

- OWNERS
- governance.md
- org/org.yaml
@jerop has been filling in for @bobcatfish in the governing board while she was on leave, see the [leave policy][leave-policy]
@bobcatfish is back 🎉🎉🎉
this change removes @jerop and adds @bobcatfish to the governing board
[leave-policy]: https://github.com/tektoncd/community/blob/main/governance.md#governing-board-leave-policy
> @jerop hands back governing board seat to @bobcatfish

- org/org.yaml
This commit adds Alan Ghelardi (from Nubank) to the Tekton org and to the experimental collaborators, for collaboration on the experimental Workflows and concurrency projects.
> Add alan-ghelardi to org

- org/org.yaml
Signed-off-by: pxp928 <parth.psu@gmail.com>
Adding Parth Patel (@pxp928) to tekton org.
Please let me know if I need to be added to another team or if this is enough.
> add parth (pxp928) to tekton org

- teps/0114-custom-tasks-beta.md
- teps/README.md
In [TEP-0121][tep-0121], we are redesigining `Retries` in `TaskRuns` and `CustomRuns`.
In this change, we propose excluding `retries` and `retriesStatus` in the initial release of `CustomRuns`.
We will figure out a way forward in [TEP-0121][tep-0121], which could be reintroducing the fields implementing replacement fields.
This allows us to unblock release of Custom Tasks Beta and Tekton Pipelines V1.
/kind tep
[tep-0121]: https://github.com/tektoncd/community/pull/816
cc @abayer @lbernick @XinruZhang
> TEP-0114: Custom Tasks Beta - Retries

- teps/0079-tekton-catalog-support-tiers.md
- teps/README.md
Continue the work of https://github.com/tektoncd/community/pull/793
This commit updates the "Ownership and Maintenance" section of TEP-0079, reflecting recent changes in:
- [TEP-0110][tep-0110]: Decouple Tekton Catalog Organization from Resource Reference
- [TEP-0115][tep-0115]: Tekton Catalog Git-Based Versioning
- https://github.com/tektoncd/hub/issues/667: Migration from Tekton Hub to Artifact Hub
This commit also renames the `official` support tier to `verified` to avoid naming confusion with the [official status][official-status] in Artifact Hub
/kind tep
[tep-0079]: https://github.com/tektoncd/community/blob/main/teps/0079-tekton-catalog-support-tiers.md
[tep-0110]: https://github.com/tektoncd/community/blob/main/teps/0110-decouple-catalog-organization-and-reference.md
[tep-0115]: …
> [TEP-0079] Ownership and Maintenance

- releases.md
The policy covers support for releases but it does not explicitly mention LTS anywhere, term which is used in releases.md files across Tekton projects. Introduce the LTS term and explain how it relates to the policy.
The term support is not clarified today - it implicitly aligns to what we do today, so make that explicit in the policy and list reason that justify a new patch release.
The policy today talks about four supported releases which matches the Jan/Apr/Jul/Oct used by several projects in their releases.md. To match that we shall do an LTS release every three months, not four. Kubernets does three minor/major releases per year, so in fact this policy does not align to the kubernets one, thus remove the sentece about that.
> Clarify LTS, support and number of releases

- teps/0121-refine-retries-for-taskruns-and-customruns.md
- teps/README.md
Retries is designed inconsistently between TaskRun and CustomRun, see the [Motivation](#motivation) section for details. In this TEP, we propose to align the inconsistency by
1. solidifying `TimeOut` is for each retry attempt, updating [TEP-069](https://github.com/tektoncd/community/blob/33ca1d5254a405b1d479f2350443f6c7979a0b72/teps/0069-support-retries-for-custom-task-in-a-pipeline.md) and [docs/runs.md](https://github.com/tektoncd/pipeline/blob/0dd9f9719177054bdf60928ce9b4aab4b85af5bd/docs/runs.md) to reflect the alignment.
2. migrating `Retries` implementation to TaskRun reconciler.
> TEP-0121: Refine Retries for TaskRuns and CustomRuns

- org/org.yaml
Please add ak1394 to the org, I'll be maintaining the `42crunch-api-security-audit` task: https://github.com/tektoncd/catalog/pull/1098
> Add ak1394 to org

- teps/0093-add-sign-verify-subcommand-to-the-cli.md
- teps/README.md
This commit proposes to add sign and verify into tekton cli to enable users to sign and verify tekton pipeline/task via tkn.
Signed-off-by: Yongxuanzhang <yongxuanzahng@google.com>
> [TEP-0093] Add sign and verify subcommand to the CLI

- teps/0121-refine-retries-for-taskruns-and-customruns.md
- teps/README.md
This PR proposes a solution for TEP-0121 and moves it to implementable. PTAL.
Signed-Off-By: @jerop  @XinruZhang 
cc @tektoncd/core-maintainers
> TEP-0121: Retries - Move to Implementable

- teps/0114-custom-tasks-beta.md
- teps/README.md
We've decided to move forward with keeping `Retries` and `RetriesStatus` in CustomRun Beta release in [2022.11.14 API WG](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#bookmark=id.n7b1ert0qisv). Updating this TEP to reflect the change.
cc @jerop @abayer @tektoncd/core-maintainers
> TEP-0114: Keep `Retries` and `RetriesStatus` in the Scope

- teps/0096-pipelines-v1.md
This commit adds migration plan for v1 regarding the v1 CRD release in v0.42.0
and the release for setting v1 as the storage version in v0.43.0.
> [TEP-96] Add migration plan for v1

- teps/0079-tekton-catalog-support-tiers.md
- teps/README.md
This commit updates the "Image Scanning for Common Vulnerabilities and Exposures" section of TEP-0079, which proposes to use [Trivy](https://github.com/aquasecurity/trivy/tree/main/pkg) as the CVEs scanning tool. It also proposes to integrate Tekton Catalogs to the [Artifact Hub Scanner](https://artifacthub.io/docs/topics/security_report/) service to run the reports periodically and show the reports in the Artifact Hub UI.
Signed-off-by: Quan Zhang <zhangquan@google.com>
> [TEP-0079] Image Scanning for CVEs

- teps/0115-tekton-catalog-git-based-versioning.md
- teps/README.md
Prior, the Tekton Catalog uses the simple [SemVer](https://semver.org/) model (`<major-version>.<minor-version>`) to version the resources for simplicity in the directory-based versioning.
This commit updates the proposal to use the full [SemVer](https://semver.org/)  model (`<major-version>.<minor-version>.<patch-version>`) as we switch to the git-based versioning, where bug fixes or security patches can go to the patch version instead of a new minor version. This update also resolves the inconsistency and confusion between the Artifact Hub (which uses the full SemVer versioning model) and Tekton Catalog versioning.
Signed-off-by: Quan Zhang <zhangquan@google.com>
> [TEP-0115] Use SemVer in Catalog

- teps/0114-custom-tasks-beta.md
- teps/README.md
This PR serves as a follow-up PR of https://github.com/tektoncd/community/pull/862 to reflect @lbernick's comment here https://github.com/tektoncd/community/pull/862#issuecomment-1292055648
We will support both v1alpha1.Run and v1beta1.CustomRun in the initial release until the design decision is made in [TEP-0121](https://github.com/tektoncd/community/pull/816).
cc @jerop, @lbernick, @abayer
> TEP-0114: Support Both V1alpha1 and V1beta1 for Custom Task in the Initial Release

- working-groups.md
We recently started a TEP-0086 Working Group. This change adds it to the list of working groups for visibility and transparency in the community.
cc @tektoncd/governing-board
> Add TEP-0086 Working Group

- design-principles.md
Add security to the list of Tekton design principles with details on specific requirements and links to OpenSSF reccomendations.
> Add security design requirements to Tekton

- teps/0091-trusted-resources.md
This commit adds more details of design evaluation. Since we need to pull in sigstore to make this proposal work, this needs to be included in this TEP. 
And also add more examples of keys, remove the configmap to store the keys since the crd covers all the needed features.
> [TEP-0091] Update TEP with design evaluations and more examples

- teps/0127-larger-results-via-sidecar-logs.md
- teps/README.md
Today, `Results` have a size limit of 4KB per `Step` and 12KB per `TaskRun` in the best case - see [issue][4012].
The goal of [TEP-0086][tep-0086] is to support larger `Results` beyond the current size limits. TEP-0086 has many alternatives but no proposal. This TEP proposes experimenting with one of the alternatives - `Sidecar` logs. This allows us to support larger `Results` that are stored within `TaskRun` CRDs.
Huge shout out to @chitrangpatel for implementing the [POC](https://github.com/tektoncd/pipeline/pull/5695) - see the [demo](https://drive.google.com/file/d/1NrWudE_XBqweomiY24DP2Txnl1yN0yD9/view?usp=sharing) 👏 
[4012]: https://github.com/tektoncd/pipeline/issues/4012
[4808]: https://github.com/tektoncd/pipeline/issues/4808
[tep-0086]: …
> TEP-0127: Larger Results via Sidecar Logs

- teps/0121-refine-retries-for-taskruns-and-customruns.md
- teps/README.md
Add an explaination on how a status changes with every retry of a taskRun/customRun. Adding an example here to show the transition when a task fails v/s a task timesout.
Open this PR to continue the discussion in https://github.com/tektoncd/community/pull/882 as Priti will be out next Month
This PR makes some modifications to address https://github.com/tektoncd/community/pull/882#discussion_r1037161026. See the file diff result between the two PRs: https://www.diffchecker.com/tmp7Jmmr
cc @pritidesai @jerop @afrittoli
> TEP-0121: Add status transition details

- teps/0114-custom-tasks-beta.md
- teps/README.md
In this change, we mark [TEP-0114][tep] as implemented. The implementation pull requests are [here][prs], and the migration guide is available [here][mig]. Thank you everyone for the contributions, and many thanks to @abayer and @XinruZhang 👏🏾  
[tep]: https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md
[mig]: https://github.com/tektoncd/pipeline/blob/main/docs/migrating-v1alpha1.Run-to-v1beta1.CustomRun.md
[prs]: https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+tep-0114+
> TEP-0114: Custom Tasks Beta - Mark as Implemented

- org/org.yaml
* Yongxuan has been a regular contributor to pipelines fixing flaky tests, adding
suppport for trusted resources as well as structured params and results.
Yongxuan meets all the requirements for being a project reviwer including the
review requirements:
https://github.com/search?q=-author%3AYongxuanzhang+repo%3Atektoncd%2Fpipeline+reviewed-by%3AYongxuanzhang+type%3Apr
* Chuang has been regularly contributing to pipelines over the past year on a
number of features such as structured params and results, provenance field in
pipelineruns etc and meets all the reviewer requirements.
Reviews: https://github.com/search?q=-author%3Achuangw6+repo%3Atektoncd%2Fpipeline+reviewed-by%3Achuangw6+type%3Apr
/assign @tektoncd/core-maintainers
> Add new pipeline reviewers - chuangw6, Yongxuanzhang

- teps/0115-tekton-catalog-git-based-versioning.md
- teps/README.md
This commit updates TEP-0115 to be `Implemented`.
The Tekton Hub to Artifact Hub Migration is tracked in: https://github.com/tektoncd/hub/issues/667
The Verified Catalogs Migration is scoped in [TEP-0079][tep-0079] and is tracked in: https://github.com/tektoncd/community/issues/889
[tep-0079]: https://github.com/tektoncd/community/blob/main/teps/0079-tekton-catalog-support-tiers.md
> [TEP-0115] Mark TEP-0115 as Implemented

- teps/0127-larger-results-via-sidecar-logs.md
- teps/README.md
In this change, we mark [TEP-0127][tep-0127] as implemented. The implementation pull requests are [here][prs].
Thank you everyone for the contributions and reviews, and many many thanks to @chitrangpatel 👏🏾 
[tep-0127]: https://github.com/tektoncd/community/blob/main/teps/0127-larger-results-via-sidecar-logs.md
[prs]: https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+tep-0127+
> TEP-0127: Larger Results via Sidecar Logs - Mark as Implemented

- org/org.yaml
@alan-ghelardi has been regularly contributing to the results project for the last few months and has also expressed interest in being a reviewer for the project!
https://github.com/tektoncd/results/commits?author=alan-ghelardi
/assign @adambkaplan 
/assign @vdemeester
> Add @alan-ghelardi as a Results collaborator/reviewer

- org/org.yaml
All maintainers team should have the "maintain" rights on the
repository they "maintain" instead of just write. It should allow them
to create tags and/or releases, etc (usually required for maintainer
doing a release).
> org: update maintainers team rights to "maintain"

- working-groups.md
Happy new year! In most recent WG we discussed updating the facilitator rotation b/c it felt out of date with who was attending and we also started using the hackmd doc to define the list (which is also much easier to update). Anyone interested in joining as a facilitator plz add yourself to the list there.
Also updated some other details that were out of date (links to closed issues and discussions)
> Update s3c wg facilitators and details 🎊

- process.md
This commit adds links to a template and folder in the Tekton Google Drive
for creating postmortems, and guidance on when and why to create a postmortem.
> Add process and template for postmortems

- org/org.yaml
Part of [#889][#889]. This commit add the `tektoncd-catalog` to the `org.yaml` file so that the org, org member, team and team members can be automatically managed by Peribolos (which lets `tektoncd-catalog` org reaches the same level of automation as `tektoncd`).
The role assignment can be only done for the members that have already joined the new org. The role is assigned to each individual based on his/her current role in `tektoncd/catalog` repo.
This commit only adds teams for the [golang][golang] repo as the migration of the repo is under going. More teams will be added in later PRs once we start the migration for other Verified Catalogs.
[golang]: https://github.com/tektoncd-catalog/golang
[#889]: #889
> Add tektoncd-catalog org to org.yaml

- teps/0079-tekton-catalog-support-tiers.md
- teps/README.md
This commit updates the "Automated Testing and Dogfooding" section of TEP-0079 based on the [previous work](https://hackmd.io/80AHmjpWQMixaP3-qkXyww?edit), which adds the testing strategy proposal for the Verified Catalogs and a testing infra template for Community Catalogs.
This commit also update the tep from `proposed` to `implementable` 🥂
> [TEP-0079] Catalog Automated Testing and Tekton Dogfooding

- teps/0122-complete-build-instructions-and-parameters.md
- teps/README.md
[This proposal](https://github.com/tektoncd/community/pull/820) was intended to be implementable but was accidentally left in proposed state. Some minor cleanup (accidental `buildConfig --> invocation.Parameters`) and clarifications were added to make it more readable. No major changes were introduced.
> TEP0122 - Complete build instructions and parameters - implementable

- teps/0074-deprecate-pipelineresources.md
This commit updates the TEP‘s proposal to remove `pipelineResources` before swapping the storage version to v1.
It conforms to the [deprecations.md](https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md) and [api_compatibility_policy.md](https://github.com/tektoncd/pipeline/blob/main/api_compatibility_policy.md).
> TEP0074 Update plans to remove `pipelineResources`

- teps/0096-pipelines-v1.md
There are features that became "stable" after TEP-0096 was implementable but before V1 CRDs were released and "beta" feature flag was introduced in v0.43:
- CSI Volumes
- Projected Volumes
- Propagated Parameters
These features have been guarded behind the "stable" feature flag in two releases with V1 CRDs - v0.43 and v0.44. During the API WG on 01/23, we agreed to officially promote these features to "stable".
Now that V1 CRDs have been released and "beta" feature flag is available, all features have to be promoted from alpha to beta to stable.
/kind tep
> TEP-0096: Document features that became stable during transition

- standards.md
As discussed in the WG, this commit adds to the guidelines that milestones should be added to the Pull Requests or Issues that target specific releases.
Thanks @pritidesai
> Contributing to Milestones

- teps/0083-polling-runs-in-tekton.md
- teps/0095-common-repository-configuration.md
- teps/0098-workflows.md
- teps/0128-scheduled-runs.md
- teps/README.md
This commit splits TEP-0083 (scheduled and polling runs) into two TEPs, one for scheduled runs and one for polling runs, and adds an implementation plan for scheduled runs.
/kind tep
> [TEP-0128]: Scheduled Runs

- standards.md
This commit updates code standards to include guidance on pull request size, structuring Go packages, and better release notes.
It also removes language around being in a "releasable state".
It's difficult to write a PR that puts us in an unreleasable state, since our CI prevents this,
so guidance that PRs shouldn't put us in an unreleasable state adds confusion.
> [Code standards] Add detail on small PRs and Go packages

- org/org.yaml
Jeeva Kandasamy is part of the Red Hat team working on OpenShift Pipelines and thus on tektoncd components.
Membership is endorsed by existing contributors @vdemeester @piyush-garg @concaf
/cc @abayer @afrittoli @jerop 
> Add jkandasa to the org

- teps/0074-deprecate-pipelineresources.md
This commit changes plans for supporting images built in Pipelines that are used by PipelineResources and their replacement Tasks. Most of these Tasks (other than the git-related ones) are not actively maintained or widely used, so this commit proposes deprecating these images.
/kind tep
> [TEP-0074] Update plans for image support

- working-groups.md
This will update the CLI and Operator WG meeting time to 30 mins before as discussed in slack and meeting.
Also update the facilitator to current ones and fix the descriptions
> Update the CLI and Operator WG meeting time

- org/org.yaml
The contributor ladder states that contributors may be moved to emeritus status [due to extended periods of inactivity](https://github.com/tektoncd/community/blob/main/process/contributor-ladder.md#inactivity). This commit moves Pipelines reviewers with < 5 reviews ever and 0 reviews in 2022 (based on https://gist.github.com/afrittoli/8aa0e878a87652f785bb9e5ec4c98400) to alumni status.
This will help prevent Pipelines pull-requests from being auto-assigned to inactive contributors.
To those who have been moved to alumni status, thank you for your contributions to this project, and you are welcome to return to active reviewer status at any time.
> Move inactive Pipelines reviewers to alumni

- teps/0130-pipeline-level-service.md
- teps/README.md
This commit opens a new TEP proposing better support for services
with the same lifespan as a PipelineRun.
/kind tep
> TEP-0130: Pipeline-level service

- teps/0133-configure-default-resolver.md
- teps/README.md
This commit adds a new TEP: Configure Default Resolver.
This commit adds proposal and implementation details to introduce a new field `default-resolver-type` in the ConfigMap to configure the default resolver type in Tekton. The design fulfills the requirement of [feature request #5907][#5907]
/kind tep
[#5907]: https://github.com/tektoncd/pipeline/issues/5907
> [TEP-0133] Configure Default Resolver

- org/org.yaml
The contributor ladder states that contributors may be moved to emeritus status due to extended periods of inactivity. This commit moves Pipelines reviewers with no reviews in 2022 to alumni, and alphabetizes the list of current reviewers.
To those who have been moved to alumni status, thank you for your contributions to this project, and you are welcome to return to active reviewer status at any time.
> Move inactive Pipelines reviewers to alumni (part 2)

- standards.md
This commit adds notes to our code standards on what functionality should be in pull requests, and clarifies what it means to be in a releaseable state.
> Code standards: Add notes on releasable state

- teps/0091-trusted-resources.md
- teps/README.md
This commit proposes to 
1. add  `mode` field into`VerificationPolicy`, update the feature flag to `verification-no-match-policy` with allow / warn / deny   
2. add condition into taskrun and pipelinerun to indicate the verification passes or not.
> [TEP-0091] Update trusted resources feature flag and add condition

- org/org.yaml
Nominated by [@pritidesai](https://github.com/pritidesai) and [@dibyom](https://github.com/dibyom) (Thanks!!)
I started to work on Tekton Pipelines since the end of March 2022. I've
implemented features such as Propagated Parameters, Propagated Workspaces, Larger Results
via sidecar logs and addressed a variety of bugs. [Here](https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+is%3Aclosed+author%3Achitrangpatel) is my full list of PRs.
I meet all the requirements for being a project reviwer including the
review requirements: https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+reviewed-by%3Achitrangpatel+-author%3Achitrangpatel
> Add chitrangpatel to Pipeline reviewers.

- teps/0001-tekton-enhancement-proposal-process.md
Today, TEPs can have the following states: `proposed`, `implementable`, `implemented`,`withdrawn` or `replaced`.
In this change, we add the `deferred` state for when a TEP is not actively worked on. This is the only remaining state we need to add from [KEP] process that inspired TEP process.
This state is useful when we want to move from `implementable`, but `withdrawn` and `replaced` is not quite right because there are some open questions. We ran into this scenario in [TEP-0092].
[KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/0000-kep-process/README.md#kep-workflow
[TEP-0092]: https://github.com/tektoncd/community/pull/969
> Add `deferred` state for TEPs

- teps/0041-tekton-component-versioning.md
- teps/README.md
TEP-0041 was implemented - https://tektoncd.slack.com/archives/CK9JGKS20/p167940569671645. This change updates the TEP state from `implementable` to `implemented`.
/kind tep
/cc @vdemeester
> TEP-0041: Tekton Component Versioning - Mark as Implemented

- teps/0027-https-connection-to-triggers-eventlistener.md
- teps/README.md
TEP-0027 was implemented in https://github.com/tektoncd/triggers/pull/819. This change updates the TEP state from `implementable` to `implemented`.
> TEP-0027: HTTPS Connection To Triggers EventListener - Mark as Implemented

- teps/0105-remove-pipeline-v1alpha1-api.md
- teps/README.md
TEP-0105 was implemented in https://github.com/tektoncd/pipeline/pull/5005. This change updates the TEP state from `implementable` to `implemented`.
> TEP-0105: Remove Pipeline v1alpha1 API - Mark as Implemented

- teps/0133-configure-default-resolver.md
- teps/README.md
This commit updates the TEP-0133 to `implemented` state with implementation PRs.
/kind tep
> [TEP-0133] Mark TEP-0133 as implemented

- teps/0074-deprecate-pipelineresources.md
- teps/README.md
PipelineResources have been removed - [PRs]. This change updates the TEP state from `implementable` to `implemented`.
/kind tep
[PRs]: https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+author%3AJeromeJu+is%3Aclosed+tep074
> TEP-0074: Deprecate PipelineResources - Mark as Implemented

- teps/0067-tekton-catalog-pipeline-organization.md
- teps/README.md
TEP-0067 was implemented - https://github.com/tektoncd/catalog/tree/main/pipeline. This change updates the TEP state from `implementable` to `implemented`.
/kind tep
> TEP-0067: Tekton Catalog Pipeline Organization - Mark as Implemented

- standards.md
This commit updates code standards instructing contributors to test only one function at a time, adding more detail around creating a focused set of test inputs and outputs.
> [Code standards] Clarify expectations for modular unit tests

- teps/0117-tekton-results-logs.md
- teps/README.md
TEP-0117 was implemented - https://github.com/tektoncd/results/pull/301. This change updates the TEP state from `implementable` to `implemented`.
/kind tep
> TEP-0117: Tekton Results Logs - Mark as Implemented

- teps/0072-results-json-serialized-records.md
- teps/README.md
TEP-0072 was implemented - https://github.com/tektoncd/results/pull/121. This change updates the TEP state from `implementable` to `implemented`.
/kind tep
> TEP-0072: Results: JSON Serialized Records - Mark as Implemented

- process/README.md
Readme files in the Prow repo are marked as deprecated and it seems the files are overdue for deletion, they are about to disappear.
The changes point to migrated doc location.
---
For future reference, screenshot of current Prow repo Readmes:
> Change deprecated Prow links

- standards.md
Before, this comes across as "tests are only needed for exported functions", which isn't quite true as it's frequently useful to have tests for unexported behavior, and this is somewhat contradictory to our other guideline of only exporting values that we want people to use.
This tweaks the policy to:
- Explicitly recommend preferring unexported/internal types.
- Softens the language of only writing tests for unexported functions to what I think was really the intent - focusing on testing the external surface of functions from the perspective of how users would use it.
- Removes language of recommending using external `_test` packages (this was a forcing function to get people to only use exported functions)
Open to feedback!
/cc @lbernick
> standards.md: Clarify policy for writing tests for unexported functions.

- working-groups.md
While Workflows is still an active area of interest, and the TEP is in "proposed" state,
Workflows WG is no longer actively meeting. This commit removes the meeting links from
the calendar, but maintains the link to the slack channel and points of contact.
> Remove links to Workflows WG meetings

- org/org.yaml
I am doing the release, so I need to be a member of the maintainers team in results. I need access to release notes. Same with other members, they will probably do the release in future.
> Add khrm, sayan and enarha to Results Maintainers

- org/org.yaml
Primarily removes inactive users from maintainer ACL and matches admin permissions to current maintainers.
/cc @lcarva - also added you to community.collaborators so you can lgtm PRs like this)
/cc @chuangw6 - saw the agenda item you added to the chains wg - hopefully this clears things up.
> Cleanup org.yaml for chains groups.

- teps/0135-coscheduling-pipelinerun-pods.md
- teps/README.md
This commit adds a proposal for scheduling all PipelineRun pods to a single node.
/kind tep
> TEP-0135: Coscheduling PipelineRun pods

- process/contributor-ladder.md
Prior to this change, the *reviewer* and *maintainer* requirements considered reviews only as the requirement. In this change, we include authoring of pull requests as a meaningful contribution that counts towards becoming a *reviewer* or *maintainer*.
Note that the *organization member* requirements already accounts for both authoring and reviewing pull requests. In addition, the Kubernetes [ladder] (that inspired the Tekton ladder) accounts for both authoring and reviewing pull requests.
[ladder]: https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer
cc @tektoncd/governing-board as discussed in today's meeting
> Include authorship of pull requests in ladder requirements

- standards.md
See error-wrapping documentation at https://pkg.go.dev/errors
> Use `%w` to wrap errors.

- org/org.yaml
See https://github.com/tektoncd/operator/pull/1536:
- Add @jkandasa as a maintainer
- Add @PuneetPunamiya as a reviewer
- Remove inactive users from maintainers/reviewers
/cc @afrittoli @jerop @piyush-garg @PuneetPunamiya @jkandasa
> Update operator's owners to be in sync with the repository

- standards.md
PR to update the links in the standards.md file for contributors
**_Release notes:_**
```release-note
NONE
```
Minor docs change
> Fix broken Docs links in standards.md

- teps/0135-coscheduling-pipelinerun-pods.md
- teps/README.md
Before this commit, the default value of `coscheduling` is `disabled`. This configuration does not preserve the current affinity assistant behavior (coschedule workspaces) after the `disable-affinity-assistant` field is deprecated. It also introduces confusion when configuring the new `coscheduling` and existing `disable-affinity-assistant` feature flags together.
This commit update the default value of the `coscheduling` feature flag to `coschedule-workspaces`, which preserves the current affinity assistant behavior. This commit also adds a chart of combinations of the `coscheduling` & the `disable-affinity-assistant` feature flags, and the corresponding affinity assistant behaviors before and after migration.
/kind tep
> TEP-0135: update coscheduling default value

- teps/0135-coscheduling-pipelinerun-pods.md
- teps/README.md
This commit updates the values of the `coscheduling` feature flag from `coschedule-workspaces` and `coschedule-pipelineruns` to `workspaces` and `pipelineruns` respectively to make the values more concise.
/kind tep
> [TEP-0135] Rename coscheduling feature flag values

- roadmap.md
The beta of the matrix feature (tracked in https://github.com/tektoncd/pipeline/issues/5265) should be part of our 2023 roadmap.
> Add matrix beta to roadmap

- org/org.yaml
As one of the maintainers for Tekton Chains, lcarva needs this acces in order to be able to create Tekton Chains releases.
> Add lcarva to plumbing.collaborators

- org/org.yaml
Nominated by: @wlynch
- Authored: 24 https://github.com/tektoncd/chains/pulls?q=is%3Apr+author%3Achuangw6+is%3Amerged+ 
- Reviewed: 30 https://github.com/tektoncd/chains/pulls?q=is%3Apr+reviewed-by%3Achuangw6++is%3Amerged+
/cc @lcarva 
/cc @priyawadhwa 
/cc @chuangw6
> Add chuangw6 to chains maintainers.

- org/org.yaml
@chitrangpatel has been involved in the Tekton Chains project for at least 6 months. He has made several contributions. Most recently, he is driving the design and implementation of producing SLSA Provenance v1.0. This has resulted in numerous PRs, design docs, and discussions. He has provided [144 PR comments in the last 3 months](https://tekton.devstats.cd.foundation/d/46/pr-reviews-by-contributor?orgId=1&var-period=d&var-repo_name=tektoncd%2Fchains&var-reviewers=%22chitrangpatel%22&from=1682049600000&to=1689998399000) across [25 PRs](https://github.com/tektoncd/chains/pulls?q=is%3Apr+reviewed-by%3Achitrangpatel+).
The number of PRs is lower than the required 30. However, Chains has a lower rate of changes than tektoncd/pipeline, for example. He is just as active as the existing …
> Make chitrangpatel a Chains maintainer

- process/contributor-ladder.md
This is lifting language from the k8s contributor ladder, which the ladder was heavily based off of to begin with:
https://github.com/kubernetes/community/blob/master/community-membership.md#member.
IIUC, this shouldn't change the process. This clarifies expectations on how much involvement someone should have before they're added to the org.
> Clarify org member requirements.

- teps/0141-platform-context-variables.md
- teps/README.md
This commit adds a problem statement for allowing platform builders to provide context variables that can be referenced in PipelineRuns.
/kind tep
> [TEP-0141] Problem statement: Platform context variables

- contact.md
The old link expired.
Fixes #1066
> Update Slack invite link

- teps/0128-scheduled-runs.md
- teps/README.md
Suggested addition of a field or annotation in Pipelinerun for scheduling. The controller to schedule Pipelineruns can be part of pipelines.
> [TEP-0128] Add an alternative Design for Scheduling Pipelineruns

- teps/0033-tekton-feature-gates.md
- teps/0138-decouple-api-and-feature-versioning.md
- teps/README.md
This commit adds the proposals for decoupling api and feature versioning. This TEP is marked as 'implementable'.
> [TEP-0138]: Decouple API and Feature Versioning Proposal

- org/org.yaml
Yongxuan was recently added as a maintainer. Billy has been a maintainer for a while but he was missing from this team.
> Add @yongxuanzhang and @wlynch to core.maintainers

- teps/0145-cel-in-whenexpression.md
- teps/README.md
This commit adds the proposal of adding CEL in WhenExpression
Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com
> [TEP-0145] CEL in WhenExpression

- org/org.yaml
When another member tried to assign me as a reviewer to the TEP, the bot rejected it with the [message](https://github.com/tektoncd/community/pull/1055#issuecomment-1753310644.).
This PR fixes that by adding @chitrangpatel as a community collaborator.
> Add chitrang as community collaborator

- teps/0144-param-enum.md
- teps/README.md
This commit adds the problem statement and design proposal to introduce a new `enum` field to support Tekton built-in `param` input validation mechanism.
/kind tep
> [TEP-0144] Param Enum

- contact.md
The previous link expired. The new one is set up so that it doesn't expire
> Use non expiring Slack invite link

- teps/0146-parameters-in-script.md
- teps/README.md
This PR adds the problem statement for the TEP and identifies possible solutions. The proposal will be added in a subsequent PR after discussions of alternatives.
Using `Parameter` variables directly in `script` blocks in `Tasks` is a footgun in two ways:
- **Security**: It is easy for a `Task` _author_ to accidentally introduce a vector for code injection and, by contrast, difficult for a `Task` _user_ to verify that such an injection can't or hasn't taken place.
- **Reliability**: It is easy for a `Task` _user_ to accidentally pass in a `Parameter` with a character that would make the `Script` invalid and fail the `Task`, making the `Task` extremely fragile.
To solve the above problems, this TEP aims to:
- Introduce a safe and reliable way to access `Parameter` variables from `Scripts`, …
> [TEP-0146] `Parameters` in `Script`

- teps/OWNERS
This PR adds Chitrang to `tep/OWNERS`.
While reviewing https://github.com/tektoncd/community/pull/1044, I was unable to `approve` it with the slash command. 
I was encouraged by several maintainers to add myself as an Owner of TEPs since I have been actively engaging in designs.
> Add Chitrang to TEP owners to grant approval privileges

- teps/0143-concise-parameters-results.md
- teps/README.md
This commit adds the proposal of concise parameters and results.
Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com
> [TEP-0143] Concise Parameters and Results - proposed

- org/org.yaml
loosebazooka is not active, and does not plan to be for the foreseeable future
> remove loosebazooka

- teps/0144-param-enum.md
- teps/README.md
Prior to this commit, Tekton validates the intersection of the enums that are both specified at `Pipeline` level and at the referenced `PipelineTask` level. In this solution, users are burdened with calculating intersections by iterating through all the PipelineTasks.
This commits add an extra validation to require that the pipeline-level enum must be a subset of the corresponding pipeline-task level enum. With this approach, users only need to check the pipeline-level enum to execute the pipeline successfully.
/kind tep
> [TEP-0144] Param Subset Enforcement

- teps/0142-enable-step-reusability.md
- teps/README.md
Prior to this, the TEP did not go into details of the use of `StepResults` in inlined step. For consistency with `StepActions`, this PR includes the use of `StepResults` for inlined Steps as well.
This is a PR following consensus in the API WG on Nov 20, 2023.
/kind tep
> Update usage of StepResults with StepActions

- teps/0144-param-enum.md
- teps/README.md
This commit updates tep-0144 to be `Implemented` and adds implementation PRs
/kind tep
> [TEP-0144] Implemented

- teps/0138-decouple-api-and-feature-versioning.md
This commit updates the table of new feature flags and their default values at each stability level.
> Update future feature flags default table

- teps/0148-summaryaggregation-api-for-tekton-results.md
- teps/README.md
This TEP proposes a new API endpoint for Tekton results that will allow users to
get a summary or aggregation data given a set of filters. This will be useful
for getting a quick overview without having to go through all the response and also
reduce the amount of data that needs to be transferred. This will also provide
a way to get aggregated data for a set of filters.
Co-authored-by: Khurram Baig <kbaig@redhat.com>
Signed-off-by: Avinal Kumar <avinal@redhat.com>
/kind tep
> TEP-0148: Summary/Aggregation API for Tekton Results

- teps/0151-error-attribution-via-condition-status.md
- teps/README.md
This is a problem statement to enhance existing error attribution for v1 Tekton Pipeline by introducing more instructive ConditionType and breaking down the existing failure reasons.
/kind tep
> TEP-0151: Error Attribution via Condition Status

- teps/0147-tekton-artifacts-phase1.md
- teps/README.md
This TEP proposes to split the work required to support Tekton Artifacts into multiple phases. In this phase, we define the Artifatct provenance data structure and how the Step surfaces that information to the `TaskRun Status` and to the provenance payload via Tekton Chains.
Prototyped by @ericzzzzzzz 🎉 https://github.com/tektoncd/pipeline/pull/7632
> TEP-0147: Tekton Artifacts phase 1

- governance.md
This PR updates the timeline of the winners of the 2024 Tekton Governing Board.
> 2024 Tekton Governing Board

- org/org.yaml
Siamak is part of the openshift-pipelines teams, and is going to own
at least a task in `tektoncd/catalog` (see
https://github.com/tektoncd/catalog/pull/1246).
I (vdemeester) am endorsing him.
> Add siamaksade to the tektoncd org

- teps/0154-concise-remote-resolver-syntax.md
- teps/README.md
This PR proposes to include a concise remote resolver syntax to reference remote resources.
It addresses the feature request https://github.com/tektoncd/pipeline/issues/7508.
/kind tep
> TEP-0154 Concise Remote Resolver Syntax

- org/org.yaml
@jkhelil is part of the openshift-pipelines teams. Currently he is focusing on operator component.
I would like to add him as member of tektoncd org.
> add jkhelil to the tektoncd org

- org/org.yaml
Add @rhybrillou as a member in the community as he is a prospective owner in the catalog repo as well as already marked as an expected owner within the catalog repo (see [this PR](https://github.com/tektoncd/catalog/pull/1259)).
He is a colleague working within the same team as me within Red Hat on Advanced Cluster Security.
> Add rhybrillou as a member

- teps/0156-whenexpressions-in-step.md
- teps/README.md
This pull request proposes the ability to define When Expressions directly within Steps. This allows for fine-grained control over step execution based on conditions like the status of previous steps, enabling more dynamic and adaptable workflows.
- Steps accept an optional when field with a list of When Expressions.
- When Expressions are evaluated at the entrypoint level, allowing access to previous step results.
- Skipped steps due to When Expressions have an exit code of 0 and a TerminationReason of Skipped. 
- Both Operator-based and CEL expressions are supported.
- Variable substitution within When Expressions includes access to Task Results, Params, Workspaces, and Step Results.
> TEP-0156 : when-in-steps

- teps/0147-tekton-artifacts-phase1.md
- teps/README.md
Prior to this, Chains did not have a way to handle the difference in output artifacts. This allows users to indicate to chains what their desire is when it comes to the provenance.
/kind tep
> Add field `isBuildArtifact` to an artifact category.

- org/org.yaml
Thank you @chengjoey for reminding me in [this comment](https://github.com/tektoncd/pipeline/pull/8312#issuecomment-2580459375). I didn't realize before that I could apply for membership in the Tekton organization. I would like to formally apply to join the Tekton organization now.
Since March 15, 2023, my contributions to the community have primarily focused on fixing bugs that I encountered while using Tekton in my work. I haven't been very active in reviewing others' contributions, as I mistakenly assumed that only members could participate in the review process.
I have a particular strength in identifying, debugging, and resolving issues, and I plan to continue contributing to the Tekton community in this capacity.
Based on the organization's …
> chore: add l-qing to tekton org

- teps/0063-workspace-dependencies.md
- teps/README.md
Added note about TEP-0043 (Workspace Dependencies) being withdrawn.
*This TEP is marked as `withdrawn` as it doesn't really had too much on
top of using `runAfter` and workspaces.*
/kind tep
> TEP: Mark TEP-0063 as withdrawn

- teps/0032-tekton-notifications.md
- teps/README.md
Added note about TEP-0032 (Tekton Notifications) being deferred and
not actively worked on.
/kind tep
> TEP: Mark TEP-0032 as deferred

- teps/0044-data-locality-and-pod-overhead-in-pipelines.md
- teps/README.md
Added note about TEP-0044 (Data Locality and Pod Overhead in Pipelines)
being withdrawn.
This TEP is marked as `withdrawn` as most of what it proposes is
doable today. It precedes some changes in the workspace that make this
TEP not relevant anymore.
/kind tep
> TEP: Mark TEP-0044 as withdraw

- teps/0071-custom-task-sdk.md
- teps/README.md
Added note about TEP-0071 (Custom Task SDK) being deferred and
not actively worked on.
/kind tep
> TEP: Mark TEP-0071 as deferred

- teps/0038-generic-workspaces.md
- teps/README.md
Added note about TEP-0038 (Generic Workspaces) being withdrawn.
This TEP is marked as `withdrawn` as most of what it proposes is
doable today. It precedes some changes in the workspace that make this
TEP not relevant anymore.
/kind tep
> TEP: Mark TEP-0038 as withdraw

- teps/0044-data-locality-and-pod-overhead-in-pipelines.md
- teps/README.md
Follow-up to https://github.com/tektoncd/community/pull/1182
A note was added in a previous change to mark TEP-0044 as withdrawn but the status field was not updated.
> TEP: Mark TEP-0044 as withdrawn

- contact.md
This PR fixes the broken link to join the TektonCD Slack.
I was not able to join last week. @afrittoli helped me and gave me a working link which I submit in this PR.
Closes issue #1187.
> Fix broken link to join the tektoncd slack

- teps/0160-enhance-results-cli.md
- teps/README.md
Proposing a TEP to enhance the existing functionalities of the Tekton Results CLI
Inspired by the [kubectl plugin](https://github.com/sayan-biswas/kubectl-tekton) developed by @sayan-biswas ❤️ 
/kind tep
> TEP-0160 Enhance Tekton Results CLI

- org/org.yaml
After getting [11 pull requests](https://github.com/pulls?q=is%3Apr+author%3AtwoGiants+archived%3Afalse+org%3Atektoncd+is%3Aclosed) merged and being active in the Tekton project in several repositories I can be added to the org and climb one step up the [Contributor Ladder](https://github.com/tektoncd/community/blob/main/process/contributor-ladder.md#organization-member).
> Add Stanislav Jakuschevskij (twoGiants) to Tekton org.

- org/org.yaml
Request to become Org Member.
@pramodbindal  is part of tekton team at RedHat and endorced by @vdemeester
> Add pramodbindal as org member

- org/org.yaml
This is to reflect OWNERS file from tektoncd/pipeline.
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> Add waveywaves to core.maintainers group

- org/org.yaml
Request to add @athorp (me) as a Tekton org member
@aThorp96 is a member of the Tekton team at Red Hat and is endorsed by @vdemeester.
> Add @aThorp96 to org

- working-groups.md
Update the link to the notes for the General WG to point to the currently used version instead of the old version from 2022.
The correct link is also included in the calendar entries.
/kind misc
> Update link to general working group notes

- teps/0161-resolver-caching.md
- teps/README.md
This is a draft TEP for the work I am doing in tektoncd/pipeline#8825 to add caching to the resolvers, primarily git and bundle resolvers.
> TEP-0161: resolver caching

- org/org.yaml
mangelajo and I (bkhizgiy) are part of RHIVOS and are working on the Jumpstarter project. We're going to own these tasks in the tektoncd/catalog (see https://github.com/tektoncd/catalog/pull/1340).
We'd like to become part of the org to maintain our tasks. Thanks!
> Add mangelajo and bkhizgiy to the tektoncd org

- teps/0162-event-based-pruning-of-tekton-resources.md
- teps/README.md
This PR includes the TEP to adopt [Event-based-Pruner](https://github.com/openshift-pipelines/tektoncd-pruner) to the tektoncd org.
The [Event-based-Pruner](https://github.com/openshift-pipelines/tektoncd-pruner) proposes an event triggered mechanism to cleanup completed PipelineRuns and TaskRuns as and when the Runs are completed based on pruner configurations defined in a configMap.
> Proposal to adopt event based pruner to tektoncd org

- org/org.yaml
They have already been added to the OWNERS file in the Chains repo: https://github.com/tektoncd/chains/pull/1418
/kind misc
> Add jkhelil to chains.maintainers

- org/org.yaml
Andrew has been contributing with very helpful reviews and insights since the beginning of this year and him contributions and technical rigour have proved extremely helpful for the community. This commit sees to it that he is added to the collaborators to help move things along a faster.
> add aThorp96 in core.collaborators
