tektoncd/community

governance.md

@kimsterv @bobcatfish @abayer @vdemeester 
I'd love comments from everyone interested, but will wait for LGTM's from each member before merging.

Add the initial bootstrap governance proposal.

---

governance.md

/assign @vdemeester @bobcatfish

Fix typos in initial governance.

---

contact.md

We have our own slack now :D Let the cats rain down!
Note that we could have much more extensive guidelines here, e.g. these are the guidelines for the knative slack: https://github.com/knative/docs/blob/541df1a173298ca94aa4ee5015e350108899674c/contributing/SLACK-GUIDELINES.md but my inclination is to keep it simple until we need more.

Update link to use `tektoncd` slack! 🗣️

---

contact.md

Let's hope it works for ever, otherwise we'll find a new solution.
/cc @bobcatfish @abayer 

Add the invite link to the slack 👼

---

contact.md

include mailing list for users

update mailing list

---

contact.md

Fix a minor typo in contact.md.
Signed-off-by: Dan Norris <protochron@users.noreply.github.com>

Fix typo in Contact doc

---

user-profiles.md

Follow Helm's good example of community guidance, prioritizing by
user profile. This will clarify priorities when updating Tekton
Relevant discussion in comments on design document shared
to the mailing list and discussed at the weekly meeting:
https://docs.google.com/document/d/1WbqPX4wmT1XLoJTM7gKekxLIUSZkggAcosYhR3lA6YQ
fixes #28
https://github.com/tektoncd/community/issues/28 
@vdemeester @bobcatfish @dlorenc @kimsterv @abayer

Add user-profiles.md

---

contact.md

This was the most popular time in our survey!

Move triggers WG to Tuesdays ⚡

---

org/org.yaml

One more (hopefully final) test of peribolos!

Add sclevine to the tekton org!

---

org/org.yaml

I somehow made a typo on pradeepitm12's line, and accidentally readded the knative-prow-robot.
Other than this, peribolos works!

Re-remove knative-prow-robot and fix pradeepitm12.

---

org/org.yaml

Adding @praveen4g0 to tekton org

Add @praveen4g0 to the tekton org

---

README.md
contact.md
process.md
working-groups.md

- list all working groups,
- for each working groups: calendar, time, video call link, meetings
notes and facilitators
I need to bootstrap some of the WG listed below :angel: and also, we should make sure I did put the right link at the right place :nerd_face: 
/hold
/cc @bobcatfish @kimsterv @abayer @dlorenc @chmouel @skaegi @ncskier @vtereso @dibyom 

Add a new page dedicated for working-groups 🍇

---

org/org.yaml

👀
@kimholmes is looking to become a member and to be able to create epics and use our zenhub boards

Add kimholmes

---

working-groups.md

Representing my corporation by lower casing the w in VMware.

Lowercase w for VMware

---

org/org.yaml

* I would really like to help with tekton triggers
* I will start by helping with the documentation, website and testing.

Add @popcor255 to list

---

org/org.yaml

I've already made some contributions to tektoncd/triggers
I have a PR up currently for tektoncd/catalog
And I envision making some contributions to tektconcd/pipelines in the future
/assign @vdemeester

add gabemontero to list

---

org/org.yaml

I have worked on the following pull requests on tektoncd/cli:
https://github.com/tektoncd/cli/pull/789
https://github.com/tektoncd/cli/pull/751
https://github.com/tektoncd/cli/pull/750
https://github.com/tektoncd/cli/pull/481
and the following pull requests on tektoncd/pipeline:
https://github.com/tektoncd/pipeline/pull/1790
https://github.com/tektoncd/pipeline/pull/1758
https://github.com/tektoncd/pipeline/pull/1650
https://github.com/tektoncd/pipeline/pull/2244
My future work will continue to revolve around cli and pipeline for a little while. In the current roadmap I am really interested in contributing via code/ideas to Tekton Artifacts as OCI Artifacts, their provenance (Notary Support maybe ?) and Pipeline Debugging Frameworks …

Add waveywaves (Vibhav Bobade (me)) to the org

---

org/org.yaml

working on pipeline:
[tektoncd/pipeline#2204](https://github.com/tektoncd/pipeline/pull/2204)
[tektoncd/pipeline#2142](https://github.com/tektoncd/pipeline/pull/2142)
[tektoncd/pipeline#2138](https://github.com/tektoncd/pipeline/pull/2138)
[tektoncd/pipeline#2136](https://github.com/tektoncd/pipeline/pull/2136)
[tektoncd/pipeline#1564](https://github.com/tektoncd/pipeline/pull/1564)
[tektoncd/pipeline#1451](https://github.com/tektoncd/pipeline/pull/1451)
[tektoncd/pipeline#1435](https://github.com/tektoncd/pipeline/pull/1435)

Add withlin as a new member

---

org/org.yaml

Adding @savitaashture to tekton org
I will represent @vdemeester and team.

Add savitaashture (Savita Ashture) to the org

---

governance.md

We need to update the content of this doc also, but for now at least update the members with the results of our election!

Update governing board 👩‍⚖️

---

org/org.yaml

This PR adds myself to the org.
I've been regularly contributing on various Tekton repositories.
Currently working on adding helm charts for Tekton components.
Below is the list of my PRs.
Pipeline:
https://github.com/tektoncd/pipeline/pull/2368
https://github.com/tektoncd/pipeline/pull/2260
https://github.com/tektoncd/pipeline/pull/1997
https://github.com/tektoncd/pipeline/pull/1901
https://github.com/tektoncd/pipeline/pull/1853
https://github.com/tektoncd/pipeline/pull/1533
Dashboard:
https://github.com/tektoncd/dashboard/pull/1262
https://github.com/tektoncd/dashboard/pull/1259
https://github.com/tektoncd/dashboard/pull/1172
Plumbing:
https://github.com/tektoncd/plumbing/pull/321
https://github.com/tektoncd/plumbing/pull/305
https://github.com/tektoncd/plumbing/pull/302 …

Add eddycharly to the org

---

org/README.md

We don't actually need to apply anything manually, there is supposed to
be a trigger watching it. Looks like it's off or something right now so
that's the next step!

Fix docs about peribolos

---

working-groups.md

Two changes: 
1. updated time .. we meet at 11am now, no longer at 1pm Eastern. 
2. Added Alan as additional facilitator. 
Probably should also remove Kim as facilitator and fix Serge's github ID.. did not make those updates.

Updated Documentation working group

---

working-groups.md

Adding the working group to our list! More facilitators TBD after our
first meeting.

Add catalog + hub working group 📰

---

roadmap.md

https://github.com/tektoncd/dashboard/issues/1266
@a-roberts fyi

Add link to the dashboard roadmap

---

roadmap.md

Adding a link to the 2020 Roadmap for the CLI.

Add cli Roadmap Link

---

org/org.yaml

I've joined the Tekton team at Google.

add myself as a member to the Tekton org.

---

org/org.yaml

Meixing is an intern on the Tekton team at Google and her name is added in a sorted order.

Add Meixing into the member list

---

org/org.yaml

Ziwei Fang is a 2020 summer intern working on Tekton project

Add yuege01(Ziwei Fang) to Tekton Org

---

org/org.yaml

/assign @dlorenc @bobcatfish @ImJasonH

Add myself and @n3wscott

---

org/org.yaml

Thank yall for letting me join! I'm looking to help however I can.
:metal:
Signed-off-by: JJ Asghar <jjasghar@gmail.com>

Adding myself to be official

---

working-groups.md

Adding the working group to our list! More facilitators TBD after our first meeting.
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

Adding Operator & Deployment Working Group

---

working-groups.md

Update working-groups.md workgroups list
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

Update working-groups.md workgroups list

---

org/org.yaml

I'm Yolanda, a Google summer intern in Tekton team. I want to join the Tekton Github org.

Add YolandaDu1997 to org

---

process.md
teps/0001-tekton-enhancement-proposal-process.md
teps/NNNN-tep-template/README.md

Update process to refer to TEPs

---

org/org.yaml

They'll be collaborating on the tektoncd/chains project.

Add lukehinds, mpeters and font to the org!

---

org/org.yaml

Otherwise, they will loose their power each time we sync the org 👼
/cc @abayer @bobcatfish @afrittoli @ImJasonH 

Add governance member as owners on the org

---

org/org.yaml

Hi, I'm Paul, part of the IBM team working on Tekton. I've started on pipelines and plan to expand out to triggers in the near future.

add psschwei as an org member

---

teps/0003-tekton-catalog-organization.md

/cc @sthaha @bobcatfish 
Depends on #121 to be merged (also #122)

TEP 0003: Tekton Catalog Organization

---

org/org.yaml

I'd love to be able to review some PRs, and this seems to be a prerequisite.

Add jonjohnsonjr as an org member

---

working-groups.md

Signing up for being one of the facilitators to General WG - US friendly time zone 😊 
Notes for reviewer:
* Added one row to the General WG facilitators in the end of the table with my name and other details.
* Updated two rows with Dibyo and Chun-Hung to align table cells without any content updates:
```
| <img width="30px" src="https://github.com/dibyom.png">     | Dibyo Mukherjee | Google  | [dibyom](https://github.com/dibyom)         |
| <img width="30px" src="https://github.com/dibyom.png">     | Dibyo Mukherjee   | Google  | [dibyom](https://github.com/dibyom)         |
```
and
```
| <img width="30px" src="https://github.com/chhsia0.png">     | Chun-Hung Hsiao | D2iQ  | [chhsia0](https://github.com/chhsia0)         |
| <img width="30px" src="https://github.com/chhsia0.png">    | …
```

adding priti as a facilitator to General WG

---

teps/0003-tekton-catalog-organization.md

*  This PR adds an example in the TEP which points to a catalog task describing
-  The structure of yaml
-  Fields required optional and mandatory in yaml while 
submiting a resource

Adds an example in catalog reorg TEP

---

teps/NNNN-tep-template/README.md

Added note under `Design Details` section explaining how to add TEP related images.
/cc @vdemeester @bobcatfish

explaining how to add images

---

teps/0004-task-results-in-final-tasks.md

Changing the status to implementable along with the workflow

changing the status to implementable

---

teps/0007-conditions-beta.md

To make the TEP easier to read

Format Conditions Beta TEP

---

teps/0002-custom-tasks.md
teps/0005-tekton-oci-bundles.md

Also update the title for tep-0002
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

tep-0005: add the TEP header

---

teps/0007-conditions-beta.md

Fixed headings for Conditions Beta TEP

TEP-0007: Fix headings

---

org/org.yaml

Yawen is a new team member in Tekton
/assign @imjasonh

Adding Yawen Luo into membership

---

teps/0012-api-spec.md

[Rendered here](https://github.com/ImJasonH/community/blob/api-spec/teps/0008-api-spec.md)
/assign @bobcatfish 
/assign @vdemeester 
/assign @afrittoli

TEP-0012: API Spec

---

teps/0007-conditions-beta.md

Related: https://github.com/tektoncd/pipeline/issues/2010#issuecomment-674945182
/cc @bobcatfish

Make the deprecation of Conditions CRD more prominent in the TEP

---

teps/0008-support-knative-service-for-triggers-eventlistener-pod.md

Moved TEP to status to **Implementable**
Addressed few open points from `proposed` state PR https://github.com/tektoncd/community/pull/162
1. naming convention as part of this comment https://github.com/tektoncd/community/pull/162#discussion_r467945712
2. How to handle `annotation/labels` as part of this comment https://github.com/tektoncd/community/pull/162#discussion_r467932988
To address this specifically changed a bit in design doc 
1. for kubernetes based deployment lets use [WithPodSpec](https://github.com/knative/pkg/blob/master/apis/duck/v1/podspec_types.go#L49) instead of [WithPod](https://github.com/knative/pkg/blob/master/apis/duck/v1/podspec_types.go#L41) duck type 
because if we use [WithPod](https://github.com/knative/pkg/blob/master/apis/duck/v1/podspec_types.go#L41)  for …

Changed Knative Triggers TEP Status to Implementable and addressed few open points

---

teps/OWNERS

ref: :technologist:
https://github.com/tektoncd/community/blob/master/process.md#requirements
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

Add Khurram Baig khrm to tep/OWNERS

---

working-groups.md

Adding facilitators and removing some others so that we are in sync
with the present.
/cc @bobcatfish @pritidesai @nikhil-thomas @savitaashture @khrm @afrittoli @piyush-garg @pradeepitm12 

working-groups: update table of facilitators

---

org/org.yaml

@yaoxiaoqi Yumeng is joining the Tekton team at Google and she is glad to do some contribution to Tekton.
/assign @dlorenc

Add Yumeng to the org

---

teps/0009-trigger-crd.md

Some minor fixes for typos/grammer for trigger-crd TEP

Some minor fixes for typos/grammer for trigger-crd TEP

---

teps/0007-conditions-beta.md

Proposing the design of When Expressions Status and exploring the alternatives discussed in https://github.com/tektoncd/pipeline/issues/3139
Related TEP: https://github.com/tektoncd/community/pull/159
/cc @pritidesai @bobcatfish

TEP-0007: Add When Expressions Status

---

org/org.yaml

Add xinruzhang to org

---

org/org.yaml

Merged PR in pipeline:
tektoncd/pipeline#3136
tektoncd/pipeline#3093
tektoncd/pipeline#3071
tektoncd/pipeline#2788
tektoncd/pipeline#2776
Unmerged:
tektoncd/pipeline#3223
tektoncd/pipeline#2787

Add FogDong to the org

---

org/org.yaml

I would like to be added to the Tekton org.
For some background: I'm working on Tekton at Google.

add Peaorl to org

---

org/org.yaml

I am working with @afrittoli and @vdemeester on the multi-architecture support, mainly on s390x.
my PRs:
https://github.com/tektoncd/pipeline/pull/3061
https://github.com/tektoncd/pipeline/pull/3107
https://github.com/tektoncd/pipeline/pull/3128
https://github.com/tektoncd/pipeline/pull/3265
https://github.com/tektoncd/pipeline/pull/3299

Add barthy1 to the org

---

teps/0014-step-timeout.md

The work is nearly finished as per [#3087](https://github.com/tektoncd/pipeline/pull/3087) so I think it's time to move to implementable.

Move TEP-0014 Step timeouts to implementable

---

org/org.yaml

I am contributing to pipelines and the experimental repos.

Add GregDritschler to the org

---

teps/0024-embedded-trigger-templates.md

Triggers issue: https://github.com/tektoncd/triggers/issues/616

Add TEP-0024: Embedded Trigger Templates

---

teps/NNNN-tep-template/README.md

Prior to this commit the description of the Requirements section
in TEPs gave limited direction on what to include.
This commit adds a bit more information about what's good to
include as part of the Requirements section.
/kind cleanup

Clarify TEP Requirements Section

---

teps/0027-https-connection-to-triggers-eventlistener.md

This is a Triggers proposal to make secure connection to eventlistener pod.
Issue: https://github.com/tektoncd/triggers/issues/650
/cc @tektoncd/triggers-maintainers @vdemeester

TEP-0027: HTTPS Connection To Triggers EventListener

---

org/org.yaml

I'm working to generate OpenAPI and swagger file for Tekton pipeline(https://github.com/tektoncd/pipeline/pull/3081), and then generate SDK for pipeline (https://github.com/tektoncd/experimental/pull/622).  The effort and changes are huge.
Now I need to join tekton and maintain the Python SDK for tekton. Thanks a lot!

Add jinchihe as memeber

---

teps/0025-hermekton.md

Also add some more detail on proposed design.

Mark the Hermekton TEP as implementable.

---

hack/tep-number.sh
teps/README.md

Until we automate this https://github.com/tektoncd/community/issues/178
provide guidelines to handle TEP numbers and avoid confusion / churn.
/cc @vdemeester @ImJasonH @bobcatfish @abayer

Add notes about TEP numbers

---

hack/teps.py
teps/README.md

Update the TEP table and fix an issue in the script.
Until we have more automation in place, the table have to be
manually updated .
/kind documentation

Update the TEP table

---

teps/XXXX-workspace-paths.md

This commit introduces a new TEP for a feature tentatively called "Workspace Paths". This commit only includes the problem statement for the issue we're trying to solve.
Included here are the motivation, goals, non-goals, user-stories and a reference section.

TEP: Workspace Paths

---

teps/NNNN-tep-template/README.md

added design evaluation to the tep template in https://github.com/tektoncd/community/pull/241 but forgot to add it to the table of contents 🙃

Add Design Evaluation to TEP template table of contents

---

teps/0016-concise-trigger-bindings.md
teps/0024-embedded-trigger-templates.md

Both concise TriggerBindings and embedded TriggerTemplates have been
implemented.

Mark TEP-0016 and TEP-0024 as implemented.

---

org/org.yaml

Mainly for work on experimental/results. See https://github.com/tektoncd/experimental/pull/661

Add myself to experimental.collaborators

---

teps/0027-https-connection-to-triggers-eventlistener.md

Moved TEP to Implementable state
PR: https://github.com/tektoncd/triggers/pull/819
/cc @dibyom @vdemeester

Change status of TEP-0027 to Implementable

---

teps/0031-tekton-bundles-cli.md
teps/README.md

This TEP proposes additions to the Tekton CLI to support building and managing Tekton Bundles.

TEP-0031: Tekton Bundles CLI

---

teps/0004-task-results-in-final-tasks.md
teps/README.md

Updating proposal based on the discussion to include the finally task in a the list of skippedTasks if a result is not initialized when finally tasks are scheduled.

TEP 0004- task results in finally - updating proposal

---

teps/0021-results-api.md

- Renames Event -> Record based on feedback (still has the same intent)
- Breaks Records out as a subresource of Results to allow for pagination
and finer grained access.
/cc @afrittoli

TEP-0021 Result API: Record Subresources

---

org/org.yaml

Adds Piyush and Vinamra as the members of the hub

---

teps/0021-results-api.md
teps/README.md

TEP-0021 Results API: Mark TEP as implementable.

---

org/org.yaml

to be added as a tektoncd/catalog kn-apply task owner
cc: @rhuss

Add rhuss to tektoncd org members

---

org/org.yaml

/cc @afrittoli @nikhil-thomas 

org: add savita and pradeep to operator collaborators

---

process.md

Since tektoncd/results is still a fairly new project, we're planning to follow the simpler OWNER process for the time being in order to onboard more OWNERS to distribute reviews.
Also reorders list alphabetically.

Add tektoncd/results to simple OWNER requirements list.

---

user-profiles.md

I missed a couple pieces of feedback from @sbwsg: a typo and also a
comment about folks who may want to conform to the Tekton API but not
use the same implementation. I'm not sure I've fully captured that here
but hopefully it's a start?
/assign @sbwsg

Improve user profiles 🧹

---

org/org.yaml

@savitaashture was added to Triggers OWNERS so should be part of the maintainers team

Add @savitaashture to triggers.maintainers

---

teps/0031-tekton-bundles-cli.md
teps/README.md

Fleshes out the developer experience and design of the Tekton Bundles CLI tep and marks it as implementable.

0031-tekton-bundles-cli design + implementable

---

teps/README.md

created from discussion in https://github.com/tektoncd/community/pull/319#issuecomment-769930252 to fix existing linting issue before merging that change.

fix linting for TEP-0037

---

org/org.yaml

Add a new member of the OWNERS list in catalog, I wanted to
add myself to the catalog.maintainers group in the community.
/cc @vdemeester @bobcatfish @chmouel @sbwsg

Adding myself to the catalog.maintainers list

---

process.md

Add the collaborator role along with the requirements to obtain the
collabortator status.

Add the collaborators role to the community docs

---

teps/0052-tekton-results-automated-run-resource-cleanup.md
teps/README.md

This proposal details a solution to provide automatic TaskRun/PipelineRun
resource clean up in conjunction with Tekton Results to preserve long term
history while minimizing the footprint of data the Pipeline controller needs to
keep track of.
https://github.com/tektoncd/results/issues/59

TEP-0052: Tekton Results: Automated Run Resource Cleanup

---

org/org.yaml

Signed-off-by: rudeigerc <rudeigerc@gmail.com>
I have been contributing to tektoncd/cli and other repos actively. 😃
> https://github.com/search?q=org%3Atektoncd+is%3Apr+author%3Arudeigerc
Merged:
- tektoncd/cli#1117
- tektoncd/cli#1123
- tektoncd/cli#1138
- tektoncd/dashboard#1924
- tektoncd/triggers#935
- tektoncd/catalog#651
In review:
- tektoncd/cli#1291
- tektoncd/cli#1296

Add @rudeigerc to the org

---

governance.md

Was renamed to adjust permissions
Fixes #358

Fix link to add permissions script 🔗

---

teps/0053-nested-triggers.md
teps/README.md

@wlynch @bigkevmcd @dibyom as discussed in the Triggers WG today, created an outline of a TEP proposal with some of the problem statement and our proposed solution.

Nested Triggers proposal

---

org/org.yaml

I'd like to start help lgtm'ing PRs to the results project. I've only just
started contributing to it but given its early stage would like to help
move along PRs.
I've so far contributed some very small fixes which have been merged:
- https://github.com/tektoncd/results/pull/96
- https://github.com/tektoncd/results/pull/95
- https://github.com/tektoncd/results/pull/88
and am working on getting a new feature into a mergeable state here:
- https://github.com/tektoncd/results/pull/87
/cc @wlynch @dibyom @ImJasonH

Add sbwsg for lgtm on results PRs

---

org/org.yaml

This PR adds myself to the list of collaborators for the Tekton catalog

Add spikeburton to catalog collaborators

---

org/README.md

Belonging to the org grants automatic "ok-to-test" and ability
to assign issues, but no "lgtm"

Fix the org README

---

roadmap.md

This updates any reference of cli repository to target the
/hold

Update cli reference from master to main 🧙

---

teps/0052-tekton-results-automated-run-resource-cleanup.md
teps/README.md

This revises the TEP status to implementable. There is no change in content.

TEP-0052: Automated RunResource Cleanup - Mark proposal as implementable

---

teps/0042-taskrun-breakpoint-on-failure.md

Add user story surrounding CLI usage and the considered
alternatives for the API format including the unused formats and some
of their pitfalls.
Created as a followup of https://github.com/tektoncd/community/pull/308#issuecomment-802056087
cc @bobcatfish @vdemeester

update: tep-0042 user stories and alternatives

---

teps/0058-graceful-pipeline-run-termination.md
teps/README.md

This TEP aims to address issue with lack of a graceful `PipelineRun` termination.

TEP-0058: Graceful Pipeline Run Termination

---

teps/0056-pipelines-in-pipelines.md
teps/README.md

This PR describes the motivation and use cases for composing 
and executing Pipelines in Pipelines. 
The feature would help resolve reusability, composability and 
failure strategies issues in Pipelines.
References:
- [Issue](https://github.com/tektoncd/pipeline/issues/2134)
- [Project Proposal](https://github.com/tektoncd/community/issues/330)
- [Experimental Project](https://github.com/tektoncd/experimental/tree/main/pipelines-in-pipelines)
- [Original Proposal](https://docs.google.com/document/d/14Uf7XQEnkMFBpNYRZiwo4dwRfW6do--m3yPhXHx4ybk/edit)

TEP-0056: Pipelines in Pipelines

---

org/org.yaml

Add mpeddada1 from Jib to tektoncd org

---

working-groups.md

Remove @sergetron as docs WG facilitator.

Remove @sergetron

---

teps/0061-allow-custom-task-to-be-embedded-in-pipeline.md

Added details for proposal and an example.
One of the consideration of this proposal is: https://github.com/tektoncd/experimental/pull/730#discussion_r615896845
/cc @Tomcli @ImJasonH @vdemeester @sbwsg @pritidesai @afrittoli

TEP-0061 Allow custom task to be embedded in pipeline, proposal.

---

org/org.yaml

Hey everyone! I've been working on chains recently, and am hoping to release v0.1.0 sometime next week. Some PRs I've merged recently/reviewed:
- https://github.com/tektoncd/plumbing/pull/828
- https://github.com/tektoncd/chains/pull/70
- https://github.com/tektoncd/chains/pull/67
- https://github.com/tektoncd/chains/pull/66
cc @dlorenc

Add priyawadhwa@ to the org and as a chains maintainer

---

org/org.yaml

Remove old nick that is not part of the org anymore.

Fix the org file

---

teps/0058-graceful-pipeline-run-termination.md
teps/README.md

Design details for already accepted proposal: https://github.com/tektoncd/community/pull/384
PoC: https://github.com/rafalbigaj/pipeline/commit/ae5b2b6fe71fa2b244918a3ef8edf2a772393574
/cc @afrittoli @pritidesai

TEP-0058 Graceful Pipeline Run Termination - design details

---

teps/README.md
teps/README.md.mustache
teps/tools/teps.py

MInor change to teps template
- cherry-picks https://github.com/tektoncd/community/pull/315
- makes a minor fix in tep template

Minor fix to tep template

---

org/org.yaml

I've just joined a team with @AlanGreene in IBM and will be contributing to the Dashboard

add LyndseyBu as member and dashboard collaborator

---

org/org.yaml

[mrutkows](https://github.com/mrutkows) has recently made major contribution to `DEVELOPMENT.md` doc (PR https://github.com/tektoncd/pipeline/pull/3955). He organized the entire doc with an easy to follow instructions. And he continues to contribute with additional [PRs](https://github.com/tektoncd/pipeline/pull/3972) to the DEVELOPMENT and CONTRIBUTING docs.
Welcome Matt 🎉

adding mrutkows to the org

---

org/org.yaml

Add myself to the ORG !

---

roadmap.md

Signed-off-by: shaowenchen <mail@chenshaowen.com>

fix: readme desc

---

code-of-conduct.md

Signed-off-by: shaowenchen <mail@chenshaowen.com>

improvement: redirect link

---

teps/0061-allow-custom-task-to-be-embedded-in-pipeline.md
teps/README.md

Also included the changes that were agreed on during PR
reviews.
/cc @sbwsg @pritidesai

Update the TEP-61 to implemented

---

teps/0067-tekton-catalog-pipeline-organization.md
teps/README.md

- With the acceptance of Tekton Catalog Orgranization for tasks,
this TEP proposes the design and structure for organization of
pipelines in Tekton Catalog

TEP- 0067 Tekton Catalog Pipeline Organization

---

teps/0004-task-results-in-final-tasks.md
teps/README.md

It was implemented in https://github.com/tektoncd/pipeline/pull/3242
/kind cleanup
/cc @pritidesai

TEP-0004: Task Results in Final Tasks - Mark as Implemented

---

teps/0028-task-execution-status-at-runtime.md
teps/README.md

Implemented in https://github.com/tektoncd/pipeline/pull/3390
/kind cleanup
/cc @pritidesai

TEP-0028: Task Execution Status at Runtime - Mark as Implemented

---

teps/0049-aggregate-status-of-dag-tasks.md
teps/README.md

Implemented in https://github.com/tektoncd/pipeline/pull/3817
And update table of contents 
/kind cleanup
/cc @pritidesai

TEP-0049: Aggregate Status of DAG Tasks - Mark as Implemented

---

working-groups.md

Add details about Chains WG to working-groups doc

---

.github/PULL_REQUEST_TEMPLATE/free-form.md
.github/PULL_REQUEST_TEMPLATE/tep.md

This adds two pull-request template.
- free form (for any type of pull-request)
- tep for TEPs, that would set the correct kind directly
We can go further and have a template for adding a member to the org, …
/cc @afrittoli @bobcatfish 

Add pull-request template 🙃

---

teps/0066-dogfooding-tekton.md
teps/README.md

Add a TEP about the dogfooding work.

TEP-0066 Tekton Dogfooding

---

org/org.yaml

So I am able to test the tekton tasks. Expecting to add a lot more because we're adopting Tekton in our organization.

Add myself

---

teps/0070-tekton-catalog-task-platform-support.md
teps/README.md

This TEP proposes to add information about supported operating systems/hardware architectures (platforms) to the Tekton catalog resources and provide ability to the user to filter/search resources from the catalog for specific platform.
Initial discussion was started at https://github.com/tektoncd/catalog/issues/661

TEP-0070: Platform support in Tekton catalog

---

teps/0062-catalog-tags-and-hub-categories-management.md
teps/README.md

Update Catalog Tags and Hub Category Management TEP status

---

teps/0062-catalog-tags-and-hub-categories-management.md

- From `tekton.dev/category` to `tekton.dev/categories`

Updates minor change in annotation

---

README.md

Signed-off-by: shaowenchen <mail@chenshaowen.com>

fix: readme anchor

---

org/org.yaml

hi, I am developing a CICD system based on Tekton for wps.com.  I love open-source projects and want to contribute more.
Here is the pull request I submitted:
https://github.com/tektoncd/community/pulls?q=is%3Apr+author%3Ashaowenchen
https://github.com/tektoncd/website/pulls?q=is%3Apr+author%3Ashaowenchen
In the https://github.com/tektoncd/catalog/pull/743, @vinamra28 suggests I join the org for a better workflow. 
Signed-off-by: shaowenchen <mail@chenshaowen.com>

Add shaowenchen to the org

---

teps/0060-remote-resource-resolution.md
teps/README.md

This commit lists some different ways tekton could approach supporting
remote resource resolution (incl. not supporting it at all).
No change to the status of the TEP itself, just recording possibile
approaches. Please comment with more if you think of them.

Add Alternatives for Remote Resource Resolution TEP

---

teps/0072-results-json-serialized-records.md
teps/README.md

This proposal outlines changes we would like to make to the Record type
to better support more types and allow us to use Tekton types directly
without needing to generate a separate proto type.

TEP-0072: Results: JSON Serialized Records [proposed]

---

teps/0040-ignore-step-errors.md

Correcting the field name in the proposal and adding instructions on how to access step exit code of a step without a step name.
/kind tep

TEP-0040 - minor corrections

---

teps/0050-ignore-task-failures.md

Adding some more detail to an existing requirement - I think I'm
capturing the original intention but removing some ambiguity.
@jerop and I were discussing this feature today and when I looked at
this requirement I realized I was making some assumptions which weren't
captured here.
@pritidesai @skaegi plz let me know if I jumped to the wrong
conclusion!
/kind tep

[TEP-0050] Clarify impact on overall pipeline status 📜

---

working-groups.md

In the last API working group, @chhsia0 mentioned that he'd like to step
back from faciltiating working groups so this commit removes him from
the rotations.
Thanks for your hard work @chhsia0!! ❤️ ❤️ ❤️
p.s. @chhsia0 if I misunderstood and you wanted to stay on the list just lemme know! 🙏

Remove @chhsia0 from facilitator list for now ❤️

---

org/org.yaml

Added myself to the org, based on the suggestion in this PR: https://github.com/tektoncd/catalog/pull/788

Add frerikandriessen to the org

---

teps/0023-implicit-mapping.md
teps/README.md

There were no outstanding comments in
https://github.com/tektoncd/community/pull/444, so going ahead with
marking this as implementable as-is.

TEP-0023: Implicit Params - mark as implementable.

---

working-groups.md

Add @vinamra28 as CLI WG facilitator

---

teps/0072-results-json-serialized-records.md
teps/README.md

Marks TEP as implementable, with some minor edits for clarity.

TEP-0072 Results JSON Serialized Records: Mark as implementable.

---

org/org.yaml

@sm43 has been contributing to Triggers for a while now!

Add @sm43 as a Triggers collaborator

---

teps/0057-windows-support.md

Added some details about work that was done in Tekton (and ko) in order
to support windows nodes and workloads.
Also added some notes on eventual testing requirements.

Add design and test details to TEP0057

---

working-groups.md

Add Workflows Working Group list of WGs

---

working-groups.md

Also fixes links to meeting notes docs and slack channel name

Add Workflows WG facilitators

---

org/org.yaml

Added myself to the org, based on the suggestion in this PR: tektoncd/catalog#788

Add mooyeg to the org

---

org/org.yaml

I'm planning on doing some work in the org and as suggested by the helpful robot, I should add myself to the org.

Add vaikas to org

---

teps/0080-support-domainscoped-parameterresult-names.md
teps/README.md

Move TEP-0080 to implemented

---

teps/0081-add-chains-subcommand-to-the-cli.md
teps/README.md

Adds a new TEP to propose to add a CLI command for Chains.

TEP-0081: Add Chains sub-command to the CLI

---

teps/0069-support-retries-for-custom-task-in-a-pipeline.md

Previously, the proposal had lot of changes to tekton controller.
After updating the proposal to "let the custom controller do the hard work",
the new approach does not require the same test plan as before.

TEP-0069: Update the test plan.

---

README.md
teps/0088-result-summaries.md
teps/README.md

This TEP is a problem statement for introducing Record summaries to
Results in order to bubble up common/overall Result information without
needing to derive it from the underlying Records.
For now this TEP is only focusing on the problem statement to solicit
ideas. Detailed proposal to come in another PR.
This is still early - we are looking for additional feedback / suggestions!

TEP-0088: Tekton Results - Record Summaries

---

working-groups.md

A couple of folks on the rotation have asked to be removed for now, so updating the list to reflect that.

Update alternate WG facilitator rotation

---

teps/0012-api-spec.md
teps/README.md

Tekton now has an API spec and conformance tests for TaskRun.
We may want to add conformance docs and tests for other parts of the Tekton API,
but the foundation has been laid for adding these later,
and this work can be tracked through Github issues instead of leaving this TEP open.
/kind tep
/assign imjasonh

[TEP-0012]: Mark as implemented

---

teps/0023-implicit-mapping.md
teps/README.md

cc @wlynch for confirmation, but https://github.com/tektoncd/pipeline/pull/4127 is merged, so I'm assuming. =)

TEP-0023: Mark as implemented

---

teps/0002-custom-tasks.md
teps/README.md

TEP-0002: Mark as implemented

---

teps/0058-graceful-pipeline-run-termination.md
teps/README.md

cc @rafalbigaj for confirmation

TEP-0058: Mark as implemented

---

teps/0062-catalog-tags-and-hub-categories-management.md
teps/README.md

https://github.com/tektoncd/catalog/pull/658 was merged a while back
cc @PuneetPunamiya for confirmation

TEP-0062: Mark as implemented

---

org/org.yaml

Added me to the org, based on the suggestion in this PR: https://github.com/tektoncd/catalog/pull/855#pullrequestreview-809464737

Added myself to org

---

teps/0096-pipelines-v1-api.md
teps/README.md

This TEP adds use cases for Tekton and criteria for scoping what work should and should not be prioritized for inclusion in a V1 API. It also adds a stability policy for metrics.
Specific features, and whether they will be in scope for V1, will be proposed in a subsequent commit.
Co-authored-by: Jerop Kipruto jerop@google.com @jerop 
Co-authored-by: Priti Desai pdesai@us.ibm.com @pritidesai 
/kind tep

[TEP-0096]: Pipelines V1 Scope

---

teps/0005-tekton-oci-bundles.md
teps/README.md

cc @vdemeester for confirmation

TEP-0005: Mark as implemented

---

teps/0079-tekton-catalog-support-tiers.md
teps/README.md

This change adds the problem statement for Support Tiers in the Tekton
Catalog - we will explore the proposal in further changes.
The aim of this TEP is to establish support tiers for resources in the
Tekton Catalog to ensure users get high quality resources that they can
rely on while making it easy for contributors to submit resources to the
Tekton Catalog.
The goals of the TEP are to address the following aspects of the Tekton
Catalog:
- Ownership and Maintenance
- Automated Testing and Dogfooding
- Image Scanning for Common Vulnerabilities and Exposures (CVEs)
- Verified Remote Resources
/cc co-authors @vinamra28 @vdemeester @bobcatfish
/kind tep
Related PRs: 
- https://github.com/tektoncd/community/pull/494
- https://github.com/tektoncd/community/pull/170

TEP-0079: Tekton Catalog Support Tiers [Problem Statement] 

---

teps/0090-matrix.md

I think the more generic term applies, will make the case for this TEP stronger and will help more people find it.

[TEP-0090]: Renaming docker use case to "Monorepo".

---

org/org.yaml

I've been in OWNERS for 6 months: https://github.com/tektoncd/chains/commit/a17c83748773c7aa06e2ee9db242c0cf5c856507
cc @priyawadhwa @dlorenc

Add myself as a Chains collaborator

---

org/org.yaml

I have been contributing to tektoncd/pipeline for about 3 months, with 12 merged and 14 total PRs,
17 review comments and 62 issue comments, as evidenced by the devstats dashboard.

Add lbernick to Pipeline collaborators

---

org/org.yaml

PR #920 in the tektonccd/catalog repo has been raised to add a Gradle task which I am offering to be the OWNER for. This PR is to add myself to the Org to allow this to happen as requested in the review comments on that PR.

Add crshnburn to Org

---

teps/0089-nonfalsifiable-provenance-support.md

Added a bit more detail about SPIRE, and also added a couple more details based on all the heavy lifting @pxp928 is doing!
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

Add some more SPIRE details to TEP0089

---

org/org.yaml

Gives me /lgtm and /ok-to-test to help with reviewing. 🙏 
/cc @priyawadhwa

Add wlynch to chains.collaborators

---

teps/0073-simplify-metrics.md
teps/README.md

This TEP was implemented by the pr https://github.com/tektoncd/pipeline/pull/4201

Change status of TEP0073 to implemented

---

teps/0044-data-locality-and-pod-overhead-in-pipelines.md
teps/README.md

This commit proposes using Pipeline in a Pod to address TEP-0044,
and adds implementation milestones for features that should be supported in a pod.
Additional design details will be added in a subsequent commit.

[TEP-0044]: Propose pipeline in pod + rollout plan

---

governance.md

Ref: https://groups.google.com/g/tekton-dev/c/DMFYxgjDpto

Update gov board with new members

---

teps/0096-pipelines-v1-api.md
teps/README.md

This commit marks TEP-0096 as implementable, as concerns about ClusterTasks and PipelineResources
have been resolved.
/kind tep

[TEP-0096]: Update to implementable

---

org/org.yaml

For the new repository : https://github.com/tektoncd/catlin
See https://github.com/tektoncd/community/issues/636

org.yaml: add catlin teams

---

org/org.yaml

As a new joiner in Google's Tekton team, my membership is endorsed by existing contributors.

---

org/org.yaml

Based on the [requirements](https://github.com/tektoncd/community/blob/main/process.md#reviewer)
in our contributor ladder, I am eligible to be a "reviewer" in the community repo based on my
nomination from an OWNER of another Tekton project.

Add Lee Bernick to community collaborators

---

teps/tools/tep-template.md.template

In this change, we update the TEPs template:
- Add questions that collaborators on a TEP should consider
to meet our design goals
- Reorganize the template to bring related sections together
- Fix typos and make other editorial changes
Co-authored-by: Christie Wilson <christiewilson@google.com>
cc @bobcatfish

Update TEPs template

---

working-groups.md

I'll be on leave until later this year, so removing myself from the
facilitator rotations - will re-add myself when I return :)

Temporarily remove myself as facilitator from working groups 🏖️

---

teps/0089-nonfalsifiable-provenance-support.md
teps/README.md

Signed-off-by: Brandon Lum <lumjjb@gmail.com>

[TEP-0089] Update TEP-0089 to implementable

---

teps/0100-embedded-taskruns-and-runs-status-in-pipelineruns.md
teps/README.md

Mark TEP-0100 as implemented

---

teps/0102-https-connection-to-triggers-interceptor.md
teps/README.md

@dibyom Updated design detail a bit 
PTAL
PR: https://github.com/tektoncd/triggers/pull/1333
Thank you

[TEP-0102] Mark as implementable with some design details update

---

teps/0081-add-chains-subcommand-to-the-cli.md
teps/README.md

Updates the status of TEP 0081 which was implemented on March 3rd 2022.

Update TEP 0081 status

---

org/org.yaml

Follow up to https://github.com/tektoncd/resolution/pull/52

Add @chitrangpatel to resolution maintainers

---

teps/0106-support-specifying-metadata-per-task-in-runtime.md
teps/README.md

/kind misc
Update status as "implementable" as the implementation is under review now.
Implementation PR: [here](https://github.com/tektoncd/pipeline/pull/4834)

Update TEP-0106 Status as Implementable

---

teps/0107-propagating-parameters.md
teps/README.md

Marking TEP-0107 as implemented, thank you @chitrangpatel!
Pull Requests:
- https://github.com/tektoncd/pipeline/pull/4906
- https://github.com/tektoncd/pipeline/pull/4845

TEP-0107: Propagating Parameters - Implemented

---

teps/0108-mapping-workspaces.md
teps/README.md

Marking TEP-0108 as implemented, thank you @Aleromerog!
PR: https://github.com/tektoncd/pipeline/pull/4887

TEP-0108: Mapping Workspaces - Implemented

---

process.md

Update the reviewer links as the previous ones are outdated.

Update reviewer links

---

teps/0111-propagating-workspaces.md
teps/README.md

`Tekton Pipelines` resources can be quite verbose because of explicitly propagating `Workspaces`. This proposal aims to propagate `Workspaces` to improve usability of `Tekton Pipelines`.

TEP-0111 - Propagating Workspaces.

---

working-groups.md

@skaegi has decided to take a pause facilitating API (US) and General WG for now. He will still continue facilitating alternate API WG. Thank you Simon for facilitating, you will be missed!
Adding @jerop as a facilitator to API and General WG. Welcome Jerop! Jerop has been facilitating API WG but was not listed in the repo.

updating facilitators for API and General WG

---

teps/OWNERS

@abayer was added as pipelines owner, so this makes him an owner here as well

add @abayer to TEP owners

---

teps/0110-decouple-catalog-organization-and-reference.md
teps/README.md

In this change, we mark TEP-0110 as implemented and add references to the pull requests.
Many thanks to @austinzhao-go and @Aleromerog for the implementation 🎉 
/kind tep

TEP-0110: Mark as Implemented

---

teps/0056-pipelines-in-pipelines.md
teps/README.md

In this change, we flesh out the design details of Pipelines in Pipelines - how it'd work with other features.
/kind tep

TEP-0056: Pipelines in Pipelines - Design

---

teps/0101-env-in-pod-template.md
teps/README.md

More details has been added in TEP regarding the examples,
api changes, precedence order etc
Structure has been refactored a bit and added few open
question can be discussed and resolved.

Improve TEP for Env in Pod Template

---

org/org.yaml

I am a new joinee to the Google Tekton team.

Add jagathprakash to tekton members.

---

teps/0114-custom-tasks-beta.md
teps/README.md

[TEP-0002: Custom Tasks][tep-0002] introduced `Custom Tasks` which allow users to extend the functionality of Tekton. 
The aim of this TEP is to promote `Custom Tasks` from alpha to beta.
/kind tep
[tep-0002]: https://github.com/tektoncd/community/blob/main/teps/0002-custom-tasks.md

TEP-0114: Custom Tasks Beta

---

teps/README.md
teps/README.md.mustache

updated argument to reflect renumber of a TEP

Update argument to renumber TEP

---

teps/0029-step-workspaces.md
teps/README.md

This commit adds implementation pull requests for TEP-0029.
/kind tep

[TEP-0029] Mark as implemented

---

org/org.yaml

Add wlynch to chains.maintainer.

---

teps/0048-task-results-without-results.md
teps/README.md

This proposes the design as how the `Results` will look like when we
want to declare the `optional` value for them.
Signed-off-by: vinamra28 <jvinamra776@gmail.com>

[TEP-0048] Add Proposed design details

---

org/org.yaml

resolve https://github.com/tektoncd/community/issues/773

add arhell to tektoncd members

---

teps/0116-referencing-finally-task-results-in-pipeline-results.md
teps/README.md

TEP-0116 has been implemented.
The status has changed from `implementable` to 
`implemented`.

[TEP-0116] implemented

---

teps/0084-endtoend-provenance-collection.md

This PR addresses the following sections for pipelinerun attestations:
* Proposal: attestation example
* Notes/Caveats
* Risks and Mitigations
* User Experience
* Performance
* Test Plan
* Design Evaluation
* Drawbacks
* Alternatives
It also removes some of the comments from the template that have already been addressed. 
A few typos have also been fixed.

TEP-0084: Add remaining sections for pipelinerun attestations 

---

teps/0116-referencing-finally-task-results-in-pipeline-results.md

Added more references to the TEP

Added implementation pull request and issues

---

teps/0086-changing-the-way-result-parameters-are-stored.md

This adds high level details about the OIDC Storage API that's been
discussed in WGs (and in various places in this doc already). This is
not intended to be a comprehensive design. API definitions, what storage
backend to use for the default impl, whether to support remote result
references, etc are intentionally not covered - we should be able to
adapt this design to whatever decision we eventually make.
Signed-off-by: Billy Lynch <billy@chainguard.dev>

[TEP-0086] Add details for OIDC Storage API

---

teps/0084-endtoend-provenance-collection.md
teps/README.md

Updating TEP-0084 to the implementable state.

TEP-0084: Move to implementable state

---

LICENSE
governance.md
hack/tep-number.sh
hack/update-toc.sh
org/collaborator.py
teps/0033-tekton-feature-gates.md
teps/0037-remove-gcs-fetcher.md
teps/0067-tekton-catalog-pipeline-organization.md
teps/0075-object-param-and-result-types.md
teps/tools/Dockerfile
teps/tools/teps.py

resolve https://github.com/tektoncd/community/issues/781

update links from http to https

---

teps/0117-tekton-results-logs.md
teps/README.md

This TEP extends Tekton Results to support the storage and retrieval of
`TaskRun` logs.

TEP-0117: Tekton Results Logs

---

teps/README.md
teps/README.md.mustache
teps/tools/README.md
teps/tools/teps.py

This commit adds the ability to specify "collaborators" for a TEP.
The intention of this commit is to recognize the efforts of contributors
who take the time to review and understand a proposed design, or contributors
who may have worked on part of the design but are not owners of the
entire design.

[TEP Process] Add "Collaborators" option

---

teps/0075-object-param-and-result-types.md

related to https://github.com/tektoncd/pipeline/pull/5427.
Prior to this update, merge behaviour was not allowed between `default` and run level value for object keys.
In this [proposal](https://github.com/tektoncd/pipeline/issues/5270) and the implementation pr https://github.com/tektoncd/pipeline/pull/5427, we allow the merge behaviour to happen to in order to give users more flexible ways to provide values for object param as long as all keys are provided with a value at runtime (combination of the values provided from default and run level value).
Signed-off-by: Chuang Wang <chuangw@google.com>

TEP-0075: More flexible ways to provide values for object param

---

teps/0111-propagating-workspaces.md
teps/README.md

In this change, we mark TEP-0111 as implemented - many thanks to @chitrangpatel! 
[Implementation Pull Requests](https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+TEP-0111+)

TEP-0111: Propagated Workspaces - Mark as Implemented

---

org/org.yaml

adding as owner of new tasks in https://github.com/tektoncd/catalog/pull/1069

add dlbewley to tektoncd org

---

teps/0091-trusted-resources.md
teps/README.md

This commit converts tep-0091 to implementable by adding more details
into implementation, proposing solutions to undetermined topics.

[TEP-0091]Update TEP-0091 to implementable

---

org/org.yaml

Working on tekton components for multi arch support.

add basavaraju the tektoncd org

---

standards.md

Adding details on how to write a release note. Also provided a couple of samples of good and bad release notes.

introducing a new section in standards - release notes

---

teps/0109-better-structured-provenance-retrieval-in-tekton-chains.md
teps/README.md

Finalize the discussions and reviews regarding to support structured results and params in Tekton Chains.
The original PR was here: https://github.com/tektoncd/community/pull/697 but the merging issue closed the original thread.
I'm reopening it in this PR.

TEP 0109: Better structured provenance retrieval in Tekton Chains

---

roadmap.md

Add proposal around a Project-based roadmap.
This is the first step in addressing https://github.com/tektoncd/community/issues/814
This PR is now `Ready to Review`; proposed review process:

Update Roadmap section.

---

.gitignore
process.md

As discussed in the community WG https://docs.google.com/document/d/1g2HQk_4ypYEWPX2WjOFa6vOMpwYoRNprph_P09TS1UM/edit#bookmark=id.ah9xcugcwqmk add best practices for pull requests affiliation diversity in the Tekton community.
Each project may define their own policy derived from these best practices and adapted to the needs of the specific Tekton project.

Add pull request best practices

---

org/org.yaml

I am involved with the experimental projects pipeline-in-pod, concurrency, and workflows, and should be able to LGTM PRs in experimental.

Add lbernick to experimental collaborators

---

README.md
adopters.md

Add an adopters file where open source projects, vendores and users can tell the community about their involvement with Tekton.
Partially fixes: #804

Add initial adopters file

---

adopters.md

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

Add VSCode and JetBrains IDEs tooling

---

org/org.yaml

org: update with recent catalog/pipeline owner updates

---

adopters.md

I lifted the copy from cloud.google.com/tekton.

Add Google to Vendors table

---

teps/0060-remote-resource-resolution.md
teps/README.md

This commit adds implementation PRs for remote resolution.
/kind tep

[TEP-0060] Mark as implemented

---

teps/0117-tekton-results-logs.md
teps/README.md

Mark TEP-0117 as implementable. The work in
https://github.com/tektoncd/results/pull/258 proves that the design in the TEP is feasible.

TEP-0117: Mark `implementable`

---

org/org.yaml

Needed to grant access to dependabot alerts, protected branch configs, etc.
/cc @priyawadhwa

Add chains.admin group.

---

teps/0098-workflows.md
teps/README.md

This commit updates the Workflows problem statement to reflect updated goals of the project, adding more detailed use cases and references to related projects or designs. In particular, Remote Resolution has been implemented since this TEP was created, so referencing Pipelines and Tasks from version control is less relevant to the TEP now. It also adds detail on extensibility and conformance goals.
/kind tep

[TEP-0098] Update Problem Statement

---

teps/0125-add-credential-filter-to-entrypoint-logger.md
teps/README.md

Hi,
while working on a pull request regarding credentials filtering we came to the conclusion that a TEP for this feature would make sense.
https://github.com/tektoncd/pipeline/pull/4837
Therefore I added a TEP for this.

add TEP for credentials filter

---

governance.md

I just realized there was a typo in my name in the governance
document. So fixing it :)

governance.md: fix a type in my name

---

teps/0086-changing-the-way-result-parameters-are-stored.md

Update PVC/workspace result passing details with new POC.

[TEP-0086] Update PVC/workspace result passing POC

---

OWNERS
governance.md
org/org.yaml
working-groups.md

thank you and congrats @wlynch !! 🥳 
Signed-off-by: Priya Wadhwa <priya@chainguard.dev>

Add wlynch to the governing board while priyawadhwa is out on leave

---

design-principles.md

This design principle addresses the point to reduce new feature flags where possible.

Avoid feature flags that change behavior of tasks/pipelines.

---

adopters.md

Add Nubank to the end users section.

Add Nubank as one of the Tekton adopters

---

teps/0101-env-in-pod-template.md
teps/README.md

Marking the TEP as implementable.
Implementation PR is available for review : https://github.com/tektoncd/pipeline/pull/5699

TEP-0101: Mark as implementable.

---

teps/0121-refine-retries-for-taskruns-and-customruns.md
teps/README.md

TEP-0121 is implemented by:
- https://github.com/tektoncd/pipeline/pull/5842
- https://github.com/tektoncd/pipeline/pull/5853
- https://github.com/tektoncd/pipeline/pull/5844

Mark TEP-0121 As Implemented

---

teps/0009-trigger-crd.md
teps/README.md

This commit adds implementation pull requests for TEP-0009.
/kind tep

[TEP-0009] Mark as implemented

---

standards.md

The Go team recently published a style guide. I'd like to propose adding this style guide to our code standards for reference in code reviews.

Add Go style guide to community standards

---

teps/0023-implicit-mapping.md
teps/0062-catalog-tags-and-hub-categories-management.md
teps/0067-tekton-catalog-pipeline-organization.md
teps/0070-tekton-catalog-task-platform-support.md

This commit runs ./hack/update-toc.sh.
/kind tep

Clean up TEP TOCs

---

teps/0026-interceptor-plugins.md
teps/README.md

This commit adds implementation pull requests for TEP-0026.
/kind tep

[TEP-0026]: Mark as implemented

---

teps/0022-trigger-immutable-input.md
teps/README.md

This commit adds implementation PRs for TEP-0022.
/kind tep

[TEP-0022]: Mark as Implemented

---

working-groups.md

Volunteer to facilitate Pipeline and API WG.

Volunteer to facilitate Pipeline and API WG

---

teps/0102-https-connection-to-triggers-interceptor.md
teps/README.md

This commit adds implementation pull requests for TEP-0102.
/kind tep

[TEP-0102] Mark as implemented

---

teps/0039-add-variable-retries-and-retrycount.md
teps/README.md

This commit adds implementation pull requests for TEP-0039.
/kind tep

[TEP-0039] Mark as implemented

---

process.md

- Added TOC link to header
- Tweaked language in "goals" section to lead with affirmative goals of postmortem
/kind documentation
/assign lbernick

Updated postmortem section

---

working-groups.md

(They were already facilitating WGs, this commit just updates the repo)

Add Jerome and Lee as API WG facilitators

---

org/org.yaml

As a new joiner in Google's Tekton team, my membership is endorsed by existing contributors @jerop @dibyom

Add EmmaMunley to org

---

working-groups.md

Volunteering for WG facilitating for pipeline Working group meetings.

Volunteering for Pipeline WG facilitating

---

org/org.yaml

Nominated by @pritidesai (Thanks!) in https://github.com/tektoncd/pipeline/pull/6007#issuecomment-1401103016
I started to work on Tekton Pipelines since Sep 2020 (stepped away in early 2021, came back in Aug 2022). I designed and implemented TEP-0121, implemented part of Custom Task Beta, fixed flake test.
I meet all requirements for being a Collaborator, specifically,
PR review requirements: https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+reviewed-by%3AXinruZhang+-author%3AXinruZhang+
/assign @tektoncd/core-maintainers

Add XinruZhang as a Pipeline Reviewer

---

working-groups.md

This commit fixes the working group.md which seems to be broken from rebasing.

Fix working-group format

---

working-groups.md

This PR Adds closing character `|` to table rows that miss it.

Fix the format of working group doc

---

org/org.yaml

> pipeline:
>>  merged:
[TEP-0118: matrix: add matrix.params field](https://github.com/tektoncd/pipeline/pull/5383)
[refactor test Test_storePipelineSpec to use yml parser](https://github.com/tektoncd/pipeline/pull/5561)
[fix 5569 pipelinerun hang on Unknown status due to duplicated task parameters](https://github.com/tektoncd/pipeline/pull/5575)
[fix tekton documentation contributor`s guide link](https://github.com/tektoncd/pipeline/pull/5669)
[Fix task parameter value substitution error due to propagateParams](https://github.com/tektoncd/pipeline/pull/6004)
>> closed:
[feat: support task spec param get value from configmap](https://github.com/tektoncd/pipeline/pull/5358)
>> on reviewing:
[TEP-0097 breakpoints for taskrun](https://github.com/tektoncd/pipeline/pull/5691)
> hub:
>> closed: …

Add chengjoey to org

---

teps/0124-distributed-tracing-for-tasks-and-pipelines.md
teps/README.md

This PR updates the status of  TEP-0124 to `implemented` with the link to implementation PR
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

TEP-0124  Mark as implemented

---

teps/0129-multiple-tekton-instances-per-cluster.md
teps/README.md

TEP proposal about running multiple instances of Tekton Pipeline in a single Tekton cluster.

[TEP-0129] Multiple Tekton instances per Cluster

---

teps/0122-complete-build-instructions-and-parameters.md
teps/README.md

This PR marks the TEP as implemented.
See https://github.com/tektoncd/chains/issues/683 for reference.

TEP-0122: Mask as Implemented

---

org/org.yaml

Self nominating to become a pipeline reviewer:)
I have been contributing to pipelines regularly working on the the pipeline v1 release including the CRD release, pipelineResource migration, pipelineRunStatus migration and features like csi volume workspace support as well. 
And I have met all the requirements for being a project reviewer including the review requirements: https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+reviewed-by%3AJeromeJu+-author%3AJeromeju
/assign @tektoncd/core-maintainers

Add JeromeJu to Reviewers

---

org/org.yaml

Thanks for all your great work Luiz!
Requirements:
✅ Have been actively participating in reviews for at least 3 months or 50% of the project lifetime, whichever is shorter
✅ Has reviewed at least 30 PRs to the codebase. - https://github.com/search?q=repo%3Atektoncd%2Fchains+reviewed-by%3Alcarva&type=pullrequests 
✅ Have been the primary reviewer for at least 10 substantial PRs to the codebase. 
✅ Demonstrates a broad knowledge of the project across multiple areas 
✅ Is able to exercise judgement for the good of the project, independent of their employer, friends, or team 
✅ Be nominated by another Maintainer (with no objections from other Maintainers)
/assign @priyawadhwa

Add lcarva to chains maintainers. 🎉

---

governance.md
org/org.yaml

https://groups.google.com/g/tekton-dev/c/E3QfPG-_oSc
Congrats @jerop!! 🎉 
Thank you @bobcatfish!! 🙏

Update org.yaml and governance.md with Gov Board 2023 election results.

---

teps/0084-endtoend-provenance-collection.md
teps/README.md

- Added relavent implementation PRs for TEP84.
- Marked TEP84 implemented.
Signed-off-by: Chuang Wang <chuangw@google.com>

Mark TEP-0084 implemented

---

teps/0097-breakpoints-for-taskruns-and-pipelineruns.md

add note for why breakpoint.Onfailure use type string instead of boolean

Tep-0097 breakpoint for taskruns and pipelineruns

---

org/org.yaml

Grants ability to /lgtm PRs.
/cc @lcarva @chitrangpatel

Add chitrangpatel to chains collaborators.

---

org/org.yaml

add jkandasa to operator collaborator

---

adopters.md

Today we are using Tekton as our main Pipelines
orchestrator [1]. There is also a series of publication on how we are adopting Tekton on our Delivery Platform [2]
[1]. https://epam.github.io/edp-install/operator-guide/tekton-overview/ [2]. https://medium.com/epam-delivery-platform/part-1-tekton-adoption-d5d47bf1bfc0

Add EPAM Delivery Platform to the list of adopters

---

org/org.yaml

@jsminem has contributed two PRs to tektoncd/pipelines, is working on a third one and will continue to contribute to Tekton on a regular basis.
I endorse @jsminem to join the Tekton org:
https://github.com/tektoncd/community/blob/main/process/contributor-ladder.md#organization-member
Welcome @jsminem!

Add jsminem to the Tekton org

---

working-groups.md

Also fix merge conflict that snuck in for s3c wg.

Update chains WG facilitator list to point to WG doc.

---

teps/0134-concise-pipelines.md
teps/README.md

This is a problem statement for improving the usability of Tekton by addressing the verbosity in `Pipelines`.
/kind tep

TEP-0134: Concise Pipelines - Problem Statement

---

working-groups.md

Scaffold the working group call for Tekton Results.

Tekton Results Working Group

---

teps/0091-trusted-resources.md
teps/README.md

This commit adds current implemention PRs for milestone1 and milestone2.
Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com

[TEP-0091] add implemention PRs for milestones

---

teps/0138-decouple-api-and-feature-versioning.md
teps/README.md

This commit adds the problem statement for decoupling api and feature versioning. This TEP is marked as 'proposed'.

[TEP-0138] Decouple API and Feature Versioning Problem Statement

---

teps/0136-capture-traces-for-task-pod-events.md
teps/README.md

Add missing details and mark the TEP as implementable

[TEP-0136] Mark as implementable

---

governance.md

I was around since the very first "bootstrap" governing board was created 🙏

Update my tenure on governing board

---

org/org.yaml

As a potential new member to Tekton, my membership is endorsed by existing contributors. @dibyom @chuangw6
Following internal onboarding guide, PR based off of https://github.com/tektoncd/community/pull/592

chore: add aaron-prindle to org

---

org/org.yaml

He is contributing to the results. And also satisfy the criteria to be a member.

chore: add avinal to org

---

org/org.yaml

Add me to the community collaborators team so that I can add `/lgtm` to Tekton Results membership pull requests.
See also: https://github.com/tektoncd/community/pull/1052#issuecomment-1671331044

Add adambkaplan to community collaborators

---

org/org.yaml

Will maintain Camel K tasks
Ref #https://github.com/tektoncd/catalog/pull/1166

chore: add squakez

---

working-groups.md

update the Tekton Results Europe + Asia WG meeting to weekly on the same time
fixes #1057

update Tekton results WG meeting

---

org/org.yaml

@jisoolee has contributed 3 PRs to tektoncd/dashboard, is working on a fourth one, and will continue to contribute to Tekton on a regular basis.
I endorse @jisoolee to join the Tekton org:
https://github.com/tektoncd/community/blob/936bdafeebc8392b1a44012630435c2218f2db05/process/contributor-ladder.md#organization-member

Add jisoolee to the Tekton org

---

org/org.yaml

Avinal has been reviewing and raising PRs for results. Let's add him to the results collaborator and 
maintainer.
@dibyom @vdemeester @alan-ghelardi @adambkaplan @sayan-biswas

Add Avinal to Results Collaborator/Maintainer

---

org/org.yaml

Nominated by @pritidesai, @dibyom, @vdemeester and @afrittoli (Thanks!!)
I started to focus on Tekton Pipeline development since March 2023, and have been involved in several projects:
- [TEP-0135: Coschedule PipelineRun Pods](https://github.com/tektoncd/community/blob/main/teps/0135-coscheduling-pipelinerun-pods.md)
- [TEP-0115: Catalog git-based versioning](https://github.com/tektoncd/community/blob/main/teps/0115-tekton-catalog-git-based-versioning.md)
- [TEP-0133: Configure default resolver](https://github.com/tektoncd/community/blob/main/teps/0133-configure-default-resolver.md)
Here is the list of my PRs:
- https://github.com/tektoncd/pipeline/pulls/QuanZhang-William
Here is the list of PRs that I've reviewed:
- https://github.com/tektoncd/pipeline/pulls?q=is%3Aopen+is%3Apr+reviewed-b …

Add QuanZhang-William to Pipeline Reviewer

---

org/org.yaml

Chitrang was added as a maintainer recently and should be part of this team

Add @chitrangpatel to core.maintainers team

---

teps/0140-producing-results-in-matrix.md
teps/README.md

This commit updates the status of TEP-0140 to be implemented. Thank you to everyone involved. 
/kind tep

[TEP-140] Mark TEP-140 As Implemented

---

teps/0140-producing-results-in-matrix.md

This commit adds the implementation reference to TEP-140.
/kind tep

[TEP 140] Add Implementation Reference

---

org/org.yaml

Adding sayan, avinal and Emil (Result Maintainer) to Community collaborators

Add sayan, avinal and Emil (Result Maintainer) to Community

---

org/org.yaml

I have continuously contributed to Tekton Pipeline and been added to Pipeline's maintainer. And also reviewed [TEPs](https://github.com/tektoncd/community/pulls?q=is%3Apr+reviewed-by%3AYongxuanzhang+-author%3AYongxuanzhang+) .

Add Yongxuanzhang to community collaborators

---

adopters.md

Allianz Direct becomes Tekton End User
Original PR: https://github.com/tektoncd/community/pull/1062

Allianz Direct becomes Tekton End User

---

org/org.yaml

Nominated by @vdemeester and following [simpler ladder mechanism][mechanism].
/kind misc
[mechanism]: https://github.com/tektoncd/community/blob/main/process/contributor-ladder.md#reviewer

Add QuanZhang-William to Catlin Reviewer

---

org/org.yaml

Jerome was added as a maintainer in tektoncd/pipeline#7327

Add JeromeJu as a pipelines maintainer

---

teps/0050-ignore-task-failures.md
teps/README.md

This commit adds implementation PRs and mark the TEP as implemented.

[TEP-0050] Implement TEP as implemented

---

org/org.yaml

Both have already contributed to Tekton. And will do so in the future also.

Adding Sudhish and Satyam to org

---

teps/0138-decouple-api-and-feature-versioning.md
teps/README.md

This commit marks TEP0138 as implemented.

Mark TEP0138 as implemented

---

teps/0153-v1-migration-for-tekton-results.md
teps/README.md

TEP discussing the approach to take to introduce the support for v1 APIs of pipelines.

[TEP-0153] Migration of Tekton Results to V1 APIs of Pipelines

---

org/org.yaml

Requesting org membership for `shipit` to contribute and maintain `hugo` task:
[Hugo Task PR](https://github.com/tektoncd/catalog/pull/1234)

chore: add shipit to the tekton org

---

org/org.yaml

Add JeromeJu to plumbings.collaborators

Add JeromeJu to plumbings.collaborators

---

teps/0148-summaryaggregation-api-for-tekton-results.md
teps/README.md

- Implemented in tektoncd/results#642 and released in `v0.9.0`
Signed-off-by: Avinal Kumar <avinal@redhat.com>

TEP-0148: mark as implmented

---

org/org.yaml

Add @chitrangpatel to plumbings.collaborators

Add chitrangpatel to plumbings.collaborators

---

adopters.md

We want to add us as End users.

Add kadaster

---

org/org.yaml

@dhaus67 is a prospective owner in catalog repo

add dhaus67 to community

---

org/org.yaml

Kevin works with me at IBM. He has started working on the Pipelines project. His first [PR](https://github.com/tektoncd/pipeline/pull/7864) was merged recently and his main focus is to implement pipelines in pipelines. We would like to add him as a member of the Tekton organization.
/cc @kgcarr

add Kevin to the Tekton Community

---

teps/0155-store-pipeline-events-in-db.md
teps/README.md

Tekton Results stores so far PipelineRuns, TaskRuns and Logs. This TEP proposes to store Pipeline Events as well to have all historical data from a PipelineRun in Tekton Results.
Added design to the original PR at https://github.com/tektoncd/community/pull/1118

TEP-0155 to store PipelineRun/TaskRun Events to DB

---

org/org.yaml

Request to add renzodavid9 (me 😸 ) to Tekton members. I'm part of Google Tekton team. Thanks!

Request for renzodavid9 to be member of Tekton

---

OWNERS
governance.md
org/org.yaml

As discussed in the May 8 gov board meeting, @chitrangpatel will be taking my place in the Gov Board!

Add chitrangpatel to the gov board while dibyom is on leave

---

org/collaborator.py
org/org.yaml

Related to https://github.com/tektoncd/pipeline/pull/8047 but not only. I think this file needs a bit more cleaning still.
cc @afrittoli @pritidesai @chitrangpatel @dibyom @wlynch

org: update some team members

---

org/org.yaml

I have been working on related projects for the past two years and will also work on Tekton derivative projects in the future.
https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+author%3Acugykw+is%3Amerged+

chore: add cugykw to the tektoncd org

---

teps/0156-whenexpressions-in-step.md
teps/README.md

- This pr update tep-0156 status and add the implemented pull request link.

docs: update tep-0156 status

---

teps/0147-tekton-artifacts-phase1.md
teps/README.md

Marks TEP 0147 as implemented.
/kind misc

Mark TEP-0147 as Implemented

---

governance.md

table formatting changes only; no changes to content

Clean up table of Current Members.

---

org/org.yaml

Alan will help with the work on reducing infra spend. Thank you @AlanGreene !

Add Alan Greene to plumbing maintainers

---

org/org.yaml

* add @jkhelil as member to operator repository

add 'jkhelil' as member to operator repository

---

adopters.md

Add [Aaluda](https://www.alauda.io/) to the list of end users.

chore: Add Alauda to the list of end users

---

org/org.yaml

- add anithapriyanatarajan and mbpavan as members to operator repository

add anithapriyanatarajan and mbpavan as members to operator repository

---

org/org.yaml

Add myself to the org following recent contributions and work on the mcp-server
Signed-off-by: Brady Pratt <bpratt@redhat.com>

add jbpratt to org

---

org/org.yaml

Hi @vdemeester, @afrittoli, @waveywaves ! I believe I am eligible to become a [Reviewer](https://github.com/tektoncd/community/blob/main/process/contributor-ladder.md#reviewer) in Pipelines now 😸.
Wdys?
tektoncd/pipeline#8880

Add twoGiants as a reviewer/collaborator to pipelines.

---

org/org.yaml

This PR adds @infernus01 as a tektoncd org member.

Add @infernus01 to tektoncd member

---

org/org.yaml

Update operator maintainers:
*Add: 
- mbpavan
- anithapriyanatarajan
- pratap0007 as collabortor
*Remove
- sm43
- concaf
- jkandasa

update operator maintainers

---

design-principles.md
process/contributor-ladder.md

added minor doc fixes

---

teps/tools/teps.py

Automatically exclude files like .DS_Store without hardcoding them by augmenting the exlucded files list with pattern matching and reading from .gitignore file

Improve TEP linting tool to use gitignore patterns
